// ── ANALYTICS-CSV ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { categoryColor, categoryIcon, compareTransactionsNewest, currencySymbol, toBase, walletById } from './core.js';
import { deleteTransaction, editTransaction, tagBadge, walletBadge } from './finance.js';
import { renderGoals } from './goals-profile.js';
import { renderBudgets, renderFxConverter, renderFxWidget } from './settings-managers.js';
import { emptyStateHtml, escapeHtml, showToast, syncClickableA11yState } from './ui-widgets.js';

// Transient (not persisted, resets on reload) — whether the transaction
// history below the filters is showing everything or just the collapsed
// TX_LIST_COLLAPSED_COUNT preview. Deliberately a plain module-level flag
// rather than an AppState field: nothing outside this file needs to read
// or persist it, same category as e.g. AppState.expandedCatIdx being
// per-file transient state, just without even needing cross-file access.
let txListExpanded=false;
const TX_LIST_COLLAPSED_COUNT=5;

const toggleTxListExpanded = function(){
  txListExpanded=!txListExpanded;
  renderFinance();
};

const setAnalyticsPeriod = function(period){
  AppState.analyticsPeriod=period;
  document.querySelectorAll('#analytics-period-filter .filter-chip').forEach(c=>c.classList.toggle('active', c.dataset.period===period));
  syncClickableA11yState(document.getElementById('analytics-period-filter'));
  renderAnalytics();
};

function analyticsPredicates(){
  const now=new Date();
  const mPrefix=(y,m)=>`${y}-${String(m+1).padStart(2,'0')}`;
  if(AppState.analyticsPeriod==='month'){
    const p=mPrefix(now.getFullYear(),now.getMonth());
    const prevD=new Date(now.getFullYear(),now.getMonth()-1,1);
    const pp=mPrefix(prevD.getFullYear(),prevD.getMonth());
    return [t=>t.date&&t.date.startsWith(p), t=>t.date&&t.date.startsWith(pp)];
  }
  if(AppState.analyticsPeriod==='prev'){
    const d=new Date(now.getFullYear(),now.getMonth()-1,1);
    const p=mPrefix(d.getFullYear(),d.getMonth());
    const prevD=new Date(d.getFullYear(),d.getMonth()-1,1);
    const pp=mPrefix(prevD.getFullYear(),prevD.getMonth());
    return [t=>t.date&&t.date.startsWith(p), t=>t.date&&t.date.startsWith(pp)];
  }
  if(AppState.analyticsPeriod==='3m'){
    const from=mPrefix(new Date(now.getFullYear(),now.getMonth()-2,1).getFullYear(), new Date(now.getFullYear(),now.getMonth()-2,1).getMonth())+'-01';
    const prevFrom=mPrefix(new Date(now.getFullYear(),now.getMonth()-5,1).getFullYear(), new Date(now.getFullYear(),now.getMonth()-5,1).getMonth())+'-01';
    return [t=>t.date&&t.date>=from, t=>t.date&&t.date>=prevFrom&&t.date<from];
  }
  return [()=>true, null]; // 'all'
}

function renderAnalytics(){
  const section=document.getElementById('analytics-section');
  if(!section) return;
  const [pred,prevPred]=analyticsPredicates();
  const expenseTx=AppState.transactions.filter(t=>t.type==='expense'&&pred(t));
  const incomeTx=AppState.transactions.filter(t=>t.type==='income'&&pred(t));
  const totalExpense=expenseTx.reduce((s,t)=>s+toBase(t.amount,t.currency||'UAH'),0);
  const totalIncome=incomeTx.reduce((s,t)=>s+toBase(t.amount,t.currency||'UAH'),0);
  const net=totalIncome-totalExpense;
  const savingsRate=totalIncome>0?Math.round((net/totalIncome)*100):0;

  const statsBox=document.getElementById('analytics-stats');
  if(statsBox){
    const netColor=net>=0?'var(--green)':'var(--red)';
    const rateColor=savingsRate>=0?'var(--green)':'var(--red)';
    statsBox.innerHTML=`
      <div class="stat-card"><span class="stat-icon" style="background:var(--green);color:#fff">${window.Icon('trendUp')}</span><div class="stat-label">${tr('analytics_income')}</div><div class="stat-val" style="color:var(--green2);font-size:18px">${totalIncome.toLocaleString('uk-UA')} грн</div></div>
      <div class="stat-card"><span class="stat-icon" style="background:var(--red);color:#fff">${window.Icon('cart')}</span><div class="stat-label">${tr('analytics_expense')}</div><div class="stat-val" style="color:var(--red2);font-size:18px">${totalExpense.toLocaleString('uk-UA')} грн</div></div>
      <div class="stat-card"><span class="stat-icon" style="background:${netColor};color:#fff">${window.Icon('coin')}</span><div class="stat-label">${tr('analytics_net')}</div><div class="stat-val" style="color:${net>=0?'var(--green2)':'var(--red2)'};font-size:18px">${net.toLocaleString('uk-UA')} грн</div></div>
      <div class="stat-card"><span class="stat-icon" style="background:${rateColor};color:#fff">${window.Icon('target')}</span><div class="stat-label">${tr('analytics_savings_rate')}</div><div class="stat-val" style="color:${savingsRate>=0?'var(--green2)':'var(--red2)'};font-size:18px">${savingsRate}%</div></div>
    `;
  }

  const insightEl=document.getElementById('analytics-insight');
  if(insightEl){
    if(!prevPred){ insightEl.textContent=''; }
    else{
      const prevExpense=AppState.transactions.filter(t=>t.type==='expense'&&prevPred(t)).reduce((s,t)=>s+toBase(t.amount,t.currency||'UAH'),0);
      if(prevExpense>0 && totalExpense>0){
        const diffPct=Math.round(((totalExpense-prevExpense)/prevExpense)*100);
        if(diffPct>=5) insightEl.innerHTML=`${tr('analytics_prefix')} <strong style="color:var(--red2)">${diffPct}%</strong> ${tr('analytics_suffix_more')}`;
        else if(diffPct<=-5) insightEl.innerHTML=`${tr('analytics_prefix')} <strong style="color:var(--green2)">${Math.abs(diffPct)}%</strong> ${tr('analytics_suffix_less')}`;
        else insightEl.textContent=tr('analytics_same');
      } else insightEl.textContent='';
    }
  }

  const byCatAmount=(txList)=>{
    const byCat={};
    txList.forEach(t=>{ byCat[t.category]=(byCat[t.category]||0)+toBase(t.amount,t.currency||'UAH'); });
    return Object.entries(byCat).sort((a,b)=>b[1]-a[1]);
  };
  const expenseByCat=byCatAmount(expenseTx);
  const incomeByCat=byCatAmount(incomeTx);

  // P2 "insights" from the UI audit: on top of the total-spend trend above,
  // call out the single category that grew the most so the user doesn't
  // have to eyeball the category list to spot it themselves. Skipped for
  // categories with no prior-period spend (an "infinite" % increase from a
  // brand-new category isn't a useful insight) and for categories too small
  // to matter (a materiality floor of 5% of total expense avoids a €2→€10
  // hobby category reading as a dramatic spike).
  if(insightEl && prevPred){
    const prevByCat=Object.fromEntries(byCatAmount(AppState.transactions.filter(t=>t.type==='expense'&&prevPred(t))));
    let topCat=null, topPct=0;
    expenseByCat.forEach(([cat,amt])=>{
      const prevAmt=prevByCat[cat]||0;
      if(prevAmt<=0 || amt<totalExpense*0.05) return;
      const pct=Math.round(((amt-prevAmt)/prevAmt)*100);
      if(pct>=20 && pct>topPct){ topPct=pct; topCat=cat; }
    });
    if(topCat){
      const line=`${tr('analytics_cat_insight_prefix')} «${escapeHtml(topCat)}»: <strong style="color:var(--red2)">+${topPct}%</strong> ${tr('analytics_cat_insight_suffix')}`;
      insightEl.innerHTML = insightEl.innerHTML ? `${insightEl.innerHTML}<div style="margin-top:4px">${line}</div>` : line;
    }
  }

  const donut=document.getElementById('analytics-donut');
  if(donut){
    if(!expenseByCat.length || totalExpense<=0){
      donut.style.background='var(--bg3)';
      donut.innerHTML=`<div class="analytics-donut-hole"></div><div class="analytics-donut-center"><span class="analytics-donut-label">${tr('analytics_no_data')}</span></div>`;
    }else{
      let acc=0;
      const stops=expenseByCat.map(([cat,amt])=>{
        const color=categoryColor(cat);
        const startPct=acc/totalExpense*100;
        acc+=amt;
        return `${color} ${startPct}% ${acc/totalExpense*100}%`;
      }).join(', ');
      donut.style.background=`conic-gradient(${stops})`;
      donut.innerHTML=`<div class="analytics-donut-hole"></div><div class="analytics-donut-center"><span class="analytics-donut-total">${totalExpense.toLocaleString('uk-UA')}</span><span class="analytics-donut-label">${tr('finance_amount_prefix')}</span></div>`;
    }
    // Retrigger the CSS entrance animation on every data change, not just
    // the first paint — a CSS animation only fires once for an element that
    // stays in the DOM, so the class has to be removed, the removal forced
    // to take effect (reading offsetWidth forces a reflow), then re-added.
    donut.classList.remove('donut-anim');
    void donut.offsetWidth;
    donut.classList.add('donut-anim');
  }

  const renderCatList=(entries,total)=>{
    if(!entries.length) return `<div class="mgr-empty">${tr('analytics_no_data')}</div>`;
    return entries.map(([cat,amt])=>{
      const pct=total>0?Math.round(amt/total*100):0;
      const color=categoryColor(cat);
      return `<div class="analytics-cat-row">
        <div class="analytics-cat-top">
          <span class="analytics-cat-name"><span class="icon-badge icon-badge-sm" style="background:${color};flex-shrink:0">${window.Icon(categoryIcon(cat))}</span><span>${escapeHtml(cat)}</span></span>
          <span class="analytics-cat-amt">${amt.toLocaleString('uk-UA')} грн · ${pct}%</span>
        </div>
        <div class="salary-bar-wrap"><div class="salary-bar-fill" style="width:${pct}%;background:${color}"></div></div>
      </div>`;
    }).join('');
  };
  const expBox=document.getElementById('analytics-expense-list');
  if(expBox) expBox.innerHTML=renderCatList(expenseByCat,totalExpense);
  const incBox=document.getElementById('analytics-income-list');
  if(incBox) incBox.innerHTML=renderCatList(incomeByCat,totalIncome);
}

export function computeWalletBalances(){
  const wb={};
  AppState.wallets.forEach(w=>{wb[w.id]=0;});
  AppState.transactions.forEach(t=>{
    const w=t.wallet;
    if(t.type==='income')   {if(wb[w]!==undefined)wb[w]+=t.amount;}
    if(t.type==='expense')  {if(wb[w]!==undefined)wb[w]-=t.amount;}
    if(t.type==='transfer') {const tw=t.targetWallet;if(wb[w]!==undefined)wb[w]-=t.amount;if(wb[tw]!==undefined)wb[tw]+=(t.targetAmount!=null?t.targetAmount:t.amount);}
  });
  return wb;
}

function renderFinanceStartGuide(){
  const box=document.getElementById('finance-start-guide');
  if(!box) return;
  if(AppState.transactions.length>0){ box.innerHTML=''; box.style.display='none'; return; }
  const hasWallet=AppState.wallets.length>0;
  box.style.display='block';
  box.innerHTML=`
    <div class="start-guide">
      <div class="start-guide-title">${escapeHtml(tr('finance_start_title'))}</div>
      <div class="start-guide-desc">${escapeHtml(tr('finance_start_desc'))}</div>
      <div class="start-guide-steps">
        <button type="button" class="start-step ${hasWallet?'done':''}" data-action="open-wallets-manager">
          <span class="start-step-index">${hasWallet?window.Icon('check'):'1'}</span>
          <span><span class="start-step-title">${escapeHtml(tr('finance_start_wallet'))}</span><span class="start-step-sub">${escapeHtml(tr('finance_start_wallet_sub'))}</span></span>
        </button>
        <button type="button" class="start-step" data-action="open-new-tx-modal">
          <span class="start-step-index">2</span>
          <span><span class="start-step-title">${escapeHtml(tr('finance_start_tx'))}</span><span class="start-step-sub">${escapeHtml(tr('finance_start_tx_sub'))}</span></span>
        </button>
        <button type="button" class="start-step" data-action="open-widgets-manager">
          <span class="start-step-index">3</span>
          <span><span class="start-step-title">${escapeHtml(tr('finance_start_widgets'))}</span><span class="start-step-sub">${escapeHtml(tr('finance_start_widgets_sub'))}</span></span>
        </button>
      </div>
    </div>`;
}

// Cold-start only: called once from js/app-init.js's init() when there was
// no local config cache to paint from instantly (a brand-new device/first
// sign-in — see CLAUDE.md's "Client-side caching/sync"), so the balance
// hero and transaction list show shimmer placeholders instead of a
// momentarily-empty/zero state while the first fbLoadNow() round-trip is
// in flight. fbLoadNow() always calls renderFinance() again once it
// resolves, which overwrites these placeholders with real content — no
// separate cleanup call needed.
export function renderFinanceSkeleton(){
  const bc=document.getElementById('fin-balances');
  if(bc){
    bc.innerHTML=`
      <div class="skeleton-block" style="width:140px;height:11px;margin-bottom:8px"></div>
      <div class="skeleton-block" style="width:190px;height:30px;margin-bottom:14px"></div>
      <div style="display:flex;gap:8px;margin-bottom:16px">
        <div class="skeleton-block" style="flex:1;height:54px;border-radius:16px"></div>
        <div class="skeleton-block" style="flex:1;height:54px;border-radius:16px"></div>
      </div>
      <div style="display:flex;gap:8px">
        <div class="skeleton-block" style="width:100px;height:32px;border-radius:999px"></div>
        <div class="skeleton-block" style="width:100px;height:32px;border-radius:999px"></div>
      </div>`;
  }
  const lc=document.getElementById('tx-list-container');
  if(lc) lc.innerHTML=`<div class="skeleton-row"></div><div class="skeleton-row"></div><div class="skeleton-row"></div>`;
}

// Inner HTML for one .tx-item row's content — extracted from renderFinance()
// so it can be reused both when creating a brand-new row and when
// refreshing an existing (reused) one's content in place. Does not include
// the outer .tx-item element itself, which persists across renders for
// unchanged transactions (see renderFinance()'s targeted-update comment).
function txItemInnerHtml(t){
  const df=t.date?t.date.split('-').reverse().join('.'):'';
  const cur=currencySymbol(t.currency||'UAH');
  let cls='',amtStr='';
  if(t.type==='income')   {cls='income';  amtStr=`+${t.amount.toLocaleString('uk-UA')} ${cur}`;}
  if(t.type==='expense')  {cls='expense'; amtStr=`−${t.amount.toLocaleString('uk-UA')} ${cur}`;}
  if(t.type==='transfer') {cls='transfer';amtStr=`${t.amount.toLocaleString('uk-UA')} ${cur}`;}
  const catIcon=window.Icon(categoryIcon(t.category));
  const wBadge=walletBadge(t.wallet);
  const convNote=(t.targetWallet&&t.targetCurrency&&t.targetCurrency!==t.currency)
    ? `<span style="font-size:12px;color:var(--muted)">(${(t.targetAmount||0).toLocaleString('uk-UA')} ${currencySymbol(t.targetCurrency)})</span>` : '';
  const twBadge=t.targetWallet?`<span style="color:var(--muted2);font-size:12px">→</span>${walletBadge(t.targetWallet)}${convNote}`:'';
  const tagBadges=(t.tags||[]).map(tagBadge).filter(Boolean).join('');
  // Pencil dropped on purpose: tapping the row already opens edit (see the
  // click listener on the outer .tx-item node itself), so a second
  // always-visible edit button was pure duplication. Delete now lives
  // behind a swipe-to-reveal panel (Telegram/Gmail-style) instead of an
  // always-visible icon — .tx-swipe-delete sits *outside* .tx-item-inner
  // (a sibling, not a child) so the inner wrapper's slide-left transform
  // (CSS :hover/:focus-within, or JS during a touch swipe — see
  // setupTxSwipe() below) reveals it without moving it.
  return `
      <div class="tx-item-inner">
        <div class="tx-left-wrap">
          <div class="icon-badge" style="background:${categoryColor(t.category)}">${catIcon}</div>
          <div class="tx-left">
            <div class="tx-cat"><span>${escapeHtml(t.category)}${t.subcategory?' · '+escapeHtml(t.subcategory):''}</span>${wBadge}${twBadge}</div>
            <div class="tx-meta">${df}${t.comment?' · '+escapeHtml(t.comment):''}</div>
            ${tagBadges?`<div style="display:flex;flex-wrap:wrap;gap:4px;margin-top:5px">${tagBadges}</div>`:''}
          </div>
        </div>
        <div class="tx-right">
          <span class="tx-amount ${cls}">${amtStr}</span>
        </div>
      </div>
      <button class="tx-swipe-delete" data-action="delete-transaction" data-id="${t.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>`;
}

const TX_SWIPE_REVEAL_PX=60;
const TX_SWIPE_OPEN_THRESHOLD=30; // half the reveal width - matches most swipe-list conventions ("did you mean to open this?")

function closeAllTxSwipes(except){
  document.querySelectorAll('.tx-item.swipe-open').forEach(el=>{ if(el!==except) el.classList.remove('swipe-open'); });
}

// Touch-swipe-to-reveal-delete (Telegram/Gmail-style) — mirrors
// js/ui-widgets.js's initSheetDrag() pointer-event pattern (drag while
// held, snap to open/closed on release) but horizontal instead of
// vertical and per-row instead of per-modal. Mouse/keyboard users reach
// the same .tx-swipe-delete button via CSS :hover/:focus-within instead
// (see index.html) — this only needs to handle an actual touch/pen drag.
// Called once per node at creation time (like the click/keydown listeners
// above); .tx-item-inner is re-queried on every drag rather than cached,
// since it gets replaced wholesale on every re-render of a reused row.
function setupTxSwipe(item){
  let startX=0,startY=0,dx=0,dragging=false,decided=false,horizontal=false;
  item.addEventListener('pointerdown',e=>{
    if(e.pointerType==='mouse') return; // mouse gets the CSS :hover reveal instead
    startX=e.clientX; startY=e.clientY; dx=0; dragging=true; decided=false; horizontal=false;
  });
  item.addEventListener('pointermove',e=>{
    if(!dragging) return;
    const ddx=e.clientX-startX, ddy=e.clientY-startY;
    if(!decided){
      // Wait for enough movement to tell a horizontal swipe (this
      // gesture) from a vertical scroll (must stay untouched) apart -
      // only takes over (setPointerCapture) once it's clearly horizontal.
      if(Math.abs(ddx)<6 && Math.abs(ddy)<6) return;
      decided=true;
      horizontal=Math.abs(ddx)>Math.abs(ddy);
      if(horizontal){
        try{ item.setPointerCapture(e.pointerId); }catch(err){}
        item.classList.add('swipe-dragging');
      }
    }
    if(!horizontal) return;
    dx=Math.max(-TX_SWIPE_REVEAL_PX*1.3, Math.min(0,ddx));
    // Shrinks .tx-item-inner's own width (from its right edge) rather than
    // translating it — see index.html's .tx-item-inner comment for why a
    // transform clips the category icon on the left instead.
    const inner=item.querySelector('.tx-item-inner');
    if(inner) inner.style.width=`calc(100% - ${-dx}px)`;
  });
  function endDrag(){
    if(!dragging) return;
    dragging=false;
    item.classList.remove('swipe-dragging');
    const inner=item.querySelector('.tx-item-inner');
    if(inner) inner.style.width=''; // hand off to the .swipe-open CSS class below
    if(horizontal){
      if(dx<-TX_SWIPE_OPEN_THRESHOLD){ closeAllTxSwipes(item); item.classList.add('swipe-open'); }
      else item.classList.remove('swipe-open');
    }
  }
  item.addEventListener('pointerup',endDrag);
  item.addEventListener('pointercancel',endDrag);
}

export function renderFinance(){
  const wb=computeWalletBalances();
  // Total balance is a UAH-equivalent sum across wallets that may each hold
  // a different currency — computed after the per-wallet loop, not
  // incrementally, since a raw income/expense sum would be meaningless
  // once wallets stop sharing one currency.
  let bal=0;
  AppState.wallets.forEach(w=>{ bal+=toBase(wb[w.id]||0, w.currency||'UAH'); });
  // This month's income/expense, for the two highlighted mini-stat cards
  // (matching the two-mini-card dashboard pattern the user asked for) —
  // computed the same way renderFinanceChart() computes its monthly totals.
  const now=new Date();
  const curPrefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
  let monthInc=0,monthExp=0;
  AppState.transactions.forEach(t=>{
    if(!t.date||!t.date.startsWith(curPrefix)) return;
    if(t.type==='income') monthInc+=toBase(t.amount,t.currency||'UAH');
    else if(t.type==='expense') monthExp+=toBase(t.amount,t.currency||'UAH');
  });

  // Balance cards (total + this month's income/expense + one per wallet)
  const bc=document.getElementById('fin-balances');
  if(bc){
    const walletCurrencies=new Set(AppState.wallets.map(w=>w.currency||'UAH'));
    const multiCurrency=walletCurrencies.size>1;
    let html=`<div class="hero-balance-label">${tr(multiCurrency?'finance_total_balance_approx':'finance_total_balance')}</div><div class="hero-balance-val">${multiCurrency?'≈ ':''}${bal.toLocaleString('uk-UA')} грн</div>`;
    if(multiCurrency) html+=`<div class="hero-balance-hint">${tr('finance_total_balance_hint')}</div>`;
    html+=`<div class="fin-mini-stat-row">
      <div class="fin-mini-stat income"><div class="fin-mini-stat-label">${tr('finance_month_income')}</div><div class="fin-mini-stat-val">+${monthInc.toLocaleString('uk-UA')} грн</div></div>
      <div class="fin-mini-stat expense"><div class="fin-mini-stat-label">${tr('finance_month_expense')}</div><div class="fin-mini-stat-val">−${monthExp.toLocaleString('uk-UA')} грн</div></div>
    </div>`;
    html+='<div class="wallet-chip-row">';
    AppState.wallets.forEach(w=>{
      html+=`<span class="wallet-chip"><span class="wallet-chip-dot" style="background:${w.color}"></span><span class="wallet-chip-name">${escapeHtml(w.name)}</span><span class="wallet-chip-val">${(wb[w.id]||0).toLocaleString('uk-UA')} ${currencySymbol(w.currency||'UAH')}</span></span>`;
    });
    html+='</div>';
    bc.innerHTML=html;
  }

  renderFinanceStartGuide();
  renderFxWidget();
  renderFxConverter();
  renderBudgets();
  renderGoals();
  renderAnalytics();

  let filtered=AppState.txFilter==='all'?AppState.transactions:AppState.transactions.filter(t=>t.type===AppState.txFilter);
  if(AppState.txCategoryFilter) filtered=filtered.filter(t=>t.category===AppState.txCategoryFilter);
  if(AppState.txSearch){
    const walletName=id=>(walletById(id)?.name||'').toLowerCase();
    filtered=filtered.filter(t=>[t.comment,t.category,t.subcategory,walletName(t.wallet),walletName(t.targetWallet),t.currency,t.targetCurrency]
      .some(v=>String(v||'').toLowerCase().includes(AppState.txSearch)));
  }
  // Newest-first, independent of AppState.transactions' own array order —
  // js/color-picker.js's fbLoadNow() already sorts on load, but re-sorting
  // a copy here too keeps the *displayed* order correct even mid-session
  // (e.g. right after editing a transaction to a backdated date, with no
  // reload in between) without needing every mutation site to maintain a
  // sorted-array invariant by hand.
  filtered=[...filtered].sort(compareTransactionsNewest);
  const lc=document.getElementById('tx-list-container');
  const tc=document.getElementById('tx-count');
  if(!lc) return;

  const catChip=document.getElementById('tx-cat-filter-chip');
  if(catChip){
    if(AppState.txCategoryFilter){ catChip.style.display='block'; document.getElementById('tx-cat-filter-label').textContent=AppState.txCategoryFilter; }
    else catChip.style.display='none';
  }

  if(tc) tc.textContent=filtered.length+' '+tr('finance_records_suffix');

  if(filtered.length===0){
    const isSearching=!!AppState.txSearch || AppState.txFilter!=='all' || !!AppState.txCategoryFilter;
    lc.innerHTML=emptyStateHtml({
      icon:isSearching?'search':'wallet',
      title:tr(isSearching?'finance_search_empty_title':'finance_empty_title'),
      desc:tr(isSearching?'finance_search_empty_desc':'finance_empty_desc'),
      action:isSearching?'':tr('finance_new_tx'),
      actionName:isSearching?'':'open-new-tx-modal'
    });
    return;
  }
  // Coming from the empty state (emptyStateHtml() above) or the cold-start
  // skeleton (renderFinanceSkeleton()) leaves non-.tx-item markup
  // (.empty-state / .skeleton-row) sitting in lc that the targeted update
  // below wouldn't otherwise know to remove, since it only tracks
  // .tx-item/.tx-view-all-btn children — clear anything else out first.
  lc.querySelectorAll(':scope > :not(.tx-item):not(.tx-view-all-btn)').forEach(node=>node.remove());

  const showAll=txListExpanded || filtered.length<=TX_LIST_COLLAPSED_COUNT;
  const visible=showAll?filtered:filtered.slice(0,TX_LIST_COLLAPSED_COUNT);

  // Targeted update: reuse existing .tx-item DOM nodes (matched by
  // data-id) instead of tearing down and rebuilding the whole list on
  // every renderFinance() call — this function is called from ~20 places
  // across js/*.js for state changes that often have nothing to do with
  // any specific transaction (renaming a wallet, editing a budget,
  // switching tabs back). Reusing nodes means unrelated re-renders don't
  // replay the .tx-item entrance animation (CSS animations don't restart
  // on innerHTML/attribute changes to an already-connected node, only on
  // fresh insertion) and don't need to re-register the click/keydown
  // listeners, which stay bound to the persisted node. Only actually-new
  // transactions get a freshly created node — and therefore the pop-in
  // animation — which is also the more correct UX (a genuinely new
  // transaction should visibly appear; an unrelated re-render shouldn't
  // make the whole list flicker). A matched row's *content* is still
  // always regenerated from the current transaction/wallet/tag/category
  // state (txItemInnerHtml()), so nothing here risks showing stale data —
  // this only changes whether the outer element is reused, not what's
  // computed into it.
  const existingById=new Map();
  lc.querySelectorAll(':scope > .tx-item').forEach(node=>{ existingById.set(node.dataset.txId, node); });

  let newNodeCount=0;
  let prevNode=null;
  visible.forEach(t=>{
    const idStr=String(t.id);
    let item=existingById.get(idStr);
    const isNew=!item;
    if(isNew){
      item=document.createElement('div');
      item.className='tx-item';
      item.tabIndex=0;
      item.style.cursor='pointer';
      item.dataset.txId=idStr;
      item.addEventListener('click',()=>{
        // A swiped-open row's first tap just closes it again (matches the
        // common swipe-list convention, e.g. iOS Mail) instead of also
        // opening edit right after the drag gesture ends - a touchend can
        // otherwise register as a click on the same element.
        if(item.classList.contains('swipe-open')){ item.classList.remove('swipe-open'); return; }
        editTransaction(t.id);
      });
      item.addEventListener('keydown',e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); editTransaction(t.id); } });
      setupTxSwipe(item);
    }else{
      existingById.delete(idStr); // consumed — whatever's left afterward gets removed below
    }
    item.innerHTML=txItemInnerHtml(t);
    item.style.animationDelay=isNew?Math.min(newNodeCount*35,280)+'ms':'';
    if(isNew) newNodeCount++;
    // Move into position only if it isn't already there — insertBefore on
    // an already-correctly-placed node is effectively a no-op in the DOM,
    // but skipping the call entirely avoids even that overhead for the
    // common case where nothing reordered.
    if(prevNode){
      if(prevNode.nextSibling!==item) lc.insertBefore(item, prevNode.nextSibling);
    }else if(lc.firstChild!==item){
      lc.insertBefore(item, lc.firstChild);
    }
    prevNode=item;
  });
  // Whatever's left in existingById is a row for a transaction no longer
  // in `visible` (deleted, or filtered/collapsed out) — remove it.
  existingById.forEach(node=>node.remove());

  // The "view all"/"show less" button always goes last; simplest to just
  // remove and re-append rather than diff a single control element.
  const oldMoreBtn=lc.querySelector(':scope > .tx-view-all-btn');
  if(oldMoreBtn) oldMoreBtn.remove();
  if(filtered.length>TX_LIST_COLLAPSED_COUNT){
    const moreBtn=document.createElement('button');
    moreBtn.type='button';
    moreBtn.className='btn btn-ghost tx-view-all-btn';
    moreBtn.dataset.action='toggle-tx-list-expanded';
    moreBtn.textContent=showAll ? tr('finance_show_less') : `${tr('finance_view_all')} (${filtered.length})`;
    lc.appendChild(moreBtn);
  }
}

const clearTxCategoryFilter = function(){
  AppState.txCategoryFilter=null;
  renderFinance();
};

function csvEscape(v){
  const s=String(v==null?'':v);
  return /[;"\n\r]/.test(s) ? '"'+s.replace(/"/g,'""')+'"' : s;
}

const exportTransactionsCSV = function(){
  if(!AppState.transactions.length){ showToast(tr('csv_empty'),'xmark'); return; }
  const TX_TYPE_LABEL={income:tr('finance_type_income').replace('+ ',''),expense:tr('finance_type_expense').replace('− ',''),transfer:tr('finance_type_transfer').replace('⇄ ','')};
  const header=[tr('csv_date'),tr('csv_type'),tr('finance_category'),tr('finance_subcategory'),tr('finance_wallet'),tr('finance_amount_prefix'),tr('csv_currency'),tr('csv_to'),tr('csv_transfer_amount'),tr('csv_transfer_currency'),tr('finance_comment')];
  const sorted=[...AppState.transactions].sort((a,b)=>(a.date||'').localeCompare(b.date||''));
  const rows=sorted.map(t=>[
    t.date||'',
    TX_TYPE_LABEL[t.type]||t.type,
    t.category||'',
    t.subcategory||'',
    (walletById(t.wallet)||{}).name||'',
    String(t.amount).replace('.',','),
    t.currency||'UAH',
    t.targetWallet?((walletById(t.targetWallet)||{}).name||''):'',
    t.targetWallet?String(t.targetAmount??t.amount).replace('.',','):'',
    t.targetWallet?(t.targetCurrency||t.currency||'UAH'):'',
    t.comment||''
  ]);
  const csv=[header,...rows].map(r=>r.map(csvEscape).join(';')).join('\r\n');
  const blob=new Blob(['﻿'+csv], {type:'text/csv;charset=utf-8;'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a');
  a.href=url; a.download=`rytm-finansy-${new Date().toISOString().split('T')[0]}.csv`;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  setTimeout(()=>URL.revokeObjectURL(url), 1000);
  showToast(tr('csv_downloaded'),'download');
};

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_analytics_csv__(){
// This file's dynamic actions are CSP-safe data-action handlers now. The
// analytics-period chips already carry data-period, so set-analytics-period
// reads ds.period directly instead of adding a redundant attribute.
const CLICK_ACTIONS = {
  'set-analytics-period': ds=>setAnalyticsPeriod(ds.period),
  'clear-tx-category-filter': ()=>clearTxCategoryFilter(),
  'export-transactions-csv': ()=>exportTransactionsCSV(),
  'toggle-tx-list-expanded': ()=>toggleTxListExpanded(),
  // The swipe-revealed delete button on a .tx-item. Needs stopPropagation
  // so the tap doesn't bubble to the row's own click→editTransaction
  // listener (which would open the edit modal instead of deleting). This
  // used to be an inline onclick="event.stopPropagation();deleteTransaction()"
  // — silently dead under the site's CSP (script-src has no 'unsafe-inline',
  // so inline event-handler attributes never execute), which is exactly why
  // "delete opened edit" on the live site: the inline handler no-op'd and
  // the tap fell through to the row's edit listener. As a real delegated
  // handler it runs normally. Dispatcher below passes the event for this.
  'delete-transaction': (ds,e)=>{ if(e) e.stopPropagation(); deleteTransaction(ds.id); },
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset, e);
}, true);

// Closes any swiped-open .tx-item (see setupTxSwipe() above) the moment a
// pointer goes down anywhere outside it — tapping a different row,
// scrolling, or interacting with anything else on the page all close it,
// matching how every other swipe-list app behaves (only one row open at a
// time, and it doesn't linger open once you've moved on).
document.addEventListener('pointerdown', e=>{
  document.querySelectorAll('.tx-item.swipe-open').forEach(el=>{
    if(!el.contains(e.target)) el.classList.remove('swipe-open');
  });
});
}
