// ── APP-INIT ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { renderFinance } from './analytics-csv.js';
import { maybeShowSettingsTip } from './auth.js';
import { renderCalendar, renderFinanceChart, renderIncomeChart, runAutoFillCheck } from './calendar.js';
import { fbLoadNow, normalizeDebtData, renderProfilesUI, seedConfigFromDocs } from './color-picker.js';
import { applyWidgetVisibility, normalizeWallets, renderPremiumUI, sanitizeWidgetOrder } from './core.js';
import { renderDebt } from './debt.js';
import { applyAutoRuleToForm, fillSubcats, setFinanceType, updateAmountLabel } from './finance.js';
import { loadProfilesMeta, lsKey } from './firebase-sync.js';
import { renderProfileUI } from './goals-profile.js';
import { getMessagingInstance, loadNotifSettings, populateNotifTimeSelects, pushEnabledKey, renderNotifUI, runNotificationChecks } from './notifications.js';
import { maybeAutoUpdateRates, populateFxConverterSelects, renderFxConverter, setupModalAccessibility, toggleHideAmounts } from './settings-managers.js';
import { renderShoppingList } from './shopping.js';
import { enhanceAllSelects, filterSettings, setupAccessibleSettingsRows, setupCollapsibleFinanceSections } from './ui-widgets.js';

export async function init(){
  const now=new Date();
  if(!AppState.initialized){
    AppState.initialized=true;
    // Month select
    const ms=document.getElementById('select-month');
    AppState.MONTHS.forEach((m,i)=>{
      const o=document.createElement('option');
      o.value=i; o.textContent=m;
      if(i===now.getMonth())o.selected=true;
      ms.appendChild(o);
    });
    // Year select
    const ys=document.getElementById('select-year');
    for(let y=now.getFullYear()-2;y<=now.getFullYear()+1;y++){
      const o=document.createElement('option');
      o.value=y; o.textContent=y;
      if(y===now.getFullYear())o.selected=true;
      ys.appendChild(o);
    }
    // Refresh the subcategory list whenever the user picks a different category
    document.getElementById('fin-category')?.addEventListener('change', fillSubcats);
    // Keep the amount field's currency label matched to the chosen wallet
    document.getElementById('fin-wallet')?.addEventListener('change', updateAmountLabel);
    // Auto-categorize as the user types the comment, per their rules
    document.getElementById('fin-comment')?.addEventListener('input', applyAutoRuleToForm);
    setupAccessibleSettingsRows();
    setupCollapsibleFinanceSections();
    setupModalAccessibility();
    loadNotifSettings();
    populateNotifTimeSelects();
    renderNotifUI();
    document.addEventListener('visibilitychange', ()=>{ if(document.visibilityState==='visible'){ runNotificationChecks(); runAutoFillCheck(); } });
    setInterval(()=>{ runNotificationChecks(); runAutoFillCheck(); }, 5*60*1000);
  }
  // Local cache first (namespaced to the signed-in user)
  try{const k=lsKey('shifts'); const s=k&&localStorage.getItem(k); if(s) AppState.shifts=JSON.parse(s);}catch{}
  try{const k=lsKey('tx'); const t=k&&localStorage.getItem(k); if(t) AppState.transactions=JSON.parse(t);}catch{}
  try{const k=lsKey('recurring'); const r=k&&localStorage.getItem(k); if(r) AppState.recurring=JSON.parse(r);}catch{}
  try{const k=lsKey('shopping'); const s2=k&&localStorage.getItem(k); if(s2) AppState.shoppingList=JSON.parse(s2);}catch{}
  try{const k=lsKey('debt'); const d=k&&localStorage.getItem(k); if(d){const norm=normalizeDebtData(JSON.parse(d)); if(norm){AppState.debts=norm.debts; AppState.currentDebtId=norm.currentDebtId;}}}catch{}
  // Config cache (shift types / wallets / categories); seed sane defaults
  // if none cached yet so the first render before cloud load doesn't break.
  let cfgCached=false;
  try{const k=lsKey('cfg'); const c=k&&localStorage.getItem(k); if(c){const o=JSON.parse(c);
    if(o&&o.shiftTypes&&o.wallets&&o.categories){AppState.shiftTypes=o.shiftTypes; AppState.autoFillSchedule=(o.autoFillSchedule&&typeof o.autoFillSchedule==='object')?{enabled:!!o.autoFillSchedule.enabled, typeId:o.autoFillSchedule.typeId||'', pattern:o.autoFillSchedule.pattern||'every', anchorDate:o.autoFillSchedule.anchorDate||''}:{enabled:false,typeId:'',pattern:'every',anchorDate:''}; AppState.wallets=o.wallets; AppState.categories=o.categories; AppState.budgets=o.budgets||{}; AppState.subcategories=o.subcategories||{}; AppState.currencyRates=o.currencyRates||{}; AppState.tags=Array.isArray(o.tags)?o.tags:[]; AppState.autoRules=Array.isArray(o.autoRules)?o.autoRules:[]; AppState.goals=Array.isArray(o.goals)?o.goals:[]; AppState.profile=(o.profile&&typeof o.profile==='object')?o.profile:{nickname:'',avatar:''}; AppState.subscription=(o.subscription&&typeof o.subscription==='object')?{plan:o.subscription.plan||'free',expiresAt:o.subscription.expiresAt||null}:{plan:'free',expiresAt:null}; AppState.widgets=(o.widgets&&typeof o.widgets==='object')?{rates:o.widgets.rates!==false,converter:o.widgets.converter!==false,analytics:o.widgets.analytics!==false,chart:o.widgets.chart!==false,goals:o.widgets.goals!==false}:{rates:true,converter:true,analytics:true,chart:true,goals:true}; AppState.widgetOrder=sanitizeWidgetOrder(o.widgetOrder); normalizeWallets(); AppState.catBackfillDone=!!o.catBackfillDone; AppState.catLegacyMerged=!!o.catLegacyMerged; cfgCached=true;}}}catch{}
  if(!cfgCached) seedConfigFromDocs(null,null);
  // Date input
  const di=document.getElementById('fin-date');
  if(di) di.value=now.toISOString().split('T')[0];
  switchTab('finance');
  setFinanceType('income');
  populateFxConverterSelects(); renderFxConverter();
  enhanceAllSelects();
  renderProfileUI(); renderPremiumUI();
  try{ await loadProfilesMeta(); }catch(e){ console.error('profiles meta load failed', e); }
  renderProfilesUI();
  // Load from cloud (auto — no manual save/load step needed)
  await fbLoadNow();
  renderProfileUI(); renderPremiumUI(); applyWidgetVisibility(); renderNotifUI();
  runNotificationChecks();
  maybeAutoUpdateRates();
  // Re-attach the foreground push handler if this device already has push
  // enabled from a previous session (registering the token itself only
  // happens once, in enablePushNotifications()).
  if(localStorage.getItem(pushEnabledKey())==='1') getMessagingInstance().catch(e=>console.warn('push init failed',e));
}

export function switchTab(tab){
  const tappedIcon=document.querySelector(`#nav-${tab} .tab-icon-wrap`);
  if(tappedIcon){
    tappedIcon.classList.remove('tab-pop');
    void tappedIcon.offsetWidth;
    tappedIcon.classList.add('tab-pop');
  }
  document.getElementById('nav-shifts').classList.toggle('active',tab==='shifts');
  document.getElementById('nav-finance').classList.toggle('active',tab==='finance');
  document.getElementById('nav-debt').classList.toggle('active',tab==='debt');
  document.getElementById('nav-shopping').classList.toggle('active',tab==='shopping');
  document.getElementById('nav-settings').classList.toggle('active',tab==='settings');
  document.getElementById('tab-shifts').style.display  = tab==='shifts'  ? 'block':'none';
  document.getElementById('tab-finance').style.display = tab==='finance' ? 'block':'none';
  document.getElementById('tab-debt').style.display    = tab==='debt'    ? 'block':'none';
  document.getElementById('tab-shopping').style.display= tab==='shopping'? 'block':'none';
  document.getElementById('tab-settings').style.display= tab==='settings'? 'block':'none';
  if(tab==='shifts')  {renderCalendar(); renderIncomeChart();}
  if(tab==='finance') {setupCollapsibleFinanceSections(); applyWidgetVisibility(); renderFinance(); renderFinanceChart();}
  if(tab==='debt') {renderDebt();}
  if(tab==='shopping') {renderShoppingList();}
  if(tab==='settings') {filterSettings(document.getElementById('settings-search-input')?.value||''); maybeShowSettingsTip();}
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_app_init__(){
document.addEventListener('click', (e)=>{
  const el=e.target.closest('.btn-primary, .fin-fab, .icon-badge');
  if(!el) return;
  el.classList.remove('ui-pop');
  void el.offsetWidth;
  el.classList.add('ui-pop');
});

// Topbar + bottom-nav wiring — these used to be inline onclick="" HTML
// attributes (which need window.foo globals to resolve, see CLAUDE.md's
// "js/ module layout" point 3); real addEventListener wiring here means
// switchTab/toggleHideAmounts/fbLoadNow only need to be real module
// exports, not also attached to window.
document.getElementById('topbar-avatar')?.addEventListener('click', ()=>switchTab('settings'));
document.getElementById('btn-hide-amounts')?.addEventListener('click', ()=>toggleHideAmounts());
document.getElementById('btn-refresh')?.addEventListener('click', ()=>fbLoadNow());
document.getElementById('nav-finance')?.addEventListener('click', ()=>switchTab('finance'));
document.getElementById('nav-shifts')?.addEventListener('click', ()=>switchTab('shifts'));
document.getElementById('nav-debt')?.addEventListener('click', ()=>switchTab('debt'));
document.getElementById('nav-shopping')?.addEventListener('click', ()=>switchTab('shopping'));
document.getElementById('nav-settings')?.addEventListener('click', ()=>switchTab('settings'));
}
