// ── APP-INIT ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { renderFinance, renderFinanceSkeleton } from './analytics-csv.js';
import { maybeShowSettingsTip } from './auth.js';
import { renderCalendar, renderFinanceChart, renderIncomeChart, renderShiftsSkeleton, runAutoFillCheck } from './calendar.js';
import { fbLoadNow, normalizeDebtData, renderProfilesUI, seedConfigFromDocs } from './color-picker.js';
import { applyWidgetVisibility, normalizeWallets, renderPremiumUI, sanitizeWidgetOrder } from './core.js';
import { renderDebt } from './debt.js';
import { applyAutoRuleToForm, fillSubcats, setFinanceType, updateAmountLabel } from './finance.js';
import { loadProfilesMeta, lsKey } from './firebase-sync.js';
import { renderProfileUI } from './goals-profile.js';
import { getMessagingInstance, loadNotifSettings, populateNotifTimeSelects, pushEnabledKey, renderNotifUI, runNotificationChecks } from './notifications.js';
import { maybeAutoUpdateRates, populateFxConverterSelects, renderFxConverter, setupModalAccessibility, toggleHideAmounts } from './settings-managers.js';
import { renderShoppingList } from './shopping.js';
import { enhanceAllSelects, filterSettings, setupAccessibleSettingsRows, setupCollapsibleFinanceSections, showToast } from './ui-widgets.js';

export async function init(){
  const now=new Date();
  if(!AppState.initialized){
    AppState.initialized=true;
    // Month select
    const ms=document.getElementById('select-month');
    AppState.MONTHS.forEach((m,i)=>{
      const o=document.createElement('option');
      o.value=i; o.textContent=m;
      if(i===now.getMonth())o.selected=true;
      ms.appendChild(o);
    });
    // Year select
    const ys=document.getElementById('select-year');
    for(let y=now.getFullYear()-2;y<=now.getFullYear()+1;y++){
      const o=document.createElement('option');
      o.value=y; o.textContent=y;
      if(y===now.getFullYear())o.selected=true;
      ys.appendChild(o);
    }
    // Refresh the subcategory list whenever the user picks a different category
    document.getElementById('fin-category')?.addEventListener('change', fillSubcats);
    // Keep the amount field's currency label matched to the chosen wallet
    document.getElementById('fin-wallet')?.addEventListener('change', updateAmountLabel);
    // Auto-categorize as the user types the comment, per their rules
    document.getElementById('fin-comment')?.addEventListener('input', applyAutoRuleToForm);
    setupAccessibleSettingsRows();
    setupCollapsibleFinanceSections();
    setupModalAccessibility();
    setupPullToRefresh();
    setupFabExpandCollapse();
    loadNotifSettings();
    populateNotifTimeSelects();
    renderNotifUI();
    document.addEventListener('visibilitychange', ()=>{ if(document.visibilityState==='visible'){ runNotificationChecks(); runAutoFillCheck(); } });
    setInterval(()=>{ runNotificationChecks(); runAutoFillCheck(); }, 5*60*1000);
  }
  // Local cache first (namespaced to the signed-in user)
  try{const k=lsKey('shifts'); const s=k&&localStorage.getItem(k); if(s) AppState.shifts=JSON.parse(s);}catch{}
  try{const k=lsKey('tx'); const t=k&&localStorage.getItem(k); if(t) AppState.transactions=JSON.parse(t);}catch{}
  try{const k=lsKey('recurring'); const r=k&&localStorage.getItem(k); if(r) AppState.recurring=JSON.parse(r);}catch{}
  try{const k=lsKey('shopping'); const s2=k&&localStorage.getItem(k); if(s2) AppState.shoppingList=JSON.parse(s2);}catch{}
  try{const k=lsKey('debt'); const d=k&&localStorage.getItem(k); if(d){const norm=normalizeDebtData(JSON.parse(d)); if(norm){AppState.debts=norm.debts; AppState.currentDebtId=norm.currentDebtId;}}}catch{}
  // Config cache (shift types / wallets / categories); seed sane defaults
  // if none cached yet so the first render before cloud load doesn't break.
  let cfgCached=false;
  try{const k=lsKey('cfg'); const c=k&&localStorage.getItem(k); if(c){const o=JSON.parse(c);
    if(o&&o.shiftTypes&&o.wallets&&o.categories){AppState.shiftTypes=o.shiftTypes; AppState.autoFillSchedule=(o.autoFillSchedule&&typeof o.autoFillSchedule==='object')?{enabled:!!o.autoFillSchedule.enabled, typeId:o.autoFillSchedule.typeId||'', pattern:o.autoFillSchedule.pattern||'every', anchorDate:o.autoFillSchedule.anchorDate||''}:{enabled:false,typeId:'',pattern:'every',anchorDate:''}; AppState.wallets=o.wallets; AppState.categories=o.categories; AppState.budgets=o.budgets||{}; AppState.subcategories=o.subcategories||{}; AppState.categoryIcons=o.categoryIcons||{}; AppState.currencyRates=o.currencyRates||{}; AppState.tags=Array.isArray(o.tags)?o.tags:[]; AppState.autoRules=Array.isArray(o.autoRules)?o.autoRules:[]; AppState.goals=Array.isArray(o.goals)?o.goals:[]; AppState.profile=(o.profile&&typeof o.profile==='object')?o.profile:{nickname:'',avatar:''}; AppState.subscription=(o.subscription&&typeof o.subscription==='object')?{plan:o.subscription.plan||'free',expiresAt:o.subscription.expiresAt||null}:{plan:'free',expiresAt:null}; AppState.widgets=(o.widgets&&typeof o.widgets==='object')?{rates:o.widgets.rates!==false,converter:o.widgets.converter!==false,analytics:o.widgets.analytics!==false,chart:o.widgets.chart!==false,goals:o.widgets.goals!==false}:{rates:true,converter:true,analytics:true,chart:true,goals:true}; AppState.widgetOrder=sanitizeWidgetOrder(o.widgetOrder); normalizeWallets(); AppState.catBackfillDone=!!o.catBackfillDone; AppState.catLegacyMerged=!!o.catLegacyMerged; cfgCached=true;}}}catch{}
  if(!cfgCached) seedConfigFromDocs(null,null);
  // Date input
  const di=document.getElementById('fin-date');
  if(di) di.value=now.toISOString().split('T')[0];
  switchTab('finance');
  // Cold start (no local config cache — see the localStorage reads above):
  // switchTab('finance') just rendered a momentarily-empty Finance tab from
  // whatever's currently in AppState (seeded defaults), which is about to
  // get overwritten by real data once fbLoadNow() resolves below. Swap in
  // shimmer placeholders instead of showing that empty flash — no explicit
  // cleanup needed, fbLoadNow() always re-renders over this unconditionally.
  // renderShiftsSkeleton() covers the same window for the Shifts tab, in
  // case the user taps that nav tab before fbLoadNow() resolves — Shifts
  // itself isn't the tab switchTab() just activated, but its skeleton still
  // needs to be in place *before* that could happen.
  if(!cfgCached){ renderFinanceSkeleton(); renderShiftsSkeleton(); }
  setFinanceType('income');
  populateFxConverterSelects(); renderFxConverter();
  enhanceAllSelects();
  renderProfileUI(); renderPremiumUI();
  try{ await loadProfilesMeta(); }catch(e){ console.error('profiles meta load failed', e); }
  renderProfilesUI();
  // Load from cloud (auto — no manual save/load step needed)
  await fbLoadNow();
  renderProfileUI(); renderPremiumUI(); applyWidgetVisibility(); renderNotifUI();
  runNotificationChecks();
  maybeAutoUpdateRates();
  // Re-attach the foreground push handler if this device already has push
  // enabled from a previous session (registering the token itself only
  // happens once, in enablePushNotifications()).
  if(localStorage.getItem(pushEnabledKey())==='1') getMessagingInstance().catch(e=>console.warn('push init failed',e));
}

// Called once from init()'s cold-init block, same as setupModalAccessibility()
// above. Pull-to-refresh: dragging down from the very top of the page (not
// mid-scroll anywhere else, and not while a modal is open) reveals a
// spinner and, past a threshold, calls the exact same fbLoadNow()+toast
// flow as the topbar's #btn-refresh tap button (js/app-init.js's
// __init_app_init__ below) — this is a second entry point to that same
// refresh, not a separate mechanism. Deliberately uses `{passive:true}`
// listeners with no preventDefault(): body's `overscroll-behavior-y:contain`
// (index.html) already suppresses the browser/OS's own native pull-to-
// refresh bounce at the CSS level, which is what actually lets this coexist
// with normal scrolling without the touchmove-preventDefault jank cost.
function setupPullToRefresh(){
  const indicator=document.getElementById('ptr-indicator');
  const spinner=document.getElementById('ptr-spinner');
  if(!indicator||!spinner) return;
  const THRESHOLD=70, MAX_PULL=100;
  let startY=null, lastPull=0, refreshing=false;

  document.addEventListener('touchstart', e=>{
    if(refreshing || AppState.openModalStack.length || (document.scrollingElement||document.documentElement).scrollTop>0){ startY=null; return; }
    startY=e.touches[0].clientY;
    lastPull=0;
    indicator.classList.remove('ptr-settling');
  }, {passive:true});

  document.addEventListener('touchmove', e=>{
    if(startY==null || refreshing) return;
    const dy=e.touches[0].clientY-startY;
    if(dy<=0){ lastPull=0; indicator.style.transform='translateY(-60px)'; return; }
    // Damped (×0.5), not 1:1 with the finger — the standard pull-to-refresh
    // "heavier the further you pull" feel, capped so the indicator can't
    // travel past MAX_PULL regardless of how far the finger keeps moving.
    lastPull=Math.min(MAX_PULL, dy*0.5);
    indicator.style.transform=`translateY(${lastPull-60}px)`;
    spinner.style.transform=`rotate(${lastPull/MAX_PULL*360}deg)`;
  }, {passive:true});

  document.addEventListener('touchend', async ()=>{
    if(startY==null) return;
    startY=null;
    if(lastPull<1) return;
    indicator.classList.add('ptr-settling');
    if(lastPull>=THRESHOLD){
      refreshing=true;
      indicator.classList.add('ptr-loading');
      indicator.style.transform='translateY(4px)';
      try{ await fbLoadNow(); showToast(tr('sync_synced'),'check'); }
      finally{
        refreshing=false;
        indicator.classList.remove('ptr-loading');
        indicator.style.transform='translateY(-60px)';
        spinner.style.transform='';
      }
    }else{
      indicator.style.transform='translateY(-60px)';
      spinner.style.transform='';
    }
    lastPull=0;
  }, {passive:true});
}

// Called once from init()'s cold-init block, same as setupPullToRefresh()
// above. Extended-FAB behavior: the "Нова операція"/"Новий платіж" floating
// buttons (.fin-fab, index.html) show an icon+label pill at rest and
// collapse to a plain icon-only circle while the page is being actively
// scrolled (CSS handles the actual pill↔circle morph via .fab-collapsed —
// see the comment on .fin-fab in index.html), re-expanding a short beat
// after scrolling stops. One listener drives every .fin-fab on the page
// (there are two — Finance and Debt tabs — but only one is ever visible at
// a time since switchTab() hides the other's whole tab section).
// Listens on `document` with useCapture:true, not a plain `window` 'scroll'
// listener — 'scroll' events never bubble (not even from document up to
// window), and on a real account with more than a handful of rows, the
// actual scrolling happens *inside* `#tx-list-container`/`.debt-list`
// (index.html, both a fixed max-height with their own `overflow-y:auto`,
// not the page itself), not on window/document. A bubble-phase or
// window-only listener silently never sees those scrolls, so the FAB never
// collapses — the capture phase still traverses top-down through every
// ancestor regardless of bubbling, so this is the only way one listener
// can catch scrolling in any current or future nested scroll container.
function setupFabExpandCollapse(){
  const fabs=document.querySelectorAll('.fin-fab');
  if(!fabs.length) return;
  let collapseTimer=null;
  document.addEventListener('scroll', ()=>{
    fabs.forEach(f=>f.classList.add('fab-collapsed'));
    clearTimeout(collapseTimer);
    collapseTimer=setTimeout(()=>{ fabs.forEach(f=>f.classList.remove('fab-collapsed')); }, 600);
  }, {passive:true, capture:true});
}

export function switchTab(tab){
  const tappedIcon=document.querySelector(`#nav-${tab} .tab-icon-wrap`);
  if(tappedIcon){
    tappedIcon.classList.remove('tab-pop');
    void tappedIcon.offsetWidth;
    tappedIcon.classList.add('tab-pop');
  }
  document.getElementById('nav-shifts').classList.toggle('active',tab==='shifts');
  document.getElementById('nav-finance').classList.toggle('active',tab==='finance');
  document.getElementById('nav-debt').classList.toggle('active',tab==='debt');
  document.getElementById('nav-shopping').classList.toggle('active',tab==='shopping');
  document.getElementById('btn-settings')?.classList.toggle('active',tab==='settings');
  document.getElementById('tab-shifts').style.display  = tab==='shifts'  ? 'block':'none';
  document.getElementById('tab-finance').style.display = tab==='finance' ? 'block':'none';
  document.getElementById('tab-debt').style.display    = tab==='debt'    ? 'block':'none';
  document.getElementById('tab-shopping').style.display= tab==='shopping'? 'block':'none';
  document.getElementById('tab-settings').style.display= tab==='settings'? 'block':'none';
  const shownTab=document.getElementById(`tab-${tab}`);
  if(shownTab){ shownTab.classList.remove('tab-in'); void shownTab.offsetWidth; shownTab.classList.add('tab-in'); }
  if(tab==='shifts')  {renderCalendar(); renderIncomeChart();}
  if(tab==='finance') {setupCollapsibleFinanceSections(); applyWidgetVisibility(); renderFinance(); renderFinanceChart();}
  if(tab==='debt') {renderDebt();}
  if(tab==='shopping') {renderShoppingList();}
  if(tab==='settings') {filterSettings(document.getElementById('settings-search-input')?.value||''); maybeShowSettingsTip();}
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_app_init__(){
document.addEventListener('click', (e)=>{
  const el=e.target.closest('.btn-primary, .fin-fab, .icon-badge');
  if(!el) return;
  el.classList.remove('ui-pop');
  void el.offsetWidth;
  el.classList.add('ui-pop');
});

// Topbar + bottom-nav wiring — these used to be inline onclick="" HTML
// attributes (which need window.foo globals to resolve, see CLAUDE.md's
// "js/ module layout" point 3); real addEventListener wiring here means
// switchTab/toggleHideAmounts/fbLoadNow only need to be real module
// exports, not also attached to window.
document.getElementById('topbar-avatar')?.addEventListener('click', ()=>switchTab('settings'));
document.getElementById('btn-settings')?.addEventListener('click', ()=>switchTab('settings'));
document.getElementById('btn-hide-amounts')?.addEventListener('click', ()=>toggleHideAmounts());
document.getElementById('btn-refresh')?.addEventListener('click', async (e)=>{
  const btn=e.currentTarget;
  if(btn.classList.contains('spinning')) return;
  btn.classList.add('spinning');
  try{ await fbLoadNow(); showToast(tr('sync_synced'),'check'); }
  finally{ btn.classList.remove('spinning'); }
});
document.getElementById('nav-finance')?.addEventListener('click', ()=>switchTab('finance'));
document.getElementById('nav-shifts')?.addEventListener('click', ()=>switchTab('shifts'));
document.getElementById('nav-debt')?.addEventListener('click', ()=>switchTab('debt'));
document.getElementById('nav-shopping')?.addEventListener('click', ()=>switchTab('shopping'));
}
