// @ts-check
// ── CALENDAR ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { saveConfigLocal, saveLocal, scheduleSave } from './color-picker.js';
import { SALARY_GOAL, canEditActiveProfile, shiftType, toBase } from './core.js';
import { csSync, emptyStateHtml, escapeHtml, hexA, initSheetDrag, showToast, uiConfirm } from './ui-widgets.js';

// Cold-start only: called once from js/app-init.js's init() when there was
// no local config cache to paint from instantly — same pattern and same
// call site as renderFinanceSkeleton() in js/analytics-csv.js. Without
// this, a user who taps the Shifts nav tab before the first fbLoadNow()
// round-trip resolves would see the "you haven't logged any shifts yet"
// empty state (AppState.shifts is still {} at that point, see
// renderCalendar()'s #calendar-empty-state block below), which incorrectly
// reads as "you have no data" rather than "still loading". renderCalendar()
// unconditionally overwrites both the grid and the empty-state visibility
// once real data arrives — no separate cleanup call needed.
/** @returns {void} */
export function renderShiftsSkeleton(){
  const grid=document.getElementById('calendar-grid');
  if(grid) grid.innerHTML=Array.from({length:35}).map(()=>'<div class="skeleton-block" style="height:64px"></div>').join('');
  const empty=document.getElementById('calendar-empty-state');
  if(empty){ empty.style.display='none'; empty.innerHTML=''; }
}

/** @param {number} d */
export function shiftMonth(d){
  const ms=/** @type {HTMLSelectElement} */ (document.getElementById('select-month'));
  const ys=/** @type {HTMLSelectElement} */ (document.getElementById('select-year'));
  let m=parseInt(ms.value)+d, y=parseInt(ys.value);
  if(m<0){m=11;y--;}
  if(m>11){m=0;y++;}
  ms.value=String(m); ys.value=String(y);
  csSync(ms); csSync(ys);
  renderCalendar(); renderIncomeChart();
}

/** @returns {void} */
export function goToday(){
  const now=new Date();
  const ms=/** @type {HTMLSelectElement} */ (document.getElementById('select-month')), ys=/** @type {HTMLSelectElement} */ (document.getElementById('select-year'));
  ms.value=String(now.getMonth()); ys.value=String(now.getFullYear());
  csSync(ms); csSync(ys);
  renderCalendar();
}

/** @param {string[]} selectedIds */
function renderShiftModalOptions(selectedIds){
  const box=document.getElementById('modal-opts');
  if(!box) return;
  box.innerHTML='';
  if(!AppState.shiftTypes.length){
    box.innerHTML=`<div class="chk-desc" style="text-align:center;padding:8px">Немає типів змін. Додай їх кнопкою «Типи змін».</div>`;
    return;
  }
  AppState.shiftTypes.forEach(t=>{
    const checked=selectedIds.includes(t.id)?'checked':'';
    const desc=t.isOff?tr('shifts_rest'):`${t.amount?t.amount.toLocaleString('uk-UA')+' грн':'—'}${t.hours?' · '+t.hours+' '+tr('shifts_hours_short'):''}`;
    const label=document.createElement('label');
    label.className='chk-row';
    label.style.setProperty('--row-color', t.color||'#8b5cf6');
    label.innerHTML=`
      <input type="checkbox" data-stid="${escapeHtml(t.id)}" ${checked}>
      <div class="chk-label"><div class="chk-name">${escapeHtml(t.name)}</div><div class="chk-desc">${escapeHtml(desc)}</div></div>`;
    box.appendChild(label);
  });
}

/**
 * @param {string} dateKey
 * @param {number} day
 */
export function openModal(dateKey, day){
  AppState.selectedDateKey=dateKey;
  const mi=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-month')).value);
  /** @type {HTMLElement} */ (document.getElementById('modal-date-title')).textContent=`${day} ${AppState.MONTHS[mi]}`;
  renderShiftModalOptions(AppState.shifts[dateKey]||[]);
  /** @type {HTMLElement} */ (document.getElementById('shift-modal')).style.display='flex';
}

/** @returns {void} */
export function closeModal(){
  /** @type {HTMLElement} */ (document.getElementById('shift-modal')).style.display='none';
  AppState.selectedDateKey=null;
}

/** @returns {void} */
export function validateModalSelection(){}

/** @returns {void} */
export function saveModalSelection(){
  if(!AppState.selectedDateKey) return;
  if(!canEditActiveProfile()){ showToast(tr('shared_profile_readonly'),'xmark'); closeModal(); return; }
  /** @type {string[]} */
  const al=[];
  document.querySelectorAll('#modal-opts input[type=checkbox]').forEach(el=>{
    if(/** @type {HTMLInputElement} */ (el).checked){ const v=el.getAttribute('data-stid'); if(v) al.push(v); }
  });
  if(al.length===0) delete AppState.shifts[AppState.selectedDateKey]; else AppState.shifts[AppState.selectedDateKey]=al;
  saveLocal(); scheduleSave(); closeModal(); renderCalendar(); renderIncomeChart();
}

// The compact 1-2 char glyph shown on a calendar day cell for a shift
// type. Prefers an explicit `code` (set on the built-ins, see
// LEGACY_SHIFT_TYPES/DEFAULT_SHIFT_TYPES in js/core.js). For a type with no
// `code` — a user-created type, or a built-in already saved to an existing
// account's config before `code` existed (pre-launch testing devices) — it
// derives one from `short`/`name`: the first letter, plus a distinguishing
// tail char when the label carries one, so the built-in `short` values
// still map cleanly without any data migration:
//   День→Д  День+→Д+  Ніч→Н  НічР→Нр  НічП→Нп  Вих→В
// A `+` suffix is kept as-is; otherwise an interior/trailing uppercase
// letter (the convention those legacy shorts use to distinguish variants)
// becomes a lowercased second char. `[...str]` (not str[0]) so a multi-byte
// first glyph isn't split mid-character.
/** @param {{code?: string, short?: string, name?: string}} t */
function shiftCode(t){
  if(t.code) return t.code;
  const src=(t.short||t.name||'').trim();
  if(!src) return '?';
  const chars=[...src];
  const first=chars[0].toUpperCase();
  if(src.includes('+')) return first+'+';
  const tail=chars.slice(1).find(ch=>/\p{L}/u.test(ch) && ch===ch.toUpperCase() && ch!==ch.toLowerCase());
  return tail ? first+tail.toLowerCase() : first;
}

/** @returns {void} */
export function renderCalendar(){
  const grid=document.getElementById('calendar-grid');
  if(!grid) return;
  renderTemplateShiftOptions();
  renderAutoFillUI();
  // Legend from current shift types
  const leg=document.getElementById('shift-legend');
  if(leg){
    leg.innerHTML=AppState.shiftTypes.map(t=>
      `<div class="leg-item"><div class="leg-dot" style="background:${hexA(t.color,.25)};border:1px solid ${hexA(t.color,.6)}"></div>${escapeHtml(t.name)}</div>`
    ).join('');
  }
  grid.innerHTML='';
  const m=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-month')).value);
  const y=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-year')).value);
  const now=new Date();
  const isCurrent=now.getMonth()===m&&now.getFullYear()===y;

  // Weekday headers
  AppState.WEEKDAYS.forEach((d,i)=>{
    const el=document.createElement('div');
    el.className='wday'+(i>=5?' weekend':'');
    el.textContent=d;
    grid.appendChild(el);
  });

  const firstDay=(new Date(y,m,1).getDay()+6)%7;
  const total=new Date(y,m+1,0).getDate();
  for(let i=0;i<firstDay;i++){const e=document.createElement('div');e.className='day-cell empty';grid.appendChild(e);}

  let earn=0,hrs=0,cShifts=0,cOff=0;

  for(let d=1;d<=total;d++){
    const dk=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
    const ds=AppState.shifts[dk]||[];
    const isToday=isCurrent&&now.getDate()===d;
    const dow=(new Date(y,m,d).getDay()+6)%7;
    const isWeekend=dow>=5;

    const cell=document.createElement('div');
    cell.className='day-cell'+(ds.length?' has-shifts':'')+(isToday?' today':'')+(isWeekend?' weekend-cell':'');
    // Faint background tint from the day's first shift type, so a month
    // reads as color patches at a glance instead of relying purely on the
    // small badge pill's text — same .07 alpha .day-cell.today already
    // uses for its own tint, kept subtle enough not to fight the badge.
    if(ds.length){
      const firstType=shiftType(ds[0]);
      if(firstType) cell.style.setProperty('--cell-tint',hexA(firstType.color,.07));
    }

    let badges='';
    ds.forEach(id=>{
      const t=shiftType(id);
      if(!t) return; // unknown/removed type — skip gracefully
      badges+=`<div class="shift-token" style="background:${hexA(t.color,.22)};border:1px solid ${hexA(t.color,.55)};color:${t.color}" aria-label="${escapeHtml(t.name)}">${escapeHtml(shiftCode(t))}</div>`;
      earn+=t.amount||0; hrs+=t.hours||0;
      if(t.isOff) cOff++; else cShifts++;
    });

    cell.innerHTML=`<div class="day-header"><span class="day-num${isWeekend?' weekend-num':''}">${d}</span>${isToday?'<span class="today-pip"></span>':''}</div>${badges?`<div class="day-tokens">${badges}</div>`:''}`;
    cell.tabIndex=0;
    cell.onclick=()=>openModal(dk,d);
    cell.onkeydown=e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); openModal(dk,d); } };
    grid.appendChild(cell);
  }

  // Update stats
  /** @param {string} id @param {string|number} v */
  const S=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=String(v);};
  S('total-salary',earn.toLocaleString('uk-UA')+' грн');
  S('total-hours',hrs);
  S('count-shifts',cShifts);
  S('count-off',cOff);
  const empty=document.getElementById('calendar-empty-state');
  if(empty){
    const hasAny=(cShifts+cOff)>0;
    empty.style.display=hasAny?'none':'block';
    empty.innerHTML=hasAny?'':emptyStateHtml({
      icon:'calendar',
      title:tr('shifts_empty_title'),
      desc:tr('shifts_empty_desc'),
      action:tr('shifts_quick_fill'),
      actionName:'toggle-quick-fill'
    });
  }
  // Progress bar
  const pct=Math.min(100,Math.round(earn/SALARY_GOAL*100));
  const bar=document.getElementById('salary-bar');
  const lbl=document.getElementById('salary-bar-label');
  if(bar) bar.style.width=pct+'%';
  if(lbl) lbl.textContent=`${pct}% ${tr('shifts_goal_progress')} ${SALARY_GOAL.toLocaleString('uk-UA')} грн`;
}

/** @returns {void} */
export function renderIncomeChart(){
  const container=document.getElementById('income-chart');
  if(!container) return;
  container.innerHTML='';
  const now=new Date();
  /** @type {Array<{m: number, y: number, label: string}>} */
  const months=[];
  for(let i=5;i>=0;i--){
    let m=now.getMonth()-i, y=now.getFullYear();
    if(m<0){m+=12;y--;}
    months.push({m,y,label:AppState.MONTHS_SHORT[m]});
  }
  const vals=months.map(({m,y})=>{
    let earn=0;
    const prefix=`${y}-${String(m+1).padStart(2,'0')}-`;
    Object.entries(AppState.shifts).forEach(([k,ds])=>{
      if(!k.startsWith(prefix)) return;
      ds.forEach(id=>{ const t=shiftType(id); if(t) earn+=t.amount||0; });
    });
    return earn;
  });
  const maxVal=Math.max(...vals,1);
  const curM=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-month')).value);
  const curY=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-year')).value);

  months.forEach(({m,y,label},i)=>{
    const isCur=m===curM&&y===curY;
    const pct=Math.round(vals[i]/maxVal*100);
    const wrap=document.createElement('div');
    wrap.className='chart-bar-wrap';
    const earn=vals[i];
    wrap.innerHTML=`
      <div class="chart-bar" style="height:${pct}%;background:${isCur?'var(--purple)':'rgba(139,92,246,.35)'}" data-tip="${earn.toLocaleString('uk-UA')} грн"></div>
      <div class="chart-bar-label" style="${isCur?'color:var(--purple2);font-weight:800':''}">${label}</div>`;
    container.appendChild(wrap);
  });
}

/** @param {string} series */
export function setFinChartSeries(series){
  AppState.financeChartSeries=series;
  document.querySelectorAll('.fin-chart-toggle-btn').forEach(b=>b.classList.toggle('active', /** @type {HTMLElement} */ (b).dataset.series===series));
  renderFinanceChart();
}

function hideFinChartTooltip(){
  const tip=document.getElementById('fin-chart-tooltip');
  if(tip) tip.style.display='none';
}

/** @param {HTMLElement | SVGElement} pointEl */
function showFinChartTooltip(pointEl){
  const tip=document.getElementById('fin-chart-tooltip');
  if(!tip) return;
  tip.textContent=pointEl.dataset.tip ?? null;
  tip.style.left=pointEl.dataset.xPct+'%';
  tip.style.top=pointEl.dataset.yPct+'%';
  tip.style.display='block';
}

// Catmull-Rom-derived cubic bezier smoothing — gives a natural curve through
// every point without needing an external charting library, consistent with
// this repo's no-build-step/no-dependency approach.
/** @param {Array<{x: number, y: number}>} pts */
function smoothPath(pts){
  if(pts.length<2) return '';
  let d=`M${pts[0].x},${pts[0].y}`;
  for(let i=0;i<pts.length-1;i++){
    const p0=pts[i-1]||pts[i], p1=pts[i], p2=pts[i+1], p3=pts[i+2]||p2;
    const c1x=p1.x+(p2.x-p0.x)/6, c1y=p1.y+(p2.y-p0.y)/6;
    const c2x=p2.x-(p3.x-p1.x)/6, c2y=p2.y-(p3.y-p1.y)/6;
    d+=` C${c1x},${c1y} ${c2x},${c2y} ${p2.x},${p2.y}`;
  }
  return d;
}

/** @returns {void} */
export function renderFinanceChart(){
  const svg=document.getElementById('fin-chart-svg');
  if(!svg) return;
  const series=AppState.financeChartSeries||'net';
  document.querySelectorAll('.fin-chart-toggle-btn').forEach(b=>b.classList.toggle('active', /** @type {HTMLElement} */ (b).dataset.series===series));

  const now=new Date();
  /** @type {Array<{m: number, y: number, label: string}>} */
  const months=[];
  for(let i=5;i>=0;i--){
    let m=now.getMonth()-i, y=now.getFullYear();
    if(m<0){m+=12;y--;}
    months.push({m,y,label:AppState.MONTHS_SHORT[m]});
  }
  const raw=months.map(({m,y})=>{
    const prefix=`${y}-${String(m+1).padStart(2,'0')}`;
    let inc=0,exp=0;
    AppState.transactions.forEach(t=>{
      if(!t.date||!t.date.startsWith(prefix)) return;
      if(t.type==='income') inc+=toBase(t.amount,t.currency||'UAH');
      else if(t.type==='expense') exp+=toBase(t.amount,t.currency||'UAH');
    });
    return {inc,exp,net:inc-exp};
  });
  const vals=raw.map(v=>series==='income'?v.inc:series==='expense'?v.exp:v.net);

  // Simple, offline trend forecast (no AI/LLM call): average of the last up
  // to 3 month-over-month deltas, projected one month past the real data.
  const deltas=[];
  for(let i=Math.max(1,vals.length-3);i<vals.length;i++) deltas.push(vals[i]-vals[i-1]);
  const avgDelta=deltas.length?deltas.reduce((a,b)=>a+b,0)/deltas.length:0;
  const forecastVal=vals[vals.length-1]+avgDelta;

  /** @param {number} v */
  const fmt=v=>Math.round(v).toLocaleString('uk-UA')+' грн';
  const totalEl=document.getElementById('fin-chart-total');
  if(totalEl) totalEl.textContent=fmt(vals[vals.length-1]);

  const trendEl=document.getElementById('fin-chart-trend');
  if(trendEl){
    const prev=vals[vals.length-2];
    if(prev){
      const pct=Math.round(((vals[vals.length-1]-prev)/Math.abs(prev))*100);
      trendEl.className='fin-chart-trend '+(pct>=0?'up':'down');
      trendEl.textContent=(pct>=0?'↑ ':'↓ ')+Math.abs(pct)+'%';
    } else {
      trendEl.className='fin-chart-trend';
      trendEl.textContent='';
    }
  }

  const allVals=[...vals,forecastVal];
  const minV=Math.min(0,...allVals), maxV=Math.max(0,...allVals);
  const range=(maxV-minV)||1;
  const W=320,H=150,padTop=14,padBottom=14,plotH=H-padTop-padBottom;
  const n=allVals.length;
  const stepX=W/(n-1);
  const points=allVals.map((v,i)=>({
    x:i*stepX,
    y:padTop+plotH-((v-minV)/range)*plotH,
    v,
  }));
  const realPts=points.slice(0,n-1);
  const forecastPts=points.slice(n-2);
  const realPath=smoothPath(realPts);
  const forecastPath=smoothPath(forecastPts);
  const areaPath=`${realPath} L${realPts[realPts.length-1].x},${H-padBottom} L${realPts[0].x},${H-padBottom} Z`;

  const circles=points.map((p,i)=>{
    const isForecast=i===n-1;
    const label=isForecast?tr('finance_chart_forecast_tip'):months[i].label;
    const tip=`${label}: ${isForecast?'≈ ':''}${fmt(p.v)}`;
    // The invisible hit-circle is drawn AFTER (SVG paints later elements on
    // top) the small visible dot, not before — otherwise the visible dot
    // itself intercepts pointer events with no handler attached, and only
    // taps landing in the ring around it (never the dot itself) would work.
    return `<circle class="fin-chart-point" cx="${p.x}" cy="${p.y}" r="${isForecast?3.5:4}" fill="${isForecast?'var(--bg1)':'var(--purple2)'}" stroke="var(--purple2)" stroke-width="2"></circle>
      <circle class="fin-chart-point-hit" cx="${p.x}" cy="${p.y}" r="10" data-tip="${escapeHtml(tip)}" data-x-pct="${(p.x/W*100).toFixed(2)}" data-y-pct="${(p.y/H*100).toFixed(2)}"></circle>`;
  }).join('');

  svg.innerHTML=`
    <defs>
      <linearGradient id="fin-chart-grad" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stop-color="${hexA('#8b5cf6',.35)}"/>
        <stop offset="100%" stop-color="${hexA('#8b5cf6',0)}"/>
      </linearGradient>
    </defs>
    <path d="${areaPath}" fill="url(#fin-chart-grad)" stroke="none"></path>
    <path d="${realPath}" fill="none" stroke="var(--purple2)" stroke-width="2.5" stroke-linecap="round"></path>
    <path d="${forecastPath}" fill="none" stroke="var(--purple2)" stroke-width="2.5" stroke-linecap="round" stroke-dasharray="5,5" opacity=".7"></path>
    ${circles}`;
  svg.querySelectorAll('.fin-chart-point-hit').forEach(c=>{
    /** @type {SVGElement} */ (c).onclick=(e)=>{ e.stopPropagation(); showFinChartTooltip(/** @type {SVGElement} */ (c)); };
  });

  const labelsEl=document.getElementById('fin-chart-labels');
  if(labelsEl) labelsEl.innerHTML=months.map(m=>`<span>${m.label}</span>`).join('')+`<span class="forecast">${tr('finance_chart_forecast')}</span>`;

  const metricsEl=document.getElementById('fin-chart-metrics');
  if(metricsEl){
    const avg=vals.reduce((a,b)=>a+b,0)/vals.length;
    let bestI=0,worstI=0;
    vals.forEach((v,i)=>{ if(v>vals[bestI])bestI=i; if(v<vals[worstI])worstI=i; });
    metricsEl.innerHTML=`
      <span class="chip-stat"><span class="chip-stat-icon">${window.Icon('refresh')}</span><span class="chip-stat-val">${fmt(avg)}</span><span class="chip-stat-lbl">${tr('finance_chart_avg')}</span></span>
      <span class="chip-stat"><span class="chip-stat-icon" style="background:linear-gradient(135deg,var(--green),var(--green2))">${window.Icon('swap')}</span><span class="chip-stat-val">${fmt(vals[bestI])}</span><span class="chip-stat-lbl">${tr('finance_chart_best')} · ${months[bestI].label}</span></span>
      <span class="chip-stat"><span class="chip-stat-icon" style="background:linear-gradient(135deg,var(--red),var(--red2))">${window.Icon('swap')}</span><span class="chip-stat-val">${fmt(vals[worstI])}</span><span class="chip-stat-lbl">${tr('finance_chart_worst')} · ${months[worstI].label}</span></span>`;
  }
}

/** @returns {Promise<void>} */
export async function clearCurrentMonth(){
  if(!(await uiConfirm(tr('shifts_clear_confirm'),{title:tr('shifts_clear_month'),okText:tr('shifts_clear_ok'),danger:true}))) return;
  const m=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-month')).value);
  const y=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-year')).value);
  const p=`${y}-${String(m+1).padStart(2,'0')}-`;
  Object.keys(AppState.shifts).forEach(k=>{if(k.startsWith(p))delete AppState.shifts[k];});
  saveLocal(); scheduleSave(); renderCalendar(); renderIncomeChart();
  showToast(tr('shifts_month_cleared'),'trash');
}

function renderTemplateShiftOptions(){
  const sel=/** @type {HTMLSelectElement | null} */ (document.getElementById('template-shift'));
  if(!sel) return;
  const prev=sel.value;
  sel.innerHTML='';
  AppState.shiftTypes.filter(t=>!t.isOff).forEach(t=>{
    const o=document.createElement('option');
    o.value=t.id; o.textContent=t.name;
    sel.appendChild(o);
  });
  if(prev&&AppState.shiftTypes.some(t=>t.id===prev)) sel.value=prev;
}

const toggleQuickFill = function(){
  const body=document.getElementById('tools-panel-body');
  const chev=document.getElementById('tools-toggle-chevron');
  if(!body) return;
  const opening = body.style.display==='none';
  body.style.display = opening ? 'flex' : 'none';
  if(chev) chev.style.transform = opening ? 'rotate(180deg)' : '';
};

/** @type {Record<string, number[]>} */
const SHIFT_PATTERN_CYCLES={every:[1,0], alt:[1,1], '2_2':[2,2], '3_3':[3,3]};

/** @returns {Promise<void>} */
export async function applyTemplate(){
  const typeId=/** @type {HTMLSelectElement} */ (document.getElementById('template-shift')).value;
  const pattern=/** @type {HTMLSelectElement} */ (document.getElementById('template-pattern')).value;
  if(!typeId){showToast(tr('shifts_add_type_first'),'xmark');return;}
  const m=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-month')).value);
  const y=parseInt(/** @type {HTMLSelectElement} */ (document.getElementById('select-year')).value);
  const total=new Date(y,m+1,0).getDate();
  if(!(await uiConfirm(tr('shifts_template_confirm'),{title:tr('shifts_quick_fill'),okText:tr('shifts_template_ok')}))) return;
  const p=`${y}-${String(m+1).padStart(2,'0')}-`;
  Object.keys(AppState.shifts).forEach(k=>{if(k.startsWith(p))delete AppState.shifts[k];});
  /** @param {number} d */
  const dk=d=>`${p}${String(d).padStart(2,'0')}`;
  const [on,off]=SHIFT_PATTERN_CYCLES[pattern]||SHIFT_PATTERN_CYCLES.every;
  const period=on+off;
  for(let d=1;d<=total;d++){
    if(((d-1)%period)<on) AppState.shifts[dk(d)]=[typeId];
  }
  saveLocal(); scheduleSave(); renderCalendar(); renderIncomeChart();
  showToast(tr('shifts_template_applied'),'bolt');
}

function todayDateKey(){
  const t=new Date();
  return `${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-${String(t.getDate()).padStart(2,'0')}`;
}

/** @param {string} dateKey */
function autoFillTypeForDate(dateKey){
  const s=AppState.autoFillSchedule;
  if(!s||!s.enabled||!s.typeId||!s.anchorDate||!shiftType(s.typeId)) return null;
  const [on,off]=SHIFT_PATTERN_CYCLES[s.pattern]||SHIFT_PATTERN_CYCLES.every;
  const period=on+off;
  if(period<=0) return null;
  const anchor=new Date(s.anchorDate+'T00:00:00');
  const target=new Date(dateKey+'T00:00:00');
  const diffDays=Math.round((target.getTime()-anchor.getTime())/86400000);
  if(diffDays<0) return null;
  return (diffDays%period)<on ? s.typeId : null;
}

/** @returns {number} */
export function processAutoFillShifts(){
  if(!AppState.autoFillSchedule||!AppState.autoFillSchedule.enabled||!AppState.autoFillSchedule.anchorDate) return 0;
  const today=new Date(); today.setHours(0,0,0,0);
  const earliest=new Date(today); earliest.setDate(earliest.getDate()-60);
  let cursor=new Date(AppState.autoFillSchedule.anchorDate+'T00:00:00');
  if(cursor<earliest) cursor=earliest;
  let added=0, guard=0;
  while(cursor<=today && guard<60){
    const key=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}-${String(cursor.getDate()).padStart(2,'0')}`;
    if(!AppState.shifts[key]){
      const typeId=autoFillTypeForDate(key);
      if(typeId){ AppState.shifts[key]=[typeId]; added++; }
    }
    cursor.setDate(cursor.getDate()+1);
    guard++;
  }
  if(added) saveLocal();
  return added;
}

/** @returns {void} */
export function runAutoFillCheck(){
  const added=processAutoFillShifts();
  if(added){ scheduleSave(); renderCalendar(); renderIncomeChart(); }
}

function renderAutoFillUI(){
  const cb=/** @type {HTMLInputElement | null} */ (document.getElementById('autofill-toggle-checkbox'));
  if(!cb) return;
  cb.checked=!!AppState.autoFillSchedule.enabled;
  const cfgBox=document.getElementById('autofill-config');
  if(cfgBox) /** @type {HTMLElement} */ (cfgBox).style.display=cb.checked?'flex':'none';
  const sel=/** @type {HTMLSelectElement | null} */ (document.getElementById('autofill-shift'));
  if(sel){
    const prev=AppState.autoFillSchedule.typeId||sel.value;
    sel.innerHTML='';
    AppState.shiftTypes.filter(t=>!t.isOff).forEach(t=>{
      const o=document.createElement('option'); o.value=t.id; o.textContent=t.name;
      sel.appendChild(o);
    });
    if(prev&&AppState.shiftTypes.some(t=>t.id===prev)) sel.value=prev;
  }
  const pat=/** @type {HTMLSelectElement | null} */ (document.getElementById('autofill-pattern'));
  if(pat){ pat.value=AppState.autoFillSchedule.pattern||'every'; csSync(pat); }
  const anchor=/** @type {HTMLInputElement | null} */ (document.getElementById('autofill-anchor'));
  if(anchor && document.activeElement!==anchor){ anchor.value=AppState.autoFillSchedule.anchorDate||''; csSync(anchor); }
}

/** @param {boolean} checked */
const toggleAutoFill = function(checked){
  AppState.autoFillSchedule.enabled=checked;
  if(checked){
    if(!AppState.autoFillSchedule.typeId){
      const first=AppState.shiftTypes.find(t=>!t.isOff);
      AppState.autoFillSchedule.typeId=first?first.id:'';
    }
    if(!AppState.autoFillSchedule.anchorDate) AppState.autoFillSchedule.anchorDate=todayDateKey();
  }
  saveConfigLocal(); scheduleSave();
  renderAutoFillUI();
  if(checked){
    const added=processAutoFillShifts();
    if(added){ renderCalendar(); renderIncomeChart(); }
    showToast(tr('shifts_autofill_on'),'bolt');
  }else{
    showToast(tr('shifts_autofill_off'),'check');
  }
};

const saveAutoFillConfig = function(){
  const sel=/** @type {HTMLSelectElement | null} */ (document.getElementById('autofill-shift'));
  const pat=/** @type {HTMLSelectElement | null} */ (document.getElementById('autofill-pattern'));
  const anchor=/** @type {HTMLInputElement | null} */ (document.getElementById('autofill-anchor'));
  if(!sel||!sel.value){ showToast(tr('shifts_add_type_first'),'xmark'); return; }
  AppState.autoFillSchedule.typeId=sel.value;
  AppState.autoFillSchedule.pattern=pat?pat.value:'every';
  if(anchor&&anchor.value) AppState.autoFillSchedule.anchorDate=anchor.value;
  saveConfigLocal(); scheduleSave();
  const added=processAutoFillShifts();
  if(added){ renderCalendar(); renderIncomeChart(); }
  showToast(tr('shifts_autofill_saved'),'check');
};

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
/** @returns {void} */
export function __init_calendar__(){
// Phase 9 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// this file has no dynamic per-row templates of its own (day cells wire
// openModal via a real cell.onclick=()=>... closure, not a literal onclick
// string) - all these window.* exports existed only for static onclick/
// onchange attributes in index.html. Converted to data-action, same
// pattern as phases 3-8. Also folds in 9 window.* assignments for this
// file's own functions that were sitting in js/color-picker.js's
// __init_color_picker__ (a leftover of the original mechanical split,
// same situation phase 8 found for debt.js's functions) - moved here and
// converted, except openModal/validateModalSelection which turned out to
// have **zero** callers of any kind (openModal is only ever invoked via
// the real cell.onclick closure above; validateModalSelection is an empty
// stub never called anywhere) and were dropped from window.* entirely
// rather than given a pointless data-action.
/** @type {Record<string, (ds: DOMStringMap) => void>} */
const CLICK_ACTIONS = {
  'close-modal': ()=>closeModal(),
  'save-modal-selection': ()=>saveModalSelection(),
  'apply-template': ()=>applyTemplate(),
  'clear-current-month': ()=>clearCurrentMonth(),
  'shift-month': ds=>shiftMonth(Number(ds.dir)),
  'go-today': ()=>goToday(),
  'toggle-quick-fill': ()=>toggleQuickFill(),
  'save-autofill-config': ()=>saveAutoFillConfig(),
  'set-fin-chart-series': ds=>setFinChartSeries(ds.series||'net'),
};
document.addEventListener('click', e=>{
  // #shift-modal's backdrop close is a plain exact-target check (same
  // idea as closeManagers()'s `e.target.classList.contains('modal-overlay')`
  // in settings-managers.js), not a data-action on the overlay itself: a
  // data-action="close-modal" on the overlay div previously matched via
  // closest() for ANY click inside the modal that didn't have its own
  // data-action (e.g. a shift-type checkbox), closing the modal the
  // instant you tried to pick a shift. Real bug, found by a user report
  // ("shifts aren't selectable") plus a Playwright repro.
  if(/** @type {Element} */ (e.target).id==='shift-modal'){ closeModal(); return; }
  if(!/** @type {Element} */ (e.target).closest('#fin-chart-wrap')) hideFinChartTooltip();
  const el=/** @type {HTMLElement | null} */ (/** @type {Element} */ (e.target).closest('[data-action]'));
  const action=el&&el.dataset.action;
  if(action && CLICK_ACTIONS[action]) CLICK_ACTIONS[action](el.dataset);
}, true);

/** @type {Record<string, (ds: DOMStringMap, el: HTMLInputElement) => void>} */
const FIELD_ACTIONS = {
  'render-calendar': ()=>renderCalendar(),
  'toggle-auto-fill': (ds,el)=>toggleAutoFill(el.checked),
};
document.addEventListener('change', e=>{
  const el=/** @type {HTMLInputElement | null} */ (/** @type {Element} */ (e.target).closest('[data-action]'));
  const action=el&&el.dataset.action;
  if(action && FIELD_ACTIONS[action]) FIELD_ACTIONS[action](el.dataset, el);
});

// Empty-state quick-fill uses data-action now (CSP-safe), so no window.*
// export is needed for toggleQuickFill.

// #shift-modal isn't in closeManagers()'s id list (it has its own
// closeModal() above, see the exact-target-check comment near the click
// listener) so it needs its own initSheetDrag() call rather than the
// blanket one settings-managers.js does for every other .modal-card.
const shiftModalCard=/** @type {HTMLElement | null} */ (document.querySelector('#shift-modal .modal-card'));
if(shiftModalCard) initSheetDrag(shiftModalCard, closeModal);
}
