// ── CALENDAR ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { saveConfigLocal, saveLocal, scheduleSave } from './color-picker.js';
import { SALARY_GOAL, shiftType, toBase } from './core.js';
import { csSync, emptyStateHtml, escapeHtml, hexA, showToast, uiConfirm } from './ui-widgets.js';

export function shiftMonth(d){
  const ms=document.getElementById('select-month');
  const ys=document.getElementById('select-year');
  let m=parseInt(ms.value)+d, y=parseInt(ys.value);
  if(m<0){m=11;y--;}
  if(m>11){m=0;y++;}
  ms.value=m; ys.value=y;
  csSync(ms); csSync(ys);
  renderCalendar(); renderIncomeChart();
}

export function goToday(){
  const now=new Date();
  const ms=document.getElementById('select-month'), ys=document.getElementById('select-year');
  ms.value=now.getMonth(); ys.value=now.getFullYear();
  csSync(ms); csSync(ys);
  renderCalendar();
}

function renderShiftModalOptions(selectedIds){
  const box=document.getElementById('modal-opts');
  if(!box) return;
  box.innerHTML='';
  if(!AppState.shiftTypes.length){
    box.innerHTML=`<div class="chk-desc" style="text-align:center;padding:8px">Немає типів змін. Додай їх кнопкою «Типи змін».</div>`;
    return;
  }
  AppState.shiftTypes.forEach(t=>{
    const checked=selectedIds.includes(t.id)?'checked':'';
    const desc=t.isOff?tr('shifts_rest'):`${t.amount?t.amount.toLocaleString('uk-UA')+' грн':'—'}${t.hours?' · '+t.hours+' '+tr('shifts_hours_short'):''}`;
    const label=document.createElement('label');
    label.className='chk-row';
    label.style.setProperty('--row-color', t.color||'#8b5cf6');
    label.innerHTML=`
      <input type="checkbox" data-stid="${escapeHtml(t.id)}" ${checked}>
      <div class="chk-label"><div class="chk-name">${escapeHtml(t.name)}</div><div class="chk-desc">${escapeHtml(desc)}</div></div>`;
    box.appendChild(label);
  });
}

export function openModal(dateKey, day){
  AppState.selectedDateKey=dateKey;
  const mi=parseInt(document.getElementById('select-month').value);
  document.getElementById('modal-date-title').textContent=`${day} ${AppState.MONTHS[mi]}`;
  renderShiftModalOptions(AppState.shifts[dateKey]||[]);
  document.getElementById('shift-modal').style.display='flex';
}

export function closeModal(){
  document.getElementById('shift-modal').style.display='none';
  AppState.selectedDateKey=null;
}

export function validateModalSelection(){}

export function saveModalSelection(){
  if(!AppState.selectedDateKey) return;
  const al=[];
  document.querySelectorAll('#modal-opts input[type=checkbox]').forEach(el=>{
    if(el.checked) al.push(el.getAttribute('data-stid'));
  });
  if(al.length===0) delete AppState.shifts[AppState.selectedDateKey]; else AppState.shifts[AppState.selectedDateKey]=al;
  saveLocal(); scheduleSave(); closeModal(); renderCalendar(); renderIncomeChart();
}

export function renderCalendar(){
  const grid=document.getElementById('calendar-grid');
  if(!grid) return;
  renderTemplateShiftOptions();
  renderAutoFillUI();
  // Legend from current shift types
  const leg=document.getElementById('shift-legend');
  if(leg){
    leg.innerHTML=AppState.shiftTypes.map(t=>
      `<div class="leg-item"><div class="leg-dot" style="background:${hexA(t.color,.25)};border:1px solid ${hexA(t.color,.6)}"></div>${escapeHtml(t.name)}</div>`
    ).join('');
  }
  grid.innerHTML='';
  const m=parseInt(document.getElementById('select-month').value);
  const y=parseInt(document.getElementById('select-year').value);
  const now=new Date();
  const isCurrent=now.getMonth()===m&&now.getFullYear()===y;

  // Weekday headers
  AppState.WEEKDAYS.forEach((d,i)=>{
    const el=document.createElement('div');
    el.className='wday'+(i>=5?' weekend':'');
    el.textContent=d;
    grid.appendChild(el);
  });

  const firstDay=(new Date(y,m,1).getDay()+6)%7;
  const total=new Date(y,m+1,0).getDate();
  for(let i=0;i<firstDay;i++){const e=document.createElement('div');e.className='day-cell empty';grid.appendChild(e);}

  let earn=0,hrs=0,cShifts=0,cOff=0;

  for(let d=1;d<=total;d++){
    const dk=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
    const ds=AppState.shifts[dk]||[];
    const isToday=isCurrent&&now.getDate()===d;
    const dow=(new Date(y,m,d).getDay()+6)%7;
    const isWeekend=dow>=5;

    const cell=document.createElement('div');
    cell.className='day-cell'+(ds.length?' has-shifts':'')+(isToday?' today':'')+(isWeekend?' weekend-cell':'');

    let badges='';
    ds.forEach(id=>{
      const t=shiftType(id);
      if(!t) return; // unknown/removed type — skip gracefully
      badges+=`<div class="badge" style="background:${hexA(t.color,.2)};border:1px solid ${hexA(t.color,.5)};color:${t.color}">${escapeHtml(t.short||t.name)}</div>`;
      earn+=t.amount||0; hrs+=t.hours||0;
      if(t.isOff) cOff++; else cShifts++;
    });

    cell.innerHTML=`<div class="day-header"><span class="day-num${isWeekend?' weekend-num':''}">${d}</span>${isToday?'<span class="today-pip"></span>':''}</div>${badges}`;
    cell.tabIndex=0;
    cell.onclick=()=>openModal(dk,d);
    cell.onkeydown=e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); openModal(dk,d); } };
    grid.appendChild(cell);
  }

  // Update stats
  const S=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};
  S('total-salary',earn.toLocaleString('uk-UA')+' грн');
  S('total-hours',hrs);
  S('count-shifts',cShifts);
  S('count-off',cOff);
  const empty=document.getElementById('calendar-empty-state');
  if(empty){
    const hasAny=(cShifts+cOff)>0;
    empty.style.display=hasAny?'none':'block';
    empty.innerHTML=hasAny?'':emptyStateHtml({
      icon:'calendar',
      title:tr('shifts_empty_title'),
      desc:tr('shifts_empty_desc'),
      action:tr('shifts_quick_fill'),
      onClick:'toggleQuickFill()'
    });
  }
  // Progress bar
  const pct=Math.min(100,Math.round(earn/SALARY_GOAL*100));
  const bar=document.getElementById('salary-bar');
  const lbl=document.getElementById('salary-bar-label');
  if(bar) bar.style.width=pct+'%';
  if(lbl) lbl.textContent=`${pct}% ${tr('shifts_goal_progress')} ${SALARY_GOAL.toLocaleString('uk-UA')} грн`;
}

export function renderIncomeChart(){
  const container=document.getElementById('income-chart');
  if(!container) return;
  container.innerHTML='';
  const now=new Date();
  const months=[];
  for(let i=5;i>=0;i--){
    let m=now.getMonth()-i, y=now.getFullYear();
    if(m<0){m+=12;y--;}
    months.push({m,y,label:AppState.MONTHS_SHORT[m]});
  }
  const vals=months.map(({m,y})=>{
    let earn=0;
    const prefix=`${y}-${String(m+1).padStart(2,'0')}-`;
    Object.entries(AppState.shifts).forEach(([k,ds])=>{
      if(!k.startsWith(prefix)) return;
      ds.forEach(id=>{ const t=shiftType(id); if(t) earn+=t.amount||0; });
    });
    return earn;
  });
  const maxVal=Math.max(...vals,1);
  const curM=parseInt(document.getElementById('select-month').value);
  const curY=parseInt(document.getElementById('select-year').value);

  months.forEach(({m,y,label},i)=>{
    const isCur=m===curM&&y===curY;
    const pct=Math.round(vals[i]/maxVal*100);
    const wrap=document.createElement('div');
    wrap.className='chart-bar-wrap';
    const earn=vals[i];
    wrap.innerHTML=`
      <div class="chart-bar" style="height:${pct}%;background:${isCur?'var(--purple)':'rgba(139,92,246,.35)'}" data-tip="${earn.toLocaleString('uk-UA')} грн"></div>
      <div class="chart-bar-label" style="${isCur?'color:var(--purple2);font-weight:800':''}">${label}</div>`;
    container.appendChild(wrap);
  });
}

export function renderFinanceChart(){
  const container=document.getElementById('finance-chart');
  if(!container) return;
  container.innerHTML='';
  const now=new Date();
  const months=[];
  for(let i=5;i>=0;i--){
    let m=now.getMonth()-i, y=now.getFullYear();
    if(m<0){m+=12;y--;}
    months.push({m,y,label:AppState.MONTHS_SHORT[m]});
  }
  const vals=months.map(({m,y})=>{
    const prefix=`${y}-${String(m+1).padStart(2,'0')}`;
    let inc=0,exp=0;
    AppState.transactions.forEach(t=>{
      if(!t.date||!t.date.startsWith(prefix)) return;
      if(t.type==='income') inc+=toBase(t.amount,t.currency||'UAH');
      else if(t.type==='expense') exp+=toBase(t.amount,t.currency||'UAH');
    });
    return {inc,exp,net:inc-exp};
  });
  const maxVal=Math.max(...vals.map(v=>Math.max(v.inc,v.exp)),1);

  months.forEach(({label},i)=>{
    const v=vals[i];
    const pctInc=Math.round(v.inc/maxVal*100);
    const pctExp=Math.round(v.exp/maxVal*100);
    const wrap=document.createElement('div');
    wrap.className='chart-bar-wrap';
    wrap.style.gap='2px';
    wrap.innerHTML=`
      <div style="width:100%;display:flex;align-items:flex-end;gap:2px;flex:1">
        <div class="chart-bar" style="flex:1;height:${pctInc}%;background:rgba(16,185,129,.5)" data-tip="+${v.inc.toLocaleString('uk-UA')} грн"></div>
        <div class="chart-bar" style="flex:1;height:${pctExp}%;background:rgba(239,68,68,.4)" data-tip="-${v.exp.toLocaleString('uk-UA')} грн"></div>
      </div>
      <div class="chart-bar-label">${label}</div>`;
    container.appendChild(wrap);
  });
}

export async function clearCurrentMonth(){
  if(!(await uiConfirm(tr('shifts_clear_confirm'),{title:tr('shifts_clear_month'),okText:tr('shifts_clear_ok'),danger:true}))) return;
  const m=parseInt(document.getElementById('select-month').value);
  const y=parseInt(document.getElementById('select-year').value);
  const p=`${y}-${String(m+1).padStart(2,'0')}-`;
  Object.keys(AppState.shifts).forEach(k=>{if(k.startsWith(p))delete AppState.shifts[k];});
  saveLocal(); scheduleSave(); renderCalendar(); renderIncomeChart();
  showToast(tr('shifts_month_cleared'),'trash');
}

function renderTemplateShiftOptions(){
  const sel=document.getElementById('template-shift');
  if(!sel) return;
  const prev=sel.value;
  sel.innerHTML='';
  AppState.shiftTypes.filter(t=>!t.isOff).forEach(t=>{
    const o=document.createElement('option');
    o.value=t.id; o.textContent=t.name;
    sel.appendChild(o);
  });
  if(prev&&AppState.shiftTypes.some(t=>t.id===prev)) sel.value=prev;
}

const toggleQuickFill = function(){
  const body=document.getElementById('tools-panel-body');
  const chev=document.getElementById('tools-toggle-chevron');
  if(!body) return;
  const opening = body.style.display==='none';
  body.style.display = opening ? 'flex' : 'none';
  if(chev) chev.style.transform = opening ? 'rotate(180deg)' : '';
};

const SHIFT_PATTERN_CYCLES={every:[1,0], alt:[1,1], '2_2':[2,2], '3_3':[3,3]};

export async function applyTemplate(){
  const typeId=document.getElementById('template-shift').value;
  const pattern=document.getElementById('template-pattern').value;
  if(!typeId){showToast(tr('shifts_add_type_first'),'xmark');return;}
  const m=parseInt(document.getElementById('select-month').value);
  const y=parseInt(document.getElementById('select-year').value);
  const total=new Date(y,m+1,0).getDate();
  if(!(await uiConfirm(tr('shifts_template_confirm'),{title:tr('shifts_quick_fill'),okText:tr('shifts_template_ok')}))) return;
  const p=`${y}-${String(m+1).padStart(2,'0')}-`;
  Object.keys(AppState.shifts).forEach(k=>{if(k.startsWith(p))delete AppState.shifts[k];});
  const dk=d=>`${p}${String(d).padStart(2,'0')}`;
  const [on,off]=SHIFT_PATTERN_CYCLES[pattern]||SHIFT_PATTERN_CYCLES.every;
  const period=on+off;
  for(let d=1;d<=total;d++){
    if(((d-1)%period)<on) AppState.shifts[dk(d)]=[typeId];
  }
  saveLocal(); scheduleSave(); renderCalendar(); renderIncomeChart();
  showToast(tr('shifts_template_applied'),'bolt');
}

function todayDateKey(){
  const t=new Date();
  return `${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-${String(t.getDate()).padStart(2,'0')}`;
}

function autoFillTypeForDate(dateKey){
  const s=AppState.autoFillSchedule;
  if(!s||!s.enabled||!s.typeId||!s.anchorDate||!shiftType(s.typeId)) return null;
  const [on,off]=SHIFT_PATTERN_CYCLES[s.pattern]||SHIFT_PATTERN_CYCLES.every;
  const period=on+off;
  if(period<=0) return null;
  const anchor=new Date(s.anchorDate+'T00:00:00');
  const target=new Date(dateKey+'T00:00:00');
  const diffDays=Math.round((target-anchor)/86400000);
  if(diffDays<0) return null;
  return (diffDays%period)<on ? s.typeId : null;
}

export function processAutoFillShifts(){
  if(!AppState.autoFillSchedule||!AppState.autoFillSchedule.enabled||!AppState.autoFillSchedule.anchorDate) return 0;
  const today=new Date(); today.setHours(0,0,0,0);
  const earliest=new Date(today); earliest.setDate(earliest.getDate()-60);
  let cursor=new Date(AppState.autoFillSchedule.anchorDate+'T00:00:00');
  if(cursor<earliest) cursor=earliest;
  let added=0, guard=0;
  while(cursor<=today && guard<60){
    const key=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}-${String(cursor.getDate()).padStart(2,'0')}`;
    if(!AppState.shifts[key]){
      const typeId=autoFillTypeForDate(key);
      if(typeId){ AppState.shifts[key]=[typeId]; added++; }
    }
    cursor.setDate(cursor.getDate()+1);
    guard++;
  }
  if(added) saveLocal();
  return added;
}

export function runAutoFillCheck(){
  const added=processAutoFillShifts();
  if(added){ scheduleSave(); renderCalendar(); renderIncomeChart(); }
}

function renderAutoFillUI(){
  const cb=document.getElementById('autofill-toggle-checkbox');
  if(!cb) return;
  cb.checked=!!AppState.autoFillSchedule.enabled;
  const cfgBox=document.getElementById('autofill-config');
  if(cfgBox) cfgBox.style.display=cb.checked?'flex':'none';
  const sel=document.getElementById('autofill-shift');
  if(sel){
    const prev=AppState.autoFillSchedule.typeId||sel.value;
    sel.innerHTML='';
    AppState.shiftTypes.filter(t=>!t.isOff).forEach(t=>{
      const o=document.createElement('option'); o.value=t.id; o.textContent=t.name;
      sel.appendChild(o);
    });
    if(prev&&AppState.shiftTypes.some(t=>t.id===prev)) sel.value=prev;
  }
  const pat=document.getElementById('autofill-pattern');
  if(pat){ pat.value=AppState.autoFillSchedule.pattern||'every'; csSync(pat); }
  const anchor=document.getElementById('autofill-anchor');
  if(anchor && document.activeElement!==anchor){ anchor.value=AppState.autoFillSchedule.anchorDate||''; csSync(anchor); }
}

const toggleAutoFill = function(checked){
  AppState.autoFillSchedule.enabled=checked;
  if(checked){
    if(!AppState.autoFillSchedule.typeId){
      const first=AppState.shiftTypes.find(t=>!t.isOff);
      AppState.autoFillSchedule.typeId=first?first.id:'';
    }
    if(!AppState.autoFillSchedule.anchorDate) AppState.autoFillSchedule.anchorDate=todayDateKey();
  }
  saveConfigLocal(); scheduleSave();
  renderAutoFillUI();
  if(checked){
    const added=processAutoFillShifts();
    if(added){ renderCalendar(); renderIncomeChart(); }
    showToast(tr('shifts_autofill_on'),'bolt');
  }else{
    showToast(tr('shifts_autofill_off'),'check');
  }
};

const saveAutoFillConfig = function(){
  const sel=document.getElementById('autofill-shift');
  const pat=document.getElementById('autofill-pattern');
  const anchor=document.getElementById('autofill-anchor');
  if(!sel||!sel.value){ showToast(tr('shifts_add_type_first'),'xmark'); return; }
  AppState.autoFillSchedule.typeId=sel.value;
  AppState.autoFillSchedule.pattern=pat?pat.value:'every';
  if(anchor&&anchor.value) AppState.autoFillSchedule.anchorDate=anchor.value;
  saveConfigLocal(); scheduleSave();
  const added=processAutoFillShifts();
  if(added){ renderCalendar(); renderIncomeChart(); }
  showToast(tr('shifts_autofill_saved'),'check');
};

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_calendar__(){
// Phase 9 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// this file has no dynamic per-row templates of its own (day cells wire
// openModal via a real cell.onclick=()=>... closure, not a literal onclick
// string) - all these window.* exports existed only for static onclick/
// onchange attributes in index.html. Converted to data-action, same
// pattern as phases 3-8. Also folds in 9 window.* assignments for this
// file's own functions that were sitting in js/color-picker.js's
// __init_color_picker__ (a leftover of the original mechanical split,
// same situation phase 8 found for debt.js's functions) - moved here and
// converted, except openModal/validateModalSelection which turned out to
// have **zero** callers of any kind (openModal is only ever invoked via
// the real cell.onclick closure above; validateModalSelection is an empty
// stub never called anywhere) and were dropped from window.* entirely
// rather than given a pointless data-action.
const CLICK_ACTIONS = {
  'close-modal': ()=>closeModal(),
  'save-modal-selection': ()=>saveModalSelection(),
  'apply-template': ()=>applyTemplate(),
  'clear-current-month': ()=>clearCurrentMonth(),
  'shift-month': ds=>shiftMonth(Number(ds.dir)),
  'go-today': ()=>goToday(),
  'toggle-quick-fill': ()=>toggleQuickFill(),
  'save-autofill-config': ()=>saveAutoFillConfig(),
};
document.addEventListener('click', e=>{
  // #shift-modal's backdrop close is a plain exact-target check (same
  // idea as closeManagers()'s `e.target.classList.contains('modal-overlay')`
  // in settings-managers.js), not a data-action on the overlay itself: a
  // data-action="close-modal" on the overlay div previously matched via
  // closest() for ANY click inside the modal that didn't have its own
  // data-action (e.g. a shift-type checkbox), closing the modal the
  // instant you tried to pick a shift. Real bug, found by a user report
  // ("shifts aren't selectable") plus a Playwright repro.
  if(e.target.id==='shift-modal'){ closeModal(); return; }
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);

const FIELD_ACTIONS = {
  'render-calendar': ()=>renderCalendar(),
  'toggle-auto-fill': (ds,el)=>toggleAutoFill(el.checked),
};
document.addEventListener('change', e=>{
  const el=e.target.closest('[data-action]');
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el);
});

// Still window-exposed: renderCalendar()'s own emptyStateHtml({onClick:
// 'toggleQuickFill()'}) call (the "no shifts yet" empty state) bakes the
// name into a literal onclick="" string via the shared ui-widgets.js
// helper, not a data-action - same reasoning as phase 8's addNewDebt/
// openNewDebtEntryModal.
window.toggleQuickFill = toggleQuickFill;
}
