// ── COLOR-PICKER ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { renderFinance } from './analytics-csv.js';
import { switchTab } from './app-init.js';
import { processAutoFillShifts, renderCalendar, renderFinanceChart, renderIncomeChart } from './calendar.js';
import { DEFAULT_CATEGORIES, DEFAULT_SHIFT_TYPES, DEFAULT_WALLETS, LEGACY_CATEGORIES, LEGACY_SHIFT_TYPES, LEGACY_WALLETS, PALETTE, applyWidgetVisibility, compareTransactionsNewest, getDoc, normalizeWallets, renderPremiumUI, sanitizeWidgetOrder, setDoc, walletCurrency } from './core.js';
import { renderDebt } from './debt.js';
import { updateTag } from './finance.js';
import { batchWriteTransactions, leaveSharedProfile, listSharedMembers, loadActiveProfileRole, loadTransactionsFromSubcollection, lsKey, redeemSharedInvite, saveActiveProfileId, saveProfilesMeta, setMemberRole, shareCurrentProfile, userDoc } from './firebase-sync.js';
import { BUILTIN_AVATARS, renderProfileUI } from './goals-profile.js';
import { renderNotifUI, saveNotifSettings } from './notifications.js';
import { setCacheItem } from './privacy-cache.js';
import { closeManagers, uid, updateShiftType, updateWallet } from './settings-managers.js';
import { applyProfileReadOnlyUI, escapeHtml, setupAccessibleClickableDivs, showToast, uiAlert, uiConfirm, uiPrompt } from './ui-widgets.js';

export const openColorPicker = function(kind,id){
  AppState.colorPickTarget={kind,id};
  renderColorPickerGrid();
  document.getElementById('color-pick-modal').style.display='flex';
};

function currentPickedColor(){
  if(!AppState.colorPickTarget) return '';
  const {kind,id}=AppState.colorPickTarget;
  const item = kind==='wallet' ? AppState.wallets.find(x=>x.id===id)
    : kind==='shiftType' ? AppState.shiftTypes.find(x=>x.id===id)
    : AppState.tags.find(x=>x.id===id);
  return item ? (item.color||'') : '';
}

function renderColorPickerGrid(){
  const box=document.getElementById('color-pick-grid'); if(!box) return;
  const current=currentPickedColor();
  box.innerHTML=PALETTE.map(c=>`<div class="color-opt${c===current?' sel':''}" style="background:${c}" data-action="select-picked-color" data-color="${c}"></div>`).join('');
  setupAccessibleClickableDivs(box);
}

const selectPickedColor = function(color){
  if(!AppState.colorPickTarget) return;
  const {kind,id}=AppState.colorPickTarget;
  if(kind==='wallet') updateWallet(id,'color',color);
  else if(kind==='shiftType') updateShiftType(id,'color',color);
  else if(kind==='tag') updateTag(id,'color',color);
  document.getElementById('color-pick-modal').style.display='none';
};

const addProfile = async function(){
  // No free-tier cap here: premium isn't purchasable yet (no payment
  // provider wired up), so a hard limit would be a dead end for everyone.
  const name=await uiPrompt(tr('profiles_add_prompt'),'',tr('profiles_add_title'));
  if(name===null) return;
  const clean=name.trim(); if(!clean) return;
  AppState.profilesMeta.list.push({id:uid('profile'), name:clean, createdAt:Date.now()});
  await saveProfilesMeta();
  renderProfilesUI();
};

const renameProfile = async function(id){
  const p=AppState.profilesMeta.list.find(x=>x.id===id); if(!p) return;
  const name=await uiPrompt(tr('profiles_rename_prompt'), p.name, tr('profiles_rename_title'));
  if(name===null) return;
  const clean=name.trim(); if(!clean) return;
  p.name=clean;
  await saveProfilesMeta();
  renderProfilesUI();
};

const openProfileAvatarPicker = function(id){
  AppState.avatarPickTargetProfileId=id;
  renderProfileAvatarPickerGrid();
  document.getElementById('profile-avatar-pick-modal').style.display='flex';
};

function renderProfileAvatarPickerGrid(){
  const box=document.getElementById('profile-avatar-pick-grid'); if(!box) return;
  const p=AppState.profilesMeta.list.find(x=>x.id===AppState.avatarPickTargetProfileId);
  box.innerHTML=BUILTIN_AVATARS.map(a=>`<div class="avatar-opt${p&&p.avatar==='builtin:'+a.id?' sel':''}" style="background:${a.gradient}" data-action="select-profile-avatar" data-avatar-id="${a.id}">${window.Icon(a.icon)}</div>`).join('');
  setupAccessibleClickableDivs(box);
}

const selectProfileAvatar = async function(avatarId){
  const p=AppState.profilesMeta.list.find(x=>x.id===AppState.avatarPickTargetProfileId); if(!p) return;
  p.avatar='builtin:'+avatarId;
  await saveProfilesMeta();
  document.getElementById('profile-avatar-pick-modal').style.display='none';
  renderProfilesUI();
};

const deleteProfile = async function(id){
  // Only ever meant for one of this account's own profiles — a shared
  // profile reference is removed via leaveSharedProfileUI() instead
  // (renderProfilesUI() wires the two to different buttons), but guard
  // here too rather than trust the caller.
  const target=AppState.profilesMeta.list.find(p=>p.id===id && p.kind!=='shared');
  if(!target) return;
  if(id===AppState.activeProfileId && !AppState.activeProfileOwnerUid){ showToast(tr('profiles_delete_active_blocked'),'warning'); return; }
  const ownProfiles=AppState.profilesMeta.list.filter(p=>p.kind!=='shared');
  if(ownProfiles.length<=1){ showToast(tr('profiles_delete_last_blocked'),'warning'); return; }
  if(!(await uiConfirm(tr('profiles_delete_confirm'),{title:tr('profiles_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.profilesMeta.list=AppState.profilesMeta.list.filter(p=>p.id!==id || p.kind==='shared');
  await saveProfilesMeta();
  renderProfilesUI();
};

// id + ownerUid together identify a profile: ownerUid is null/omitted for
// one of this account's own profiles, or the sharing account's uid for a
// shared one (see state.js's activeProfileOwnerUid comment).
const switchProfile = async function(id, ownerUid){
  ownerUid = ownerUid || null;
  if(id===AppState.activeProfileId && ownerUid===AppState.activeProfileOwnerUid) return;
  const known = ownerUid
    ? AppState.profilesMeta.list.some(p=>p.id===id && p.kind==='shared' && p.ownerUid===ownerUid)
    : AppState.profilesMeta.list.some(p=>p.id===id && p.kind!=='shared');
  if(!known) return;
  if(!(await uiConfirm(tr('profiles_switch_confirm'),{title:tr('profiles_switch_title'),okText:tr('profiles_switch_btn')}))) return;
  clearTimeout(AppState.fbTimer);
  await fbSaveNow();
  AppState.activeProfileId=id;
  AppState.activeProfileOwnerUid=ownerUid;
  saveActiveProfileId();
  await loadActiveProfileRole();
  applyProfileReadOnlyUI();
  closeManagers();
  await fbLoadNow();
  renderProfileUI(); renderPremiumUI(); applyWidgetVisibility(); renderNotifUI(); renderProfilesUI();
  switchTab('finance');
  showToast(tr('profiles_switched_toast'),'check');
};

// Turns the *current* profile into a shared one and shows the resulting
// invite code in a dialog for the owner to copy/read out to whoever
// should join — plain uiAlert rather than a dedicated share sheet/modal,
// matching this repo's preference for reusing the existing dialog
// primitives over building single-purpose UI for something this simple.
const shareCurrentProfileUI = async function(){
  if(AppState.activeProfileOwnerUid){ showToast(tr('profiles_share_not_owner'),'warning'); return; }
  try{
    const code=await shareCurrentProfile();
    await uiAlert(`${tr('profiles_share_code_msg')}\n\n${code}\n\n${tr('profiles_share_code_hint')}`, tr('profiles_share_code_title'));
  }catch(e){
    console.error(e);
    showToast(tr('sync_autosave_error'),'xmark');
  }
};

const joinSharedProfileUI = async function(){
  const code=await uiPrompt(tr('profiles_join_prompt'), '', tr('profiles_join_title'));
  if(code===null) return;
  const clean=code.trim(); if(!clean) return;
  const result=await redeemSharedInvite(clean);
  if(!result.ok){
    const reasonKey = result.reason==='own-profile' ? 'profiles_join_err_own'
      : result.reason==='used' ? 'profiles_join_err_used'
      : result.reason==='expired' ? 'profiles_join_err_expired'
      : 'profiles_join_err_generic';
    showToast(tr(reasonKey),'xmark');
    return;
  }
  renderProfilesUI();
  showToast(tr('profiles_join_success'),'check');
};

const leaveSharedProfileUI = async function(id, ownerUid){
  if(!(await uiConfirm(tr('profiles_leave_confirm'),{title:tr('profiles_leave_title'),okText:tr('profiles_leave_btn'),danger:true}))) return;
  const wasActive = AppState.activeProfileId===id && AppState.activeProfileOwnerUid===ownerUid;
  try{
    await leaveSharedProfile(ownerUid, id);
  }catch(e){
    console.error(e);
    showToast(tr('sync_autosave_error'),'xmark');
    return;
  }
  if(wasActive){
    const fallback=AppState.profilesMeta.list.find(p=>p.kind!=='shared') || {id:'default'};
    await switchProfile(fallback.id, null);
  }else{
    renderProfilesUI();
  }
  showToast(tr('profiles_left_toast'),'check');
};

// ── SHARED PROFILE MEMBERS MANAGER (granular permissions, a later session) ──
// Owner-only: lists everyone who's joined one of the owner's own profiles,
// with a per-member button to flip their role between editor/viewer. Follows
// the same "Settings manager" modal pattern as every other manager in this
// file (wallets/categories/tags/etc.) — a plain list-render + data-action
// buttons — rather than the single-shot uiAlert/uiPrompt pattern
// shareCurrentProfileUI() above uses, since this needs a genuine per-row
// action (toggle this specific member's role), which a single dialog can't
// cleanly express. currentManagedMembersProfileId tracks which profile's
// members are currently shown so toggleMemberRoleUI() knows which
// shared_members doc to write back to.
let currentManagedMembersProfileId=null;

const openSharedMembersManagerUI = async function(profileId){
  currentManagedMembersProfileId=profileId;
  const modal=document.getElementById('shared-members-modal');
  if(modal) modal.style.display='flex';
  await renderSharedMembersList(profileId);
};

async function renderSharedMembersList(profileId){
  const box=document.getElementById('shared-members-list'); if(!box) return;
  box.innerHTML='';
  let data;
  try{
    data=await listSharedMembers(profileId);
  }catch(e){
    console.error(e);
    showToast(tr('sync_autosave_error'),'xmark');
    return;
  }
  const otherMembers=(data&&data.members||[]).filter(uid=>uid!==AppState.currentUser.uid);
  if(!otherMembers.length){
    box.innerHTML=`<div class="settings-no-results" style="display:block">${tr('profiles_members_none')}</div>`;
    return;
  }
  const roles=data.roles||{};
  otherMembers.forEach(uid=>{
    const role=roles[uid]==='viewer'?'viewer':'editor';
    const row=document.createElement('div');
    row.className='mgr-row';
    // No display-name infrastructure exists between accounts (this app has
    // no contacts/friends list) — a shortened uid is the only identifier
    // available, same limitation the invite-code flow already has.
    const shortUid=escapeHtml(uid.length>10?uid.slice(0,10)+'…':uid);
    row.innerHTML=`
      <div class="mgr-name-inline">${shortUid}</div>
      <span style="font-weight:800;font-size:13px;color:${role==='viewer'?'var(--muted2)':'var(--green2)'};text-transform:uppercase;letter-spacing:.04em;flex:0 0 auto">${role==='viewer'?tr('profiles_member_role_viewer'):tr('profiles_member_role_editor')}</span>
      <button class="btn btn-ghost" style="padding:6px 12px;font-size:13px;flex:0 0 auto" data-action="toggle-member-role" data-uid="${escapeHtml(uid)}" data-role="${role}">${role==='viewer'?tr('profiles_member_make_editor'):tr('profiles_member_make_viewer')}</button>
    `;
    box.appendChild(row);
  });
}

const toggleMemberRoleUI = async function(uid, currentRole){
  if(!currentManagedMembersProfileId) return;
  const nextRole = currentRole==='viewer' ? 'editor' : 'viewer';
  try{
    await setMemberRole(currentManagedMembersProfileId, uid, nextRole);
  }catch(e){
    console.error(e);
    showToast(tr('sync_autosave_error'),'xmark');
    return;
  }
  await renderSharedMembersList(currentManagedMembersProfileId);
  showToast(tr('profiles_member_role_changed'),'check');
};

export function renderProfilesUI(){
  const sub=document.getElementById('settings-profiles-sub');
  if(sub){
    const active=AppState.profilesMeta.list.find(p=>p.id===AppState.activeProfileId && (p.kind==='shared'?p.ownerUid===AppState.activeProfileOwnerUid:!AppState.activeProfileOwnerUid));
    sub.textContent = (active && active.name) ? active.name : tr('settings_profiles_sub');
  }
  const box=document.getElementById('profiles-list'); if(!box) return;
  box.innerHTML='';
  AppState.profilesMeta.list.forEach((p,i)=>{
    const isShared=p.kind==='shared';
    const isActive=p.id===AppState.activeProfileId && (isShared?p.ownerUid===AppState.activeProfileOwnerUid:!AppState.activeProfileOwnerUid);
    const row=document.createElement('div');
    row.className='mgr-row';
    const builtin=p.avatar && p.avatar.startsWith('builtin:') ? BUILTIN_AVATARS.find(a=>'builtin:'+a.id===p.avatar) : null;
    const initial=(p.name||'?').trim().charAt(0).toUpperCase()||'?';
    const avatarBg=builtin ? builtin.gradient : PALETTE[i%PALETTE.length];
    const avatarContent=builtin ? window.Icon(builtin.icon) : escapeHtml(initial);
    // A shared-profile reference's name/avatar are still this account's
    // own cosmetic copy in its own profilesMeta (see redeemSharedInvite())
    // — editable the same way as any other profile, just additionally
    // tagged so it's clear this data isn't solely this account's own.
    const sharedBadge=isShared?`<span style="font-weight:800;font-size:13px;color:var(--purple2);text-transform:uppercase;letter-spacing:.04em;flex:0 0 auto;white-space:nowrap" data-i18n="profiles_shared_badge">Спільний</span>`:'';
    row.innerHTML=`
      <div class="profile-row-avatar" style="background:${avatarBg};color:#fff;cursor:pointer" data-action="open-profile-avatar-picker" data-id="${p.id}">${avatarContent}</div>
      <div class="mgr-name-inline">${escapeHtml(p.name)}</div>
      ${sharedBadge}
      ${isActive
        ? `<span style="font-weight:800;font-size:13px;color:var(--green);text-transform:uppercase;letter-spacing:.04em;flex:0 0 auto">${tr('profiles_active_badge')}</span>`
        : `<button class="btn btn-ghost" style="padding:6px 12px;font-size:13px;flex:0 0 auto" data-action="switch-profile" data-id="${p.id}" ${isShared?`data-owner-uid="${p.ownerUid}"`:''}>${tr('profiles_switch_btn')}</button>`}
      <div class="profile-row-actions">
        ${!isShared ? `<button class="mgr-del" data-action="open-shared-members-manager" data-id="${p.id}" aria-label="${tr('profiles_members_btn')}">${window.Icon('people')}</button>` : ''}
        <button class="mgr-del" data-action="rename-profile" data-id="${p.id}" aria-label="${tr('common_edit')}">${window.Icon('pencil')}</button>
        ${isShared
          ? `<button class="mgr-del" data-action="leave-shared-profile" data-id="${p.id}" data-owner-uid="${p.ownerUid}" aria-label="${tr('profiles_leave_btn')}">${window.Icon('logout')}</button>`
          : `<button class="mgr-del" data-action="delete-profile" data-id="${p.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>`}
      </div>
    `;
    box.appendChild(row);
  });
  setupAccessibleClickableDivs(box);
}

function fbSetStatus(type, text){
  const el=document.getElementById('fb-status');
  const tx=document.getElementById('fb-text');
  if(!el||!tx) return;
  el.className='sync-chip '+type;
  tx.textContent=text;
}

async function fbSaveNow(){
  if(!AppState.currentUser) return;
  fbSetStatus('loading',tr('sync_saving'));
  try{
    const [sChk,fChk,dChk]=await Promise.all([
      getDoc(userDoc('shifts')), getDoc(userDoc('finance')), getDoc(userDoc('debt')),
    ]);
    const remoteUpdatedAt={
      shifts:  sChk.exists()?(sChk.data().updatedAt||0):0,
      finance: fChk.exists()?(fChk.data().updatedAt||0):0,
      debt:    dChk.exists()?(dChk.data().updatedAt||0):0,
    };
    const conflict=Object.keys(remoteUpdatedAt).some(k=>remoteUpdatedAt[k]>AppState.lastKnownUpdatedAt[k]);
    if(conflict){
      fbSetStatus('error',tr('sync_conflict'));
      const overwrite=await uiConfirm(tr('sync_conflict_msg'), {title:tr('sync_conflict_title'), okText:tr('sync_conflict_overwrite'), cancelText:tr('sync_conflict_load_fresh')});
      if(!overwrite){ await fbLoadNow(); return; }
    }
    const now=Date.now();
    await Promise.all([
      setDoc(userDoc('shifts'),  {data:AppState.shifts, shiftTypes: AppState.shiftTypes, autoFillSchedule: AppState.autoFillSchedule, updatedAt:now}, {merge:false}),
      // No `data`/transactions array here anymore — each transaction is its
      // own doc in the `transactions` subcollection (see the TRANSACTIONS
      // SUBCOLLECTION section of js/firebase-sync.js) and is written
      // directly by whatever function mutates it, not batched into this
      // whole-finance-doc rewrite. `{merge:false}` replacing the whole doc
      // is exactly what drops any stale legacy `data` field for an
      // already-migrated account, with no extra cleanup code needed.
      setDoc(userDoc('finance'), {wallets: AppState.wallets, categories: AppState.categories, budgets: AppState.budgets, subcategories: AppState.subcategories, categoryIcons: AppState.categoryIcons, currencyRates: AppState.currencyRates, tags: AppState.tags, autoRules: AppState.autoRules, recurring: AppState.recurring, shoppingList: AppState.shoppingList, goals: AppState.goals, profile: AppState.profile, subscription: AppState.subscription, widgets: AppState.widgets, widgetOrder: AppState.widgetOrder, notifSettings: AppState.notifSettings, integrations: AppState.integrations, catBackfillDone: AppState.catBackfillDone, catLegacyMerged: AppState.catLegacyMerged, txMigrated: AppState.txMigrated, updatedAt:now}, {merge:false}),
      setDoc(userDoc('debt'),    {data:{debts: AppState.debts, currentDebtId: AppState.currentDebtId}, updatedAt:now}, {merge:false}),
    ]);
    AppState.lastKnownUpdatedAt={shifts:now, finance:now, debt:now};
    fbSetStatus('ok',tr('sync_saved'));
  }catch(e){
    console.error(e);
    fbSetStatus('error',tr('sync_error'));
    showToast(tr('sync_autosave_error'),'xmark');
  }
}

export function normalizeDebtData(raw){
  if(!raw) return null;
  if(Array.isArray(raw.debts)&&raw.debts.length){
    return {debts:raw.debts, currentDebtId:raw.currentDebtId||raw.debts[0].id};
  }
  if(raw.info){
    const d={id:1,name:raw.info.name||'Борг',note:raw.info.note||'',currency:raw.info.currency||'у.о.',startAmount:raw.info.startAmount||0,entries:raw.entries||[]};
    return {debts:[d], currentDebtId:d.id};
  }
  return null;
}

export function seedConfigFromDocs(sData, fData){
  let seeded=false;
  const hasData = Object.keys(AppState.shifts).length>0 || AppState.transactions.length>0 || (AppState.debts&&AppState.debts.length>0);
  if(Array.isArray(sData&&sData.shiftTypes) && sData.shiftTypes.length){
    AppState.shiftTypes=sData.shiftTypes;
  }else{
    AppState.shiftTypes=(hasData?LEGACY_SHIFT_TYPES:DEFAULT_SHIFT_TYPES).map(t=>({...t}));
    seeded=true;
  }
  if(Array.isArray(fData&&fData.wallets) && fData.wallets.length){
    AppState.wallets=fData.wallets;
  }else{
    AppState.wallets=(hasData?LEGACY_WALLETS:DEFAULT_WALLETS).map(w=>({...w}));
    seeded=true;
  }
  normalizeWallets();
  if(fData&&fData.categories&&(fData.categories.income||fData.categories.expense)){
    AppState.categories={income:fData.categories.income||[], expense:fData.categories.expense||[]};
  }else{
    AppState.categories={income:[...DEFAULT_CATEGORIES.income], expense:[...DEFAULT_CATEGORIES.expense]};
    seeded=true;
  }
  AppState.budgets = (fData && fData.budgets) ? {...fData.budgets} : {};
  AppState.subcategories = (fData && fData.subcategories) ? {...fData.subcategories} : {};
  AppState.categoryIcons = (fData && fData.categoryIcons) ? {...fData.categoryIcons} : {};
  AppState.currencyRates = (fData && fData.currencyRates) ? {...fData.currencyRates} : {};
  AppState.tags = (fData && Array.isArray(fData.tags)) ? fData.tags : [];
  AppState.autoRules = (fData && Array.isArray(fData.autoRules)) ? fData.autoRules : [];
  AppState.goals = (fData && Array.isArray(fData.goals)) ? fData.goals : [];
  AppState.profile = (fData && fData.profile) ? {nickname:fData.profile.nickname||'', avatar:fData.profile.avatar||''} : {nickname:'', avatar:''};
  AppState.subscription = (fData && fData.subscription) ? {plan:fData.subscription.plan||'free', expiresAt:fData.subscription.expiresAt||null} : {plan:'free', expiresAt:null};
  AppState.widgets = (fData && fData.widgets && typeof fData.widgets==='object') ? {rates:fData.widgets.rates!==false, converter:fData.widgets.converter!==false, analytics:fData.widgets.analytics!==false, chart:fData.widgets.chart!==false, goals:fData.widgets.goals!==false, dailyTip:fData.widgets.dailyTip!==false, cryptoTop:fData.widgets.cryptoTop!==false} : {rates:true, converter:true, analytics:true, chart:true, goals:true, dailyTip:true, cryptoTop:true};
  AppState.widgetOrder = sanitizeWidgetOrder(fData && fData.widgetOrder);
  // Merged (not replaced) over the local/localStorage copy, so a value
  // set on another device wins, but nothing here can be missing — the
  // Cloud Function sweep needs a complete object, not a partial one.
  if(fData && fData.notifSettings && typeof fData.notifSettings==='object') AppState.notifSettings={...AppState.notifSettings, ...fData.notifSettings};
  // Backfill/refresh timeZone for accounts that enabled reminders before
  // this field existed, or moved to a different timezone since — without
  // this, notificationSweep falls back to UTC for anyone whose settings
  // predate the fix. Only triggers a save if it actually changed, so this
  // doesn't spam writes for accounts with reminders off.
  try{
    const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
    if(AppState.notifSettings.enabled && AppState.notifSettings.timeZone!==tz){ AppState.notifSettings.timeZone=tz; saveNotifSettings(); }
  }catch(e){}
  AppState.catBackfillDone = !!(fData && fData.catBackfillDone);
  AppState.catLegacyMerged = !!(fData && fData.catLegacyMerged);
  AppState.integrations = (fData && fData.integrations && typeof fData.integrations==='object') ? fData.integrations : {monobank:null};
  return seeded;
}

function backfillCategories(){
  if(AppState.catLegacyMerged) return false;
  const hasData = Object.keys(AppState.shifts).length>0 || AppState.transactions.length>0 || (AppState.debts&&AppState.debts.length>0);
  let changed=false;
  const add=(type,name)=>{
    const c=(name||'').trim();
    if(!c || c==='Внутрішній переказ') return;
    if(!AppState.categories[type]) AppState.categories[type]=[];
    if(!AppState.categories[type].includes(c)){ AppState.categories[type].push(c); changed=true; }
  };
  if(hasData){
    LEGACY_CATEGORIES.income.forEach(c=>add('income',c));
    LEGACY_CATEGORIES.expense.forEach(c=>add('expense',c));
  }
  AppState.transactions.forEach(t=>{ if(t.type==='income'||t.type==='expense') add(t.type, t.category); });
  AppState.catLegacyMerged=true; AppState.catBackfillDone=true;
  return changed;
}

export async function fbLoadNow(){
  if(!AppState.currentUser) return;
  fbSetStatus('loading',tr('sync_loading'));
  try{
    // loadTransactionsFromSubcollection() doesn't depend on the finance-doc
    // fetch below (it only needs userDoc('finance') to build the
    // subcollection path, not its contents), so it runs in parallel with
    // the other three doc reads rather than after them.
    const [sS,fS,dS,subTx]=await Promise.all([getDoc(userDoc('shifts')),getDoc(userDoc('finance')),getDoc(userDoc('debt')),loadTransactionsFromSubcollection()]);
    const sData=sS.exists()?sS.data():null;
    const fData=fS.exists()?fS.data():null;
    AppState.shifts=sData?(sData.data||{}):{};
    const sk=lsKey('shifts'); if(sk) setCacheItem(sk,JSON.stringify(AppState.shifts));
    AppState.autoFillSchedule=(sData&&sData.autoFillSchedule&&typeof sData.autoFillSchedule==='object')
      ? {enabled:!!sData.autoFillSchedule.enabled, typeId:sData.autoFillSchedule.typeId||'', pattern:sData.autoFillSchedule.pattern||'every', anchorDate:sData.autoFillSchedule.anchorDate||''}
      : {enabled:false, typeId:'', pattern:'every', anchorDate:''};
    // Transactions live in the `transactions` subcollection now, not
    // finance.data (see js/firebase-sync.js's TRANSACTIONS SUBCOLLECTION
    // section). One-time migration for any account/profile that hasn't
    // been migrated yet: if the subcollection is still empty but the
    // legacy array has entries, copy them in once and flip txMigrated so
    // this never runs again for this doc — guards against a later load
    // (after the account has since deleted every transaction, leaving the
    // subcollection legitimately empty again) resurrecting the stale array.
    AppState.txMigrated=!!(fData && fData.txMigrated);
    const legacyTx=fData?(fData.data||[]):[];
    let migratedNow=false;
    if(!AppState.txMigrated && legacyTx.length){
      await batchWriteTransactions(legacyTx);
      AppState.transactions=legacyTx;
      AppState.txMigrated=true;
      migratedNow=true;
    }else{
      AppState.transactions=subTx;
    }
    // Firestore's getDocs() on the transactions subcollection has no
    // orderBy — document order is unspecified, not "insertion order" or
    // "newest first" the way addTransaction()'s unshift() makes a
    // *locally-added* transaction land at index 0. Without this explicit
    // sort, a loaded account's history could render in essentially
    // arbitrary order (confirmed by a real account owner screenshot
    // showing oldest-first) even though renderFinance() has always sliced
    // "the first N" for the collapsed view assuming that meant "newest N".
    // Sorted once here (not per-render) so every array-order consumer
    // (renderFinance, the cached localStorage copy read back on next cold
    // start, etc.) sees a consistent newest-first order without each call
    // site needing its own sort.
    AppState.transactions.sort(compareTransactionsNewest);
    const tk=lsKey('tx'); if(tk) setCacheItem(tk,JSON.stringify(AppState.transactions));
    AppState.recurring=fData?(fData.recurring||[]):[];
    saveRecurringLocal();
    AppState.shoppingList=fData?(fData.shoppingList||[]):[];
    saveShoppingLocal();
    if(dS.exists()){
      const norm=normalizeDebtData(dS.data().data);
      AppState.debts=norm?norm.debts:[]; AppState.currentDebtId=norm?norm.currentDebtId:null;
    }else{
      AppState.debts=[]; AppState.currentDebtId=null;
    }
    saveDebtLocal();
    const seeded=seedConfigFromDocs(sData, fData);
    const backfilled=backfillCategories();
    saveConfigLocal();
    const recurAdded=await processRecurring();
    const autoFillAdded=processAutoFillShifts();
    AppState.lastKnownUpdatedAt={
      shifts:  sS.exists()?(sS.data().updatedAt||0):0,
      finance: fS.exists()?(fS.data().updatedAt||0):0,
      debt:    dS.exists()?(dS.data().updatedAt||0):0,
    };
    fbSetStatus('ok',tr('sync_synced'));
    renderCalendar(); renderFinance(); renderIncomeChart(); renderFinanceChart(); renderDebt();
    // Sync itself stays silent — only surfaced to the user when something
    // actually needs their attention (a conflict, or being offline below).
    if(recurAdded) showToast(`${tr('sync_recur_added')} ${recurAdded} ${tr('sync_recur_suffix')}`,'repeat');
    if(autoFillAdded) showToast(`${tr('shifts_autofill_added')} ${autoFillAdded}`,'bolt');
    // Persist newly-seeded config, keeping a one-time raw backup first so
    // the original docs can always be recovered if anything looks wrong.
    if(seeded){
      try{
        await setDoc(userDoc('backup_v2'), {
          shifts:sData||null, finance:fData||null,
          debt:dS.exists()?dS.data():null, at:Date.now()
        }, {merge:false});
      }catch(be){ console.error('backup failed', be); }
    }
    if(seeded||backfilled||recurAdded||autoFillAdded||migratedNow) await fbSaveNow();
  }catch(e){
    console.error(e);
    fbSetStatus('error',tr('sync_offline'));
    showToast(tr('sync_cloud_unavailable'),'offline');
  }
}

export function scheduleSave(){
  fbSetStatus('loading',tr('sync_autosave'));
  clearTimeout(AppState.fbTimer);
  AppState.fbTimer=setTimeout(fbSaveNow,1800);
}

export function saveLocal(){
  const k=lsKey('shifts'); if(k) setCacheItem(k,JSON.stringify(AppState.shifts));
}

export function saveDebtLocal(){
  const k=lsKey('debt'); if(k) setCacheItem(k, JSON.stringify({debts: AppState.debts, currentDebtId: AppState.currentDebtId}));
}

export function saveRecurringLocal(){
  const k=lsKey('recurring'); if(k) setCacheItem(k, JSON.stringify(AppState.recurring));
}

export function saveShoppingLocal(){
  const k=lsKey('shopping'); if(k) localStorage.setItem(k, JSON.stringify(AppState.shoppingList));
}

function computeNextDate(dateStr, freq){
  const d=new Date(dateStr+'T00:00:00');
  if(freq==='daily') d.setDate(d.getDate()+1);
  else if(freq==='weekly') d.setDate(d.getDate()+7);
  else d.setMonth(d.getMonth()+1); // monthly (default)
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

async function processRecurring(){
  if(!AppState.recurring.length) return 0;
  const todayStr=new Date().toISOString().split('T')[0];
  let added=0;
  const newTx=[];
  AppState.recurring.forEach(r=>{
    if(r.active===false || !r.nextDate || !r.amount) return;
    let guard=0;
    while(r.nextDate<=todayStr && guard<24){
      const t={
        id:uid('tx'), createdAt:Date.now()+added, type:r.type, amount:r.amount, currency:walletCurrency(r.wallet), category:r.category||'Інше',
        wallet:r.wallet, targetWallet:null, targetAmount:null, targetCurrency:null, date:r.nextDate,
        comment:(r.comment?r.comment+' · ':'')+tr('recurring_comment_tag')
      };
      AppState.transactions.unshift(t);
      newTx.push(t);
      r.nextDate=computeNextDate(r.nextDate, r.frequency||'monthly');
      added++; guard++;
    }
  });
  if(added){
    const tk=lsKey('tx'); if(tk) setCacheItem(tk,JSON.stringify(AppState.transactions));
    saveRecurringLocal();
    await batchWriteTransactions(newTx);
  }
  return added;
}

export function saveConfigLocal(){
  const k=lsKey('cfg'); if(k) setCacheItem(k, JSON.stringify({shiftTypes: AppState.shiftTypes, autoFillSchedule: AppState.autoFillSchedule, wallets: AppState.wallets, categories: AppState.categories, budgets: AppState.budgets, subcategories: AppState.subcategories, categoryIcons: AppState.categoryIcons, currencyRates: AppState.currencyRates, tags: AppState.tags, autoRules: AppState.autoRules, goals: AppState.goals, profile: AppState.profile, subscription: AppState.subscription, widgets: AppState.widgets, widgetOrder: AppState.widgetOrder, integrations: AppState.integrations, catBackfillDone: AppState.catBackfillDone, catLegacyMerged: AppState.catLegacyMerged}));
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_color_picker__(){
// Phase 4 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// this file's own 6 dynamic onclick sites (color swatches, avatar picker,
// profile row buttons) plus static ones in index.html (add-profile,
// open-profiles-manager) replaced with a data-action attribute dispatched
// through one delegated listener, same pattern as js/settings-managers.js's
// phase 3. CAPTURE phase for the same reason as there: several of these
// buttons sit inside a .modal-card whose own onclick="event.stopPropagation()"
// would otherwise swallow a bubble-phase document listener.
const CLICK_ACTIONS = {
  'select-picked-color': ds=>selectPickedColor(ds.color),
  'select-profile-avatar': ds=>selectProfileAvatar(ds.avatarId),
  'open-profile-avatar-picker': ds=>openProfileAvatarPicker(ds.id),
  'switch-profile': ds=>switchProfile(ds.id, ds.ownerUid||null),
  'rename-profile': ds=>renameProfile(ds.id),
  'delete-profile': ds=>deleteProfile(ds.id),
  'add-profile': ()=>addProfile(),
  'open-profiles-manager': ()=>{ document.getElementById('profiles-modal').style.display='flex'; renderProfilesUI(); },
  'share-current-profile': ()=>shareCurrentProfileUI(),
  'join-shared-profile': ()=>joinSharedProfileUI(),
  'leave-shared-profile': ds=>leaveSharedProfileUI(ds.id, ds.ownerUid),
  'open-shared-members-manager': ds=>openSharedMembersManagerUI(ds.id),
  'toggle-member-role': ds=>toggleMemberRoleUI(ds.uid, ds.role),
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);

// Color swatches now call openColorPicker through imported data-action
// handlers, so no CSP-sensitive window.* export is needed here.
// openModal/closeModal/saveModalSelection/validateModalSelection/
// applyTemplate/clearCurrentMonth/renderCalendar/shiftMonth/goToday
// (calendar.js's own functions) and setFinanceType/addTransaction/
// deleteTransaction/setTxFilter (finance.js's own) used to be re-exported
// here too (a leftover of the original mechanical split landing other
// files' window.* assignments in this file's chunk) - moved to
// js/calendar.js's and js/finance.js's own __init_*__() functions as part
// of phases 8-9 of the window.*/onclick removal audit item, see CLAUDE.md.
}
