// ── COLOR-PICKER ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { renderFinance } from './analytics-csv.js';
import { switchTab } from './app-init.js';
import { applyTemplate, clearCurrentMonth, closeModal, goToday, openModal, processAutoFillShifts, renderCalendar, renderFinanceChart, renderIncomeChart, saveModalSelection, shiftMonth, validateModalSelection } from './calendar.js';
import { DEFAULT_CATEGORIES, DEFAULT_SHIFT_TYPES, DEFAULT_WALLETS, LEGACY_CATEGORIES, LEGACY_SHIFT_TYPES, LEGACY_WALLETS, PALETTE, applyWidgetVisibility, getDoc, normalizeWallets, renderPremiumUI, sanitizeWidgetOrder, setDoc, walletCurrency } from './core.js';
import { addDebtEntry, deleteCurrentDebt, deleteDebtEntry, renderDebt, updateDebtEntry, updateDebtInfo } from './debt.js';
import { addTransaction, deleteTransaction, setFinanceType, setTxFilter, updateTag } from './finance.js';
import { activeProfileLsKey, lsKey, saveProfilesMeta, userDoc } from './firebase-sync.js';
import { BUILTIN_AVATARS, renderProfileUI } from './goals-profile.js';
import { renderNotifUI, saveNotifSettings } from './notifications.js';
import { closeManagers, uid, updateShiftType, updateWallet } from './settings-managers.js';
import { escapeHtml, setupAccessibleClickableDivs, showToast, uiConfirm, uiPrompt } from './ui-widgets.js';

const openColorPicker = function(kind,id){
  AppState.colorPickTarget={kind,id};
  renderColorPickerGrid();
  document.getElementById('color-pick-modal').style.display='flex';
};

function currentPickedColor(){
  if(!AppState.colorPickTarget) return '';
  const {kind,id}=AppState.colorPickTarget;
  const item = kind==='wallet' ? AppState.wallets.find(x=>x.id===id)
    : kind==='shiftType' ? AppState.shiftTypes.find(x=>x.id===id)
    : AppState.tags.find(x=>x.id===id);
  return item ? (item.color||'') : '';
}

function renderColorPickerGrid(){
  const box=document.getElementById('color-pick-grid'); if(!box) return;
  const current=currentPickedColor();
  box.innerHTML=PALETTE.map(c=>`<div class="color-opt${c===current?' sel':''}" style="background:${c}" onclick="selectPickedColor('${c}')"></div>`).join('');
  setupAccessibleClickableDivs(box);
}

const selectPickedColor = function(color){
  if(!AppState.colorPickTarget) return;
  const {kind,id}=AppState.colorPickTarget;
  if(kind==='wallet') updateWallet(id,'color',color);
  else if(kind==='shiftType') updateShiftType(id,'color',color);
  else if(kind==='tag') updateTag(id,'color',color);
  document.getElementById('color-pick-modal').style.display='none';
};

const addProfile = async function(){
  // No free-tier cap here: premium isn't purchasable yet (no payment
  // provider wired up), so a hard limit would be a dead end for everyone.
  const name=await uiPrompt(tr('profiles_add_prompt'),'',tr('profiles_add_title'));
  if(name===null) return;
  const clean=name.trim(); if(!clean) return;
  AppState.profilesMeta.list.push({id:uid('profile'), name:clean, createdAt:Date.now()});
  await saveProfilesMeta();
  renderProfilesUI();
};

const renameProfile = async function(id){
  const p=AppState.profilesMeta.list.find(x=>x.id===id); if(!p) return;
  const name=await uiPrompt(tr('profiles_rename_prompt'), p.name, tr('profiles_rename_title'));
  if(name===null) return;
  const clean=name.trim(); if(!clean) return;
  p.name=clean;
  await saveProfilesMeta();
  renderProfilesUI();
};

const openProfileAvatarPicker = function(id){
  AppState.avatarPickTargetProfileId=id;
  renderProfileAvatarPickerGrid();
  document.getElementById('profile-avatar-pick-modal').style.display='flex';
};

function renderProfileAvatarPickerGrid(){
  const box=document.getElementById('profile-avatar-pick-grid'); if(!box) return;
  const p=AppState.profilesMeta.list.find(x=>x.id===AppState.avatarPickTargetProfileId);
  box.innerHTML=BUILTIN_AVATARS.map(a=>`<div class="avatar-opt${p&&p.avatar==='builtin:'+a.id?' sel':''}" style="background:${a.gradient}" onclick="selectProfileAvatar('${a.id}')">${window.Icon(a.icon)}</div>`).join('');
  setupAccessibleClickableDivs(box);
}

const selectProfileAvatar = async function(avatarId){
  const p=AppState.profilesMeta.list.find(x=>x.id===AppState.avatarPickTargetProfileId); if(!p) return;
  p.avatar='builtin:'+avatarId;
  await saveProfilesMeta();
  document.getElementById('profile-avatar-pick-modal').style.display='none';
  renderProfilesUI();
};

const deleteProfile = async function(id){
  if(id===AppState.activeProfileId){ showToast(tr('profiles_delete_active_blocked'),'warning'); return; }
  if(AppState.profilesMeta.list.length<=1){ showToast(tr('profiles_delete_last_blocked'),'warning'); return; }
  if(!(await uiConfirm(tr('profiles_delete_confirm'),{title:tr('profiles_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.profilesMeta.list=AppState.profilesMeta.list.filter(p=>p.id!==id);
  await saveProfilesMeta();
  renderProfilesUI();
};

const switchProfile = async function(id){
  if(id===AppState.activeProfileId) return;
  if(!AppState.profilesMeta.list.some(p=>p.id===id)) return;
  if(!(await uiConfirm(tr('profiles_switch_confirm'),{title:tr('profiles_switch_title'),okText:tr('profiles_switch_btn')}))) return;
  clearTimeout(AppState.fbTimer);
  await fbSaveNow();
  AppState.activeProfileId=id;
  try{ const k=activeProfileLsKey(); if(k) localStorage.setItem(k, AppState.activeProfileId); }catch(e){}
  closeManagers();
  await fbLoadNow();
  renderProfileUI(); renderPremiumUI(); applyWidgetVisibility(); renderNotifUI(); renderProfilesUI();
  switchTab('finance');
  showToast(tr('profiles_switched_toast'),'check');
};

export function renderProfilesUI(){
  const sub=document.getElementById('settings-profiles-sub');
  if(sub){
    const active=AppState.profilesMeta.list.find(p=>p.id===AppState.activeProfileId);
    sub.textContent = (active && active.name) ? active.name : tr('settings_profiles_sub');
  }
  const box=document.getElementById('profiles-list'); if(!box) return;
  box.innerHTML='';
  AppState.profilesMeta.list.forEach((p,i)=>{
    const isActive=p.id===AppState.activeProfileId;
    const row=document.createElement('div');
    row.className='mgr-row';
    const builtin=p.avatar && p.avatar.startsWith('builtin:') ? BUILTIN_AVATARS.find(a=>'builtin:'+a.id===p.avatar) : null;
    const initial=(p.name||'?').trim().charAt(0).toUpperCase()||'?';
    const avatarBg=builtin ? builtin.gradient : PALETTE[i%PALETTE.length];
    const avatarContent=builtin ? window.Icon(builtin.icon) : escapeHtml(initial);
    row.innerHTML=`
      <div class="profile-row-avatar" style="background:${avatarBg};color:#fff;cursor:pointer" onclick="openProfileAvatarPicker('${p.id}')">${avatarContent}</div>
      <div class="mgr-name-inline">${escapeHtml(p.name)}</div>
      ${isActive
        ? `<span style="font-weight:800;font-size:11px;color:var(--green);text-transform:uppercase;letter-spacing:.04em;flex:0 0 auto">${tr('profiles_active_badge')}</span>`
        : `<button class="btn btn-ghost" style="padding:6px 12px;font-size:12px;flex:0 0 auto" onclick="switchProfile('${p.id}')">${tr('profiles_switch_btn')}</button>`}
      <button class="mgr-del" onclick="renameProfile('${p.id}')" aria-label="${tr('common_edit')}">${window.Icon('pencil')}</button>
      <button class="mgr-del" onclick="deleteProfile('${p.id}')" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
    `;
    box.appendChild(row);
  });
  setupAccessibleClickableDivs(box);
}

function fbSetStatus(type, text){
  const el=document.getElementById('fb-status');
  const tx=document.getElementById('fb-text');
  if(!el||!tx) return;
  el.className='sync-chip '+type;
  tx.textContent=text;
}

async function fbSaveNow(){
  if(!AppState.currentUser) return;
  fbSetStatus('loading',tr('sync_saving'));
  try{
    const [sChk,fChk,dChk]=await Promise.all([
      getDoc(userDoc('shifts')), getDoc(userDoc('finance')), getDoc(userDoc('debt')),
    ]);
    const remoteUpdatedAt={
      shifts:  sChk.exists()?(sChk.data().updatedAt||0):0,
      finance: fChk.exists()?(fChk.data().updatedAt||0):0,
      debt:    dChk.exists()?(dChk.data().updatedAt||0):0,
    };
    const conflict=Object.keys(remoteUpdatedAt).some(k=>remoteUpdatedAt[k]>AppState.lastKnownUpdatedAt[k]);
    if(conflict){
      fbSetStatus('error',tr('sync_conflict'));
      const overwrite=await uiConfirm(tr('sync_conflict_msg'), {title:tr('sync_conflict_title'), okText:tr('sync_conflict_overwrite'), cancelText:tr('sync_conflict_load_fresh')});
      if(!overwrite){ await fbLoadNow(); return; }
    }
    const now=Date.now();
    await Promise.all([
      setDoc(userDoc('shifts'),  {data:AppState.shifts, shiftTypes: AppState.shiftTypes, autoFillSchedule: AppState.autoFillSchedule, updatedAt:now}, {merge:false}),
      setDoc(userDoc('finance'), {data:AppState.transactions, wallets: AppState.wallets, categories: AppState.categories, budgets: AppState.budgets, subcategories: AppState.subcategories, currencyRates: AppState.currencyRates, tags: AppState.tags, autoRules: AppState.autoRules, recurring: AppState.recurring, shoppingList: AppState.shoppingList, goals: AppState.goals, profile: AppState.profile, subscription: AppState.subscription, widgets: AppState.widgets, widgetOrder: AppState.widgetOrder, notifSettings: AppState.notifSettings, catBackfillDone: AppState.catBackfillDone, catLegacyMerged: AppState.catLegacyMerged, updatedAt:now}, {merge:false}),
      setDoc(userDoc('debt'),    {data:{debts: AppState.debts, currentDebtId: AppState.currentDebtId}, updatedAt:now}, {merge:false}),
    ]);
    AppState.lastKnownUpdatedAt={shifts:now, finance:now, debt:now};
    fbSetStatus('ok',tr('sync_saved'));
  }catch(e){
    console.error(e);
    fbSetStatus('error',tr('sync_error'));
    showToast(tr('sync_autosave_error'),'xmark');
  }
}

export function normalizeDebtData(raw){
  if(!raw) return null;
  if(Array.isArray(raw.debts)&&raw.debts.length){
    return {debts:raw.debts, currentDebtId:raw.currentDebtId||raw.debts[0].id};
  }
  if(raw.info){
    const d={id:1,name:raw.info.name||'Борг',note:raw.info.note||'',currency:raw.info.currency||'у.о.',startAmount:raw.info.startAmount||0,entries:raw.entries||[]};
    return {debts:[d], currentDebtId:d.id};
  }
  return null;
}

export function seedConfigFromDocs(sData, fData){
  let seeded=false;
  const hasData = Object.keys(AppState.shifts).length>0 || AppState.transactions.length>0 || (AppState.debts&&AppState.debts.length>0);
  if(Array.isArray(sData&&sData.shiftTypes) && sData.shiftTypes.length){
    AppState.shiftTypes=sData.shiftTypes;
  }else{
    AppState.shiftTypes=(hasData?LEGACY_SHIFT_TYPES:DEFAULT_SHIFT_TYPES).map(t=>({...t}));
    seeded=true;
  }
  if(Array.isArray(fData&&fData.wallets) && fData.wallets.length){
    AppState.wallets=fData.wallets;
  }else{
    AppState.wallets=(hasData?LEGACY_WALLETS:DEFAULT_WALLETS).map(w=>({...w}));
    seeded=true;
  }
  normalizeWallets();
  if(fData&&fData.categories&&(fData.categories.income||fData.categories.expense)){
    AppState.categories={income:fData.categories.income||[], expense:fData.categories.expense||[]};
  }else{
    AppState.categories={income:[...DEFAULT_CATEGORIES.income], expense:[...DEFAULT_CATEGORIES.expense]};
    seeded=true;
  }
  AppState.budgets = (fData && fData.budgets) ? {...fData.budgets} : {};
  AppState.subcategories = (fData && fData.subcategories) ? {...fData.subcategories} : {};
  AppState.currencyRates = (fData && fData.currencyRates) ? {...fData.currencyRates} : {};
  AppState.tags = (fData && Array.isArray(fData.tags)) ? fData.tags : [];
  AppState.autoRules = (fData && Array.isArray(fData.autoRules)) ? fData.autoRules : [];
  AppState.goals = (fData && Array.isArray(fData.goals)) ? fData.goals : [];
  AppState.profile = (fData && fData.profile) ? {nickname:fData.profile.nickname||'', avatar:fData.profile.avatar||''} : {nickname:'', avatar:''};
  AppState.subscription = (fData && fData.subscription) ? {plan:fData.subscription.plan||'free', expiresAt:fData.subscription.expiresAt||null} : {plan:'free', expiresAt:null};
  AppState.widgets = (fData && fData.widgets && typeof fData.widgets==='object') ? {rates:fData.widgets.rates!==false, converter:fData.widgets.converter!==false, analytics:fData.widgets.analytics!==false, chart:fData.widgets.chart!==false, goals:fData.widgets.goals!==false} : {rates:true, converter:true, analytics:true, chart:true, goals:true};
  AppState.widgetOrder = sanitizeWidgetOrder(fData && fData.widgetOrder);
  // Merged (not replaced) over the local/localStorage copy, so a value
  // set on another device wins, but nothing here can be missing — the
  // Cloud Function sweep needs a complete object, not a partial one.
  if(fData && fData.notifSettings && typeof fData.notifSettings==='object') AppState.notifSettings={...AppState.notifSettings, ...fData.notifSettings};
  // Backfill/refresh timeZone for accounts that enabled reminders before
  // this field existed, or moved to a different timezone since — without
  // this, notificationSweep falls back to UTC for anyone whose settings
  // predate the fix. Only triggers a save if it actually changed, so this
  // doesn't spam writes for accounts with reminders off.
  try{
    const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
    if(AppState.notifSettings.enabled && AppState.notifSettings.timeZone!==tz){ AppState.notifSettings.timeZone=tz; saveNotifSettings(); }
  }catch(e){}
  AppState.catBackfillDone = !!(fData && fData.catBackfillDone);
  AppState.catLegacyMerged = !!(fData && fData.catLegacyMerged);
  return seeded;
}

function backfillCategories(){
  if(AppState.catLegacyMerged) return false;
  const hasData = Object.keys(AppState.shifts).length>0 || AppState.transactions.length>0 || (AppState.debts&&AppState.debts.length>0);
  let changed=false;
  const add=(type,name)=>{
    const c=(name||'').trim();
    if(!c || c==='Внутрішній переказ') return;
    if(!AppState.categories[type]) AppState.categories[type]=[];
    if(!AppState.categories[type].includes(c)){ AppState.categories[type].push(c); changed=true; }
  };
  if(hasData){
    LEGACY_CATEGORIES.income.forEach(c=>add('income',c));
    LEGACY_CATEGORIES.expense.forEach(c=>add('expense',c));
  }
  AppState.transactions.forEach(t=>{ if(t.type==='income'||t.type==='expense') add(t.type, t.category); });
  AppState.catLegacyMerged=true; AppState.catBackfillDone=true;
  return changed;
}

export async function fbLoadNow(){
  if(!AppState.currentUser) return;
  fbSetStatus('loading',tr('sync_loading'));
  try{
    const [sS,fS,dS]=await Promise.all([getDoc(userDoc('shifts')),getDoc(userDoc('finance')),getDoc(userDoc('debt'))]);
    const sData=sS.exists()?sS.data():null;
    const fData=fS.exists()?fS.data():null;
    AppState.shifts=sData?(sData.data||{}):{};
    const sk=lsKey('shifts'); if(sk) localStorage.setItem(sk,JSON.stringify(AppState.shifts));
    AppState.autoFillSchedule=(sData&&sData.autoFillSchedule&&typeof sData.autoFillSchedule==='object')
      ? {enabled:!!sData.autoFillSchedule.enabled, typeId:sData.autoFillSchedule.typeId||'', pattern:sData.autoFillSchedule.pattern||'every', anchorDate:sData.autoFillSchedule.anchorDate||''}
      : {enabled:false, typeId:'', pattern:'every', anchorDate:''};
    AppState.transactions=fData?(fData.data||[]):[];
    const tk=lsKey('tx'); if(tk) localStorage.setItem(tk,JSON.stringify(AppState.transactions));
    AppState.recurring=fData?(fData.recurring||[]):[];
    saveRecurringLocal();
    AppState.shoppingList=fData?(fData.shoppingList||[]):[];
    saveShoppingLocal();
    if(dS.exists()){
      const norm=normalizeDebtData(dS.data().data);
      AppState.debts=norm?norm.debts:[]; AppState.currentDebtId=norm?norm.currentDebtId:null;
    }else{
      AppState.debts=[]; AppState.currentDebtId=null;
    }
    saveDebtLocal();
    const seeded=seedConfigFromDocs(sData, fData);
    const backfilled=backfillCategories();
    saveConfigLocal();
    const recurAdded=processRecurring();
    const autoFillAdded=processAutoFillShifts();
    AppState.lastKnownUpdatedAt={
      shifts:  sS.exists()?(sS.data().updatedAt||0):0,
      finance: fS.exists()?(fS.data().updatedAt||0):0,
      debt:    dS.exists()?(dS.data().updatedAt||0):0,
    };
    fbSetStatus('ok',tr('sync_synced'));
    renderCalendar(); renderFinance(); renderIncomeChart(); renderFinanceChart(); renderDebt();
    // Sync itself stays silent — only surfaced to the user when something
    // actually needs their attention (a conflict, or being offline below).
    if(recurAdded) showToast(`${tr('sync_recur_added')} ${recurAdded} ${tr('sync_recur_suffix')}`,'repeat');
    if(autoFillAdded) showToast(`${tr('shifts_autofill_added')} ${autoFillAdded}`,'bolt');
    // Persist newly-seeded config, keeping a one-time raw backup first so
    // the original docs can always be recovered if anything looks wrong.
    if(seeded){
      try{
        await setDoc(userDoc('backup_v2'), {
          shifts:sData||null, finance:fData||null,
          debt:dS.exists()?dS.data():null, at:Date.now()
        }, {merge:false});
      }catch(be){ console.error('backup failed', be); }
    }
    if(seeded||backfilled||recurAdded||autoFillAdded) await fbSaveNow();
  }catch(e){
    console.error(e);
    fbSetStatus('error',tr('sync_offline'));
    showToast(tr('sync_cloud_unavailable'),'offline');
  }
}

export function scheduleSave(){
  fbSetStatus('loading',tr('sync_autosave'));
  clearTimeout(AppState.fbTimer);
  AppState.fbTimer=setTimeout(fbSaveNow,1800);
}

export function saveLocal(){
  const k=lsKey('shifts'); if(k) localStorage.setItem(k,JSON.stringify(AppState.shifts));
}

export function saveDebtLocal(){
  const k=lsKey('debt'); if(k) localStorage.setItem(k, JSON.stringify({debts: AppState.debts, currentDebtId: AppState.currentDebtId}));
}

export function saveRecurringLocal(){
  const k=lsKey('recurring'); if(k) localStorage.setItem(k, JSON.stringify(AppState.recurring));
}

export function saveShoppingLocal(){
  const k=lsKey('shopping'); if(k) localStorage.setItem(k, JSON.stringify(AppState.shoppingList));
}

function computeNextDate(dateStr, freq){
  const d=new Date(dateStr+'T00:00:00');
  if(freq==='daily') d.setDate(d.getDate()+1);
  else if(freq==='weekly') d.setDate(d.getDate()+7);
  else d.setMonth(d.getMonth()+1); // monthly (default)
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

function processRecurring(){
  if(!AppState.recurring.length) return 0;
  const todayStr=new Date().toISOString().split('T')[0];
  let added=0;
  AppState.recurring.forEach(r=>{
    if(r.active===false || !r.nextDate || !r.amount) return;
    let guard=0;
    while(r.nextDate<=todayStr && guard<24){
      AppState.transactions.unshift({
        id:Date.now()+added, type:r.type, amount:r.amount, currency:walletCurrency(r.wallet), category:r.category||'Інше',
        wallet:r.wallet, targetWallet:null, targetAmount:null, targetCurrency:null, date:r.nextDate,
        comment:(r.comment?r.comment+' · ':'')+tr('recurring_comment_tag')
      });
      r.nextDate=computeNextDate(r.nextDate, r.frequency||'monthly');
      added++; guard++;
    }
  });
  if(added){
    const tk=lsKey('tx'); if(tk) localStorage.setItem(tk,JSON.stringify(AppState.transactions));
    saveRecurringLocal();
  }
  return added;
}

export function saveConfigLocal(){
  const k=lsKey('cfg'); if(k) localStorage.setItem(k, JSON.stringify({shiftTypes: AppState.shiftTypes, autoFillSchedule: AppState.autoFillSchedule, wallets: AppState.wallets, categories: AppState.categories, budgets: AppState.budgets, subcategories: AppState.subcategories, currencyRates: AppState.currencyRates, tags: AppState.tags, autoRules: AppState.autoRules, goals: AppState.goals, profile: AppState.profile, subscription: AppState.subscription, widgets: AppState.widgets, widgetOrder: AppState.widgetOrder, catBackfillDone: AppState.catBackfillDone, catLegacyMerged: AppState.catLegacyMerged}));
}

const scrollToSection = function(id){
  document.getElementById(id)?.scrollIntoView({behavior:'smooth', block:'start'});
};

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_color_picker__(){
window.openColorPicker = openColorPicker;
window.selectPickedColor = selectPickedColor;
window.addProfile = addProfile;
window.renameProfile = renameProfile;
window.openProfileAvatarPicker = openProfileAvatarPicker;
window.selectProfileAvatar = selectProfileAvatar;
window.deleteProfile = deleteProfile;
window.switchProfile = switchProfile;
window.renderProfilesUI=renderProfilesUI;
window.scrollToSection = scrollToSection;
window.openModal=openModal;
window.closeModal=closeModal;
window.saveModalSelection=saveModalSelection;
window.validateModalSelection=validateModalSelection;
window.applyTemplate=applyTemplate;
window.clearCurrentMonth=clearCurrentMonth;
window.renderCalendar=renderCalendar;
window.setFinanceType=setFinanceType;
window.addTransaction=addTransaction;
window.deleteTransaction=deleteTransaction;
window.setTxFilter=setTxFilter;
window.shiftMonth=shiftMonth;
window.goToday=goToday;
window.updateDebtInfo=updateDebtInfo;
window.addDebtEntry=addDebtEntry;
window.updateDebtEntry=updateDebtEntry;
window.deleteDebtEntry=deleteDebtEntry;
window.deleteCurrentDebt=deleteCurrentDebt;
}
