// ── CORE ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState, LANG_CALENDAR, WIDGET_ORDER_DEFAULT } from './state.js';
import { renderFinance } from './analytics-csv.js';
import { renderCalendar, renderFinanceChart, renderIncomeChart } from './calendar.js';
import { renderDebt } from './debt.js';
import { updateAmountLabel } from './finance.js';
import { renderGoals, renderProfileUI } from './goals-profile.js';
import { renderNotifUI } from './notifications.js';
import { csSync } from './ui-widgets.js';

import { initializeApp } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js";

import { getFirestore, doc, getDoc, setDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js";

import {
  getAuth, onAuthStateChanged, signOut, deleteUser,
  createUserWithEmailAndPassword, signInWithEmailAndPassword,
  GoogleAuthProvider, signInWithPopup, sendPasswordResetEmail,
  EmailAuthProvider, reauthenticateWithCredential, reauthenticateWithPopup,
  RecaptchaVerifier, signInWithPhoneNumber, linkWithPhoneNumber, unlink
} from "https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js";

import { getMessaging, getToken, deleteToken, onMessage, isSupported as isMessagingSupported } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-messaging.js";

export const fbApp = initializeApp({
  apiKey:"AIzaSyBjtcCiXKKZ9TH3Ubrn65IX59kyCe9C-H4",
  authDomain:"maxtr-c238f.firebaseapp.com",
  projectId:"maxtr-c238f",
  storageBucket:"maxtr-c238f.firebasestorage.app",
  messagingSenderId:"311094677098",
  appId:"1:311094677098:web:7a3797c99fad2874340413"
});

export const db = getFirestore(fbApp);

export const auth = getAuth(fbApp);

export const googleProvider = new GoogleAuthProvider();

export const DCOL = 'max_tracker';

export const VAPID_KEY = 'BBcPaLYW4stwLwTHX-2mNXmu86eQeqw1biQXPGv4-FLOZWbUl8BAVgeHxGC2vvlLXkYqOUCyoo8NqnN6n8Usbtw';

const ERROR_LOG_MAX = 20;

function errorLogKey(){ return AppState.currentUser ? `mx_errlog_${AppState.currentUser.uid}` : 'mx_errlog_anon'; }

function currentTabName(){
  const el = document.querySelector('#nav-shifts.active, #nav-finance.active, #nav-debt.active, #nav-shopping.active, #nav-settings.active');
  return el ? el.id.replace('nav-','') : null;
}

function logAppError(kind, detail){
  const entry = { kind, at: new Date().toISOString(), tab: currentTabName(), ...detail };
  console.error(`[Zminka:${kind}]`, entry);
  try{
    const key = errorLogKey();
    const list = JSON.parse(localStorage.getItem(key) || '[]');
    list.push(entry);
    while(list.length > ERROR_LOG_MAX) list.shift();
    localStorage.setItem(key, JSON.stringify(list));
  }catch(e){}
}

export const SALARY_GOAL = 20000;

export function subKey(type,name){ return type+':'+name; }

// rates/converter/analytics moved into #tools-modal (see CLAUDE.md's
// Finance-tab-widgets section) — no longer part of the toggleable
// show/hide+reorder set, so only chart/goals remain here.
const WIDGET_SECTION_IDS={chart:'finance-chart-section', goals:'goals-section'};

export function sanitizeWidgetOrder(arr){
  const seen=new Set();
  const out=(Array.isArray(arr)?arr:[]).filter(k=>WIDGET_ORDER_DEFAULT.includes(k)&&!seen.has(k)&&seen.add(k));
  WIDGET_ORDER_DEFAULT.forEach(k=>{ if(!seen.has(k)){ out.push(k); seen.add(k); } });
  return out;
}

export function applyWidgetVisibility(){
  Object.entries(WIDGET_SECTION_IDS).forEach(([key,id])=>{
    if(key==='goals') return; // goals additionally self-hides when empty — handled inside renderGoals()
    const el=document.getElementById(id);
    if(el) el.style.display = AppState.widgets[key]===false ? 'none' : '';
  });
  renderGoals();
  applyWidgetOrder();
}

export function applyWidgetOrder(){
  const anchor=document.getElementById('budgets-section');
  if(!anchor||!anchor.parentNode) return;
  AppState.widgetOrder.forEach(key=>{
    const el=document.getElementById(WIDGET_SECTION_IDS[key]);
    if(el) anchor.parentNode.insertBefore(el, anchor);
  });
}

const FREE_LIMITS = {wallets:3, categoriesPerType:8, autoRules:3, recurring:3, goals:1};

function isPremium(){ return AppState.subscription.plan==='premium' && (!AppState.subscription.expiresAt || AppState.subscription.expiresAt>Date.now()); }

function canAddMore(kind, currentCount){ return isPremium() || currentCount < FREE_LIMITS[kind]; }

export function renderPremiumUI(){
  const sub=document.getElementById('settings-premium-sub');
  if(sub) sub.textContent = isPremium() ? tr('premium_active_plan') : tr('premium_free_plan');
}

const PREMIUM_LIMIT_MSG_KEYS={wallets:'premium_limit_wallets', categoriesPerType:'premium_limit_categories', autoRules:'premium_limit_rules', recurring:'premium_limit_recurring', goals:'premium_limit_goals'};

const showPremiumUpsell = function(limitKind){
  const msgEl=document.getElementById('premium-modal-limit-msg');
  if(msgEl) msgEl.textContent = limitKind ? tr(PREMIUM_LIMIT_MSG_KEYS[limitKind]) : tr('premium_subtitle');
  document.getElementById('premium-modal').style.display='flex';
};

export const DEBT_COLORS = ['#8b5cf6','#10b981','#3b82f6','#f59e0b','#ec4899','#06b6d4'];

export const PALETTE = ['#8b5cf6','#3b82f6','#10b981','#f59e0b','#ec4899','#06b6d4','#ef4444','#a78bfa'];

export function categoryColor(name){
  const s=String(name||'');
  let h=0;
  for(let i=0;i<s.length;i++) h=(h*31+s.charCodeAt(i))>>>0;
  return PALETTE[h%PALETTE.length];
}

function populateMonthSelectLabels(){
  const ms=document.getElementById('select-month');
  if(!ms) return;
  Array.from(ms.options).forEach(o=>{ o.textContent=AppState.MONTHS[Number(o.value)]; });
  csSync(ms);
}

const __applyLangDynamic = function(lang){
  AppState.MONTHS=LANG_CALENDAR[lang].months;
  AppState.MONTHS_SHORT=LANG_CALENDAR[lang].monthsShort;
  AppState.WEEKDAYS=LANG_CALENDAR[lang].weekdays;
  populateMonthSelectLabels();
  renderCalendar(); renderIncomeChart(); renderFinance(); renderFinanceChart(); renderDebt();
  renderProfileUI(); renderPremiumUI(); renderNotifUI(); updateAmountLabel();
  const wsl=document.getElementById('wallet-source-label');
  if(wsl){
    const key={income:'finance_wallet',expense:'finance_wallet_expense',transfer:'finance_wallet_transfer'}[AppState.currentFinanceType];
    if(key) wsl.textContent=tr(key);
  }
};

const CAT_ICON = {
  'Зарплата':'briefcase','Аванс':'card','Підробіток':'gift','Повернення боргу':'coin','Інше':'box',
  'Кава':'coffee','Кафе':'coffee','Фастфуд':'burger','Розваги':'gift',
  'Кредит':'bank','Борг':'coin','Продукти':'cart','Транспорт':'car','Комуналка':'house','Покупки':'bag',
  'Здоров\'я':'coin','Аптека':'coin','Цигарки':'cigarette','Внутрішній переказ':'swap',
};

// 'umbrella' deliberately excluded — it's used elsewhere for vacation/day-off
// (setIcon('ic-vacation','umbrella')), which reads fine there, but as a
// random fallback for an arbitrary category name (e.g. a bank fee category
// hashing onto it) it looks nonsensical with no thematic connection.
const CAT_ICON_FALLBACK_POOL = ['tag','person','star','flag','bell','globe','camera','box','gift'];

export function categoryIcon(name){
  if(CAT_ICON[name]) return CAT_ICON[name];
  const s=String(name||'');
  let h=0;
  for(let i=0;i<s.length;i++) h=(h*31+s.charCodeAt(i))>>>0;
  return CAT_ICON_FALLBACK_POOL[h%CAT_ICON_FALLBACK_POOL.length];
}

export const LEGACY_SHIFT_TYPES = [
  {id:'day',         name:'Денна зміна',          short:'День', color:'#3b82f6', amount:1000, hours:12},
  {id:'day1900',     name:'Денна (підвищена)',    short:'День+',color:'#10b981', amount:1900, hours:12},
  {id:'night',       name:'Нічна повна',          short:'Ніч',  color:'#8b5cf6', amount:900,  hours:12},
  {id:'night_half1', name:'Ніч рання',            short:'НічР', color:'#ec4899', amount:450,  hours:6},
  {id:'night_half2', name:'Ніч пізня',            short:'НічП', color:'#06b6d4', amount:450,  hours:6},
  {id:'vacation',    name:'Вихідний',             short:'Вих',  color:'#f59e0b', amount:0,    hours:0, isOff:true},
];

export const LEGACY_WALLETS = [
  {id:'main',name:'Основна картка',color:'#8b5cf6',icon:'card',currency:'UAH'},
  {id:'pumb',name:'Картка ПУМБ',   color:'#ef4444',icon:'card',currency:'UAH'},
  {id:'cash',name:'Готівка',        color:'#f59e0b',icon:'banknote',currency:'UAH'},
];

export const DEFAULT_SHIFT_TYPES = [
  {id:'st_day',   name:'Денна зміна', short:'День', color:'#3b82f6', amount:0, hours:8},
  {id:'st_night', name:'Нічна зміна', short:'Ніч',  color:'#8b5cf6', amount:0, hours:12},
  {id:'st_off',   name:'Вихідний',    short:'Вих',  color:'#f59e0b', amount:0, hours:0, isOff:true},
];

export const DEFAULT_WALLETS = [
  {id:'w_card',name:'Картка', color:'#8b5cf6',icon:'card',currency:'UAH'},
  {id:'w_cash',name:'Готівка',color:'#f59e0b',icon:'banknote',currency:'UAH'},
];

export const CURRENCY_LIST=['UAH','USD','EUR','GBP','PLN'];

const CURRENCY_META={
  UAH:{symbol:'грн'}, USD:{symbol:'$'}, EUR:{symbol:'€'}, GBP:{symbol:'£'}, PLN:{symbol:'zł'},
};

export const SEED_RATES={USD:41, EUR:44, GBP:51, PLN:10.5};

export function currencySymbol(code){ return (CURRENCY_META[code]||{}).symbol || code || 'грн'; }

export function convertCurrency(amount, fromCode, toCode){
  if(fromCode===toCode) return amount;
  const fromRate=AppState.currencyRates[fromCode] ?? SEED_RATES[fromCode] ?? 1;
  const toRate=AppState.currencyRates[toCode] ?? SEED_RATES[toCode] ?? 1;
  return Math.round((amount*fromRate/toRate)*100)/100;
}

export function toBase(amount, code){ return convertCurrency(amount, code||'UAH', 'UAH'); }

export function walletCurrency(id){ return (walletById(id)||{}).currency||'UAH'; }

export function normalizeWallets(){
  AppState.wallets.forEach(w=>{ if(!w.currency) w.currency='UAH'; });
}

export const DEFAULT_CATEGORIES = {
  income:  ['Зарплата','Аванс','Підробіток','Інше'],
  expense: ['Продукти','Кафе','Транспорт','Покупки','Комуналка','Здоров\'я','Розваги','Інше'],
};

export const LEGACY_CATEGORIES = {
  income:  ['Зарплата','Аванс','Підробіток','Повернення боргу','Інше'],
  expense: ['Алла','Син','Цигарки','Кава','Фастфуд','Борг','Кредит','Продукти','Транспорт','Комуналка','Покупки','Інше'],
};

export function shiftType(id){ return AppState.shiftTypes.find(t=>t.id===id); }

export function walletById(id){ return AppState.wallets.find(w=>w.id===id); }

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_core__(){
window.addEventListener('error', e=>{
  logAppError('uncaught-error', { message: e.message, source: e.filename, line: e.lineno, col: e.colno, stack: e.error && e.error.stack });
});
window.addEventListener('unhandledrejection', e=>{
  const reason = e.reason;
  logAppError('unhandled-rejection', { message: reason && reason.message || String(reason), stack: reason && reason.stack });
});
// Surfaces Content-Security-Policy-Report-Only violations (see
// firebase.json) into the same local error log, since this app has no
// backend to send CSP reports to — lets the account owner check
// localStorage (or a future Settings-tab viewer) for anything the policy
// missed before it ever gets flipped from report-only to enforcing.
document.addEventListener('securitypolicyviolation', e=>{
  logAppError('csp-violation', { message: `${e.violatedDirective} blocked ${e.blockedURI}`, source: e.sourceFile, line: e.lineNumber, col: e.columnNumber });
});
// window.__applyLangDynamic deliberately kept — it's the one hook back
// from the inline classic script's setLang() (genuinely outside the js/
// module graph, see CLAUDE.md's "index.html script structure"), not an
// onclick attribute, so it's out of scope for this audit item.
window.__applyLangDynamic = __applyLangDynamic;
// Phase 13 of the window.*/inline-onclick removal audit item (see
// CLAUDE.md): this file's one static onclick="" site in index.html
// (the premium-upsell settings row) converted to a data-action dispatch.
// window.getErrorLog was dropped outright — grepped every call site
// across index.html/js/*.js and found zero, dead since whenever this
// file was split out.
const CLICK_ACTIONS = {
  'show-premium-upsell': ()=>showPremiumUpsell(),
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);
}

// Re-exports of this file's own imported (not locally declared) bindings
// that other split files also need - can't prefix an ImportDeclaration
// with `export`, so these are re-exported explicitly instead.
export { EmailAuthProvider, RecaptchaVerifier, createUserWithEmailAndPassword, deleteDoc, deleteToken, deleteUser, doc, getDoc, getMessaging, getToken, isMessagingSupported, linkWithPhoneNumber, onAuthStateChanged, onMessage, reauthenticateWithCredential, reauthenticateWithPopup, sendPasswordResetEmail, setDoc, signInWithEmailAndPassword, signInWithPhoneNumber, signInWithPopup, signOut, unlink };
