// ── DEBT ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { saveDebtLocal, scheduleSave } from './color-picker.js';
import { DEBT_COLORS } from './core.js';
import { emptyStateHtml, escapeHtml, showToast, uiConfirm, uiPrompt } from './ui-widgets.js';

function getCurrentDebt(){
  return AppState.debts.find(d=>d.id===AppState.currentDebtId)||AppState.debts[0];
}

function switchDebt(id){
  AppState.currentDebtId=id;
  saveDebtLocal(); renderDebt();
}

async function addNewDebt(){
  const name=await uiPrompt(tr('debt_add_prompt'),'',tr('debt_new_default'));
  if(name===null) return;
  const nd={id:Date.now(), name:name.trim()||tr('debt_new_default'), note:'', currency:'грн', startAmount:0, entries:[]};
  AppState.debts.push(nd);
  AppState.currentDebtId=nd.id;
  saveDebtLocal(); scheduleSave(); renderDebt();
  showToast(tr('debt_added'),'check');
}

export async function deleteCurrentDebt(){
  if(AppState.debts.length<=1){showToast(tr('debt_need_one'),'xmark');return;}
  if(!(await uiConfirm(tr('debt_delete_confirm'),{title:tr('debt_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.debts=AppState.debts.filter(d=>d.id!==AppState.currentDebtId);
  AppState.currentDebtId=AppState.debts[0].id;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

export function updateDebtInfo(){
  const cd=getCurrentDebt(); if(!cd) return;
  const ni=document.getElementById('debt-name');
  const noi=document.getElementById('debt-note');
  const ci=document.getElementById('debt-currency');
  const si=document.getElementById('debt-start');
  cd.name=ni?.value.trim()||tr('debt_default_name');
  cd.note=noi?.value.trim()||'';
  cd.currency=ci?.value||'у.о.';
  cd.startAmount=parseFloat(si?.value)||0;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

function debtCurrentBalance(cd){
  return cd.entries.length?cd.entries[cd.entries.length-1].balance:(cd.startAmount||0);
}

function todayLabel(){
  const d=new Date();
  return `${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}.${d.getFullYear()}`;
}

const autoFillDebtBalance = function(){
  const cd=getCurrentDebt(); if(!cd) return;
  const ai=document.getElementById('debt-amount');
  const bi=document.getElementById('debt-balance-input');
  if(!ai||!bi) return;
  const raw=ai.value.trim();
  if(/^\d+(\.\d+)?$/.test(raw)){
    bi.value=Math.round((debtCurrentBalance(cd)-parseFloat(raw))*100)/100;
  }else if(!raw){
    bi.value='';
  }
};

export function addDebtEntry(){
  const cd=getCurrentDebt(); if(!cd) return;
  const ai=document.getElementById('debt-amount');
  const bi=document.getElementById('debt-balance-input');
  const di=document.getElementById('debt-date');
  const amount=ai?.value.trim();
  if(!amount){showToast(tr('debt_enter_amount'),'xmark');return;}
  let balance=parseFloat(bi?.value);
  if(isNaN(balance)){
    // auto-compute from the running balance when the amount is a plain number
    if(/^\d+(\.\d+)?$/.test(amount)) balance=debtCurrentBalance(cd)-parseFloat(amount);
    else {showToast(tr('debt_enter_balance'),'xmark');return;}
  }
  const date=(di?.value.trim())||todayLabel();
  cd.entries.push({id:Date.now(),amount,balance,date});
  saveDebtLocal(); scheduleSave();
  if(ai)ai.value=''; if(bi)bi.value=''; if(di)di.value=todayLabel();
  renderDebt();
  closeDebtEntryModal();
  showToast(tr('debt_payment_added'),'check');
}

const openNewDebtEntryModal = function(){
  const m=document.getElementById('debt-form-modal'); if(m) m.style.display='flex';
  document.getElementById('debt-amount')?.focus();
};

const closeDebtEntryModal = function(){
  const m=document.getElementById('debt-form-modal'); if(m) m.style.display='none';
};

export function updateDebtEntry(id,field,value){
  const cd=getCurrentDebt(); if(!cd) return;
  const e=cd.entries.find(x=>x.id===id);
  if(!e) return;
  e[field]=field==='balance'?(parseFloat(value)||0):value;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

export async function deleteDebtEntry(id){
  const cd=getCurrentDebt(); if(!cd) return;
  if(!(await uiConfirm(tr('debt_delete_payment_confirm'),{title:tr('debt_delete_payment_title'),okText:tr('common_delete'),danger:true}))) return;
  cd.entries=cd.entries.filter(x=>x.id!==id);
  if(AppState.debtEntryEditId===id) AppState.debtEntryEditId=null;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

const toggleDebtEntryEdit = function(id){
  AppState.debtEntryEditId = (AppState.debtEntryEditId===id) ? null : id;
  renderDebt();
};

const toggleDebtInfoPanel = function(){
  const body=document.getElementById('debt-info-body');
  const chev=document.getElementById('debt-info-chevron');
  if(!body) return;
  const opening = body.style.display==='none';
  body.style.display = opening ? 'flex' : 'none';
  if(chev) chev.style.transform = opening ? 'rotate(180deg)' : '';
};

const toggleDebtHistoryPanel = function(){
  const body=document.getElementById('debt-list-container');
  const chev=document.getElementById('debt-history-chevron');
  if(!body) return;
  const opening = body.style.display==='none';
  body.style.display = opening ? 'flex' : 'none';
  if(chev) chev.style.transform = opening ? 'rotate(180deg)' : '';
};

function renderDebtChips(){
  const c=document.getElementById('debt-chips');
  if(!c) return;
  c.innerHTML='';
  AppState.debts.forEach((d,i)=>{
    const chip=document.createElement('button');
    chip.className='debt-chip'+(d.id===AppState.currentDebtId?' active':'');
    chip.style.setProperty('--chip-color', DEBT_COLORS[i%DEBT_COLORS.length]);
    chip.textContent=d.name||tr('debt_default_name');
    chip.onclick=()=>switchDebt(d.id);
    c.appendChild(chip);
  });
  const addChip=document.createElement('button');
  // An icon-only circle reads as decoration, not a button — always show the
  // label rather than relying on a hover title (which doesn't even fire on
  // touch), matching the "+ Додати гаманець" convention used everywhere else.
  addChip.className='debt-chip debt-chip-add debt-chip-add-labeled';
  addChip.innerHTML=`${window.Icon('plus')}<span>${tr('debt_new_default')}</span>`;
  addChip.onclick=addNewDebt;
  c.appendChild(addChip);
}

export function renderDebt(){
  renderDebtChips();
  const cd=getCurrentDebt();
  if(!cd){
    // No debts in this profile — clear out whatever the previous profile's
    // renderDebt() left on screen instead of leaving it stale.
    const ni=document.getElementById('debt-name'); if(ni) ni.value='';
    const noi=document.getElementById('debt-note'); if(noi) noi.value='';
    const ci=document.getElementById('debt-currency'); if(ci) ci.value='у.о.';
    const si=document.getElementById('debt-start'); if(si) si.value='';
    const S=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};
    S('debt-start-val','0'); S('debt-balance-val','0'); S('debt-paid-val','0'); S('debt-count-val','0');
    const lc=document.getElementById('debt-list-container');
    const cc=document.getElementById('debt-entry-count');
    if(cc) cc.textContent='';
    if(lc) lc.innerHTML=emptyStateHtml({
      icon:'bank',
      title:tr('debt_empty_no_calc_title'),
      desc:tr('debt_empty_no_calc_desc'),
      action:tr('debt_add_calc'),
      onClick:'addNewDebt()'
    });
    return;
  }
  const cur=cd.currency||'у.о.';

  const ni=document.getElementById('debt-name'); if(ni) ni.value=cd.name||'';
  const noi=document.getElementById('debt-note'); if(noi) noi.value=cd.note||'';
  const ci=document.getElementById('debt-currency'); if(ci) ci.value=cur;
  const si=document.getElementById('debt-start'); if(si) si.value=cd.startAmount||0;
  // Prefill today's date for the next payment if the field is empty
  const ddi=document.getElementById('debt-date'); if(ddi&&!ddi.value) ddi.value=todayLabel();

  const currentBalance=cd.entries.length?cd.entries[cd.entries.length-1].balance:(cd.startAmount||0);
  const paid=(cd.startAmount||0)-currentBalance;
  const S=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};
  S('debt-start-val',(cd.startAmount||0).toLocaleString('uk-UA')+' '+cur);
  S('debt-balance-val',currentBalance.toLocaleString('uk-UA')+' '+cur);
  S('debt-paid-val',paid.toLocaleString('uk-UA')+' '+cur);
  S('debt-count-val',cd.entries.length);

  const lc=document.getElementById('debt-list-container');
  const cc=document.getElementById('debt-entry-count');
  if(!lc) return;
  if(cc) cc.textContent=cd.entries.length+' '+tr('finance_records_suffix');
  lc.innerHTML='';

  if(cd.entries.length===0){
    lc.innerHTML=emptyStateHtml({
      icon:'coin',
      title:tr('debt_empty_title'),
      desc:tr('debt_empty_desc'),
      action:tr('debt_add_payment'),
      onClick:'openNewDebtEntryModal()'
    });
    return;
  }

  let prevBalance=cd.startAmount||0;
  cd.entries.forEach(entry=>{
    const isCleanNumber=/^\d+(\.\d+)?$/.test(String(entry.amount).trim());
    const expected=isCleanNumber?prevBalance-parseFloat(entry.amount):null;
    const hasDiscrepancy=expected!==null&&Math.abs(expected-entry.balance)>0.01;
    const row=document.createElement('div');
    const editing=AppState.debtEntryEditId===entry.id;
    row.className='debt-row'+(hasDiscrepancy?' discrepancy':'');
    const fieldsHtml = editing ? `
      <div class="debt-field"><span class="debt-field-label">${tr('debt_amount')}</span><input type="text" value="${escapeHtml(entry.amount??'')}" data-action="update-debt-entry" data-id="${entry.id}" data-field="amount"></div>
      <div class="debt-field"><span class="debt-field-label">${tr('debt_stat_balance')}</span><input type="number" step="0.01" value="${entry.balance??''}" data-action="update-debt-entry" data-id="${entry.id}" data-field="balance"></div>
      <div class="debt-field"><span class="debt-field-label">${tr('finance_date')}</span><input type="text" value="${escapeHtml(entry.date??'')}" data-action="update-debt-entry" data-id="${entry.id}" data-field="date"></div>
      <button class="debt-row-edit debt-row-edit-active" data-action="toggle-debt-entry-edit" data-id="${entry.id}" aria-label="${tr('a11y_confirm')}">${window.Icon('check')}</button>
    ` : `
      <div class="debt-field"><span class="debt-field-label">${tr('debt_amount')}</span><div class="debt-field-view">${escapeHtml(entry.amount??'')}</div></div>
      <div class="debt-field"><span class="debt-field-label">${tr('debt_stat_balance')}</span><div class="debt-field-view">${(entry.balance??0).toLocaleString('uk-UA')}</div></div>
      <div class="debt-field"><span class="debt-field-label">${tr('finance_date')}</span><div class="debt-field-view">${escapeHtml(entry.date??'')}</div></div>
      <button class="debt-row-edit" data-action="toggle-debt-entry-edit" data-id="${entry.id}" aria-label="${tr('common_edit')}">${window.Icon('pencil')}</button>
    `;
    row.innerHTML=`
      ${fieldsHtml}
      <button class="debt-row-del" data-action="delete-debt-entry" data-id="${entry.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
      ${hasDiscrepancy?`<div class="debt-hint">${tr('debt_expected')} ${expected.toLocaleString('uk-UA')} ${cur} — ${tr('debt_discrepancy')} ${(entry.balance-expected).toLocaleString('uk-UA')} ${cur}</div>`:''}
    `;
    lc.appendChild(row);
    prevBalance=entry.balance;
  });
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_debt__(){
// Phase 8 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// converts this file's own 6 dynamic onclick/onchange sites (debt-entry
// edit/delete/fields) plus 8 static index.html ones (new-debt-entry FAB,
// info/history panel toggles, debt-info fields, add-payment, delete-debt)
// to data-action, same pattern as phases 3-7. Also folds in 5 window.*
// assignments that were exports of THIS file's own functions
// (updateDebtInfo/addDebtEntry/deleteCurrentDebt/updateDebtEntry/
// deleteDebtEntry) but physically lived in js/color-picker.js's
// __init_color_picker__ — a leftover of the original mechanical split
// phase 4 deliberately left alone (see that entry in CLAUDE.md); now that
// this file is the one being worked, those 5 lines move here and get the
// same data-action treatment instead of staying as dead weight in a
// different file's init function.
const CLICK_ACTIONS = {
  'open-new-debt-entry-modal': ()=>openNewDebtEntryModal(),
  'toggle-debt-info-panel': ()=>toggleDebtInfoPanel(),
  'toggle-debt-history-panel': ()=>toggleDebtHistoryPanel(),
  'toggle-debt-entry-edit': ds=>toggleDebtEntryEdit(Number(ds.id)),
  'delete-debt-entry': ds=>deleteDebtEntry(Number(ds.id)),
  'add-debt-entry': ()=>addDebtEntry(),
  'delete-current-debt': ()=>deleteCurrentDebt(),
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);

const FIELD_ACTIONS = {
  'auto-fill-debt-balance': ()=>autoFillDebtBalance(),
  'update-debt-info': ()=>updateDebtInfo(),
  'update-debt-entry': (ds,el)=>updateDebtEntry(Number(ds.id), ds.field, el.value),
};
function dispatchFieldAction(e){
  const el=e.target.closest('[data-action]');
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el);
}
document.addEventListener('change', dispatchFieldAction);
document.addEventListener('input', dispatchFieldAction);

// Still window-exposed: renderDebt()'s own emptyStateHtml({onClick:'...'})
// calls (ui-widgets.js's shared empty-state helper bakes onClick straight
// into a literal onclick="" attribute string, not a data-action) reference
// both by name for the "no debts yet"/"no payments yet" empty states.
// Converting emptyStateHtml itself to data-action would touch every file
// that calls it (shopping.js, analytics-csv.js's onboarding checklist,
// etc.), out of scope for this single-file phase.
window.addNewDebt=addNewDebt;
window.openNewDebtEntryModal = openNewDebtEntryModal;
}
