// @ts-check
// ── DEBT ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { saveDebtLocal, scheduleSave } from './color-picker.js';
import { DEBT_COLORS, canEditActiveProfile } from './core.js';
import { emptyStateHtml, escapeHtml, showToast, uiConfirm, uiPrompt } from './ui-widgets.js';
// Vendored (not an npm import) so this resolves identically whether
// js/debt.js is served unbundled (GitHub Pages, a bare 'preact' package
// specifier isn't a valid URL there) or bundled by Vite (dist/, Firebase
// Hosting) — same reasoning as js/vendor/tesseract/ in js/receipt-ocr.js,
// see CLAUDE.md's "Preact adoption" note. Preact-based rendering is used
// only for the payoff-forecast widget below, a proof of concept.
import { h as _h, render, Fragment } from './vendor/preact/preact.module.js';
// See js/analytics-csv.js's identical comment for why this re-declaration
// is needed (TypeScript infers h()'s signature from the vendored file's
// own minified implementation rather than the real `preact` package's
// richer .d.ts, installed as a type-only devDependency - see
// types/preact-vendor.d.ts). Zero runtime difference.
/** @type {typeof import('preact').h} */
const h = /** @type {any} */ (_h);

function getCurrentDebt(){
  return AppState.debts.find(d=>d.id===AppState.currentDebtId)||AppState.debts[0];
}

function switchDebt(id){
  AppState.currentDebtId=id;
  saveDebtLocal(); renderDebt();
}

async function addNewDebt(){
  const name=await uiPrompt(tr('debt_add_prompt'),'',tr('debt_new_default'));
  if(name===null) return;
  const nd={id:Date.now(), name:name.trim()||tr('debt_new_default'), note:'', currency:'грн', startAmount:0, dueDate:'', entries:[]};
  AppState.debts.push(nd);
  AppState.currentDebtId=nd.id;
  saveDebtLocal(); scheduleSave(); renderDebt();
  showToast(tr('debt_added'),'check');
}

/** @returns {Promise<void>} */
export async function deleteCurrentDebt(){
  if(AppState.debts.length<=1){showToast(tr('debt_need_one'),'xmark');return;}
  if(!(await uiConfirm(tr('debt_delete_confirm'),{title:tr('debt_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.debts=AppState.debts.filter(d=>d.id!==AppState.currentDebtId);
  AppState.currentDebtId=AppState.debts[0].id;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

/** @returns {void} */
export function updateDebtInfo(){
  const cd=getCurrentDebt(); if(!cd) return;
  const ni=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-name'));
  const noi=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-note'));
  const ci=/** @type {HTMLSelectElement | null} */ (document.getElementById('debt-currency'));
  const si=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-start'));
  const dui=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-due-date'));
  cd.name=ni?.value.trim()||tr('debt_default_name');
  cd.note=noi?.value.trim()||'';
  cd.currency=ci?.value||'у.о.';
  cd.startAmount=parseFloat(si?.value)||0;
  cd.dueDate=dui?.value||'';
  saveDebtLocal(); scheduleSave(); renderDebt();
}

function debtCurrentBalance(cd){
  return cd.entries.length?cd.entries[cd.entries.length-1].balance:(cd.startAmount||0);
}

function todayLabel(){
  const d=new Date();
  return `${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}.${d.getFullYear()}`;
}

const autoFillDebtBalance = function(){
  const cd=getCurrentDebt(); if(!cd) return;
  const ai=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-amount'));
  const bi=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-balance-input'));
  if(!ai||!bi) return;
  const raw=ai.value.trim();
  if(/^\d+(\.\d+)?$/.test(raw)){
    bi.value=String(Math.round((debtCurrentBalance(cd)-parseFloat(raw))*100)/100);
  }else if(!raw){
    bi.value='';
  }
};

/** @returns {void} */
export function addDebtEntry(){
  if(!canEditActiveProfile()){ showToast(tr('shared_profile_readonly'),'xmark'); return; }
  const cd=getCurrentDebt(); if(!cd) return;
  const ai=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-amount'));
  const bi=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-balance-input'));
  const di=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-date'));
  const amount=ai?.value.trim();
  if(!amount){showToast(tr('debt_enter_amount'),'xmark');return;}
  let balance=parseFloat(bi?.value);
  if(isNaN(balance)){
    // auto-compute from the running balance when the amount is a plain number
    if(/^\d+(\.\d+)?$/.test(amount)) balance=debtCurrentBalance(cd)-parseFloat(amount);
    else {showToast(tr('debt_enter_balance'),'xmark');return;}
  }
  const date=(di?.value.trim())||todayLabel();
  cd.entries.push({id:Date.now(),amount,balance,date});
  saveDebtLocal(); scheduleSave();
  if(ai)ai.value=''; if(bi)bi.value=''; if(di)di.value=todayLabel();
  renderDebt();
  closeDebtEntryModal();
  showToast(tr('debt_payment_added'),'check');
}

const openNewDebtEntryModal = function(){
  const m=document.getElementById('debt-form-modal'); if(m) m.style.display='flex';
  document.getElementById('debt-amount')?.focus();
};

const closeDebtEntryModal = function(){
  const m=document.getElementById('debt-form-modal'); if(m) m.style.display='none';
};

/**
 * @param {number} id
 * @param {string} field
 * @param {*} value
 */
export function updateDebtEntry(id,field,value){
  const cd=getCurrentDebt(); if(!cd) return;
  const e=cd.entries.find(x=>x.id===id);
  if(!e) return;
  e[field]=field==='balance'?(parseFloat(value)||0):value;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

/**
 * @param {number} id
 * @returns {Promise<void>}
 */
export async function deleteDebtEntry(id){
  if(!canEditActiveProfile()){ showToast(tr('shared_profile_readonly'),'xmark'); return; }
  const cd=getCurrentDebt(); if(!cd) return;
  if(!(await uiConfirm(tr('debt_delete_payment_confirm'),{title:tr('debt_delete_payment_title'),okText:tr('common_delete'),danger:true}))) return;
  cd.entries=cd.entries.filter(x=>x.id!==id);
  if(AppState.debtEntryEditId===id) AppState.debtEntryEditId=null;
  saveDebtLocal(); scheduleSave(); renderDebt();
}

const toggleDebtEntryEdit = function(id){
  AppState.debtEntryEditId = (AppState.debtEntryEditId===id) ? null : id;
  renderDebt();
};

const toggleDebtInfoPanel = function(){
  const body=document.getElementById('debt-info-body');
  const chev=document.getElementById('debt-info-chevron');
  if(!body) return;
  const opening = body.style.display==='none';
  body.style.display = opening ? 'flex' : 'none';
  if(chev) chev.style.transform = opening ? 'rotate(180deg)' : '';
};

const toggleDebtHistoryPanel = function(){
  const body=document.getElementById('debt-list-container');
  const chev=document.getElementById('debt-history-chevron');
  if(!body) return;
  const opening = body.style.display==='none';
  body.style.display = opening ? 'flex' : 'none';
  if(chev) chev.style.transform = opening ? 'rotate(180deg)' : '';
};

function renderDebtChips(){
  const c=document.getElementById('debt-chips');
  if(!c) return;
  c.innerHTML='';
  AppState.debts.forEach((d,i)=>{
    const chip=document.createElement('button');
    chip.className='debt-chip'+(d.id===AppState.currentDebtId?' active':'');
    chip.style.setProperty('--chip-color', DEBT_COLORS[i%DEBT_COLORS.length]);
    chip.textContent=d.name||tr('debt_default_name');
    chip.onclick=()=>switchDebt(d.id);
    c.appendChild(chip);
  });
  const addChip=document.createElement('button');
  // An icon-only circle reads as decoration, not a button — always show the
  // label rather than relying on a hover title (which doesn't even fire on
  // touch), matching the "+ Додати гаманець" convention used everywhere else.
  addChip.className='debt-chip debt-chip-add debt-chip-add-labeled';
  addChip.innerHTML=`${window.Icon('plus')}<span>${tr('debt_new_default')}</span>`;
  addChip.onclick=addNewDebt;
  c.appendChild(addChip);
}

/**
 * @param {string} iso
 * @returns {string}
 */
function formatDueDate(iso){
  const d=new Date(iso+'T00:00:00');
  if(isNaN(d.getTime())) return '';
  return `${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}.${d.getFullYear()}`;
}

// Shows/hides the "Термін сплати" chip based on whether the current debt has
// a dueDate set, and colors its icon amber/red as the date approaches or
// passes — the same value checkDebtAlerts() in js/notifications.js (and the
// server-side sweepProfile() in functions/lib/sweep.js) uses to decide when
// to actually fire a reminder, just rendered for the user to see at a
// glance rather than only ever surfacing as a push/local notification.
function renderDebtDueChip(cd){
  const chip=document.getElementById('debt-due-chip');
  const val=document.getElementById('debt-due-val');
  const icon=document.getElementById('ic-debt-due');
  if(!chip||!val) return;
  if(!cd.dueDate){ chip.style.display='none'; return; }
  chip.style.display='';
  const today=new Date(); today.setHours(0,0,0,0);
  const due=new Date(cd.dueDate+'T00:00:00');
  const diffDays=Math.round((due.getTime()-today.getTime())/86400000);
  let suffix;
  if(diffDays<0) suffix=tr('debt_due_overdue_days').replace('{n}',String(Math.abs(diffDays)));
  else if(diffDays===0) suffix=tr('debt_due_today');
  else suffix=tr('debt_due_in_days').replace('{n}',String(diffDays));
  val.textContent=`${formatDueDate(cd.dueDate)} · ${suffix}`;
  if(icon) icon.style.background = diffDays<=3 ? 'var(--red)' : 'var(--purple)';
}

// A "savings goal"-style payoff progress bar for the current debt, the same
// visual pattern renderGoals() (js/goals-profile.js) already uses for
// savings-wallet goals (a % filled bar, green once reached) — applied here
// to "% of startAmount already paid off" instead of "% of a savings target
// saved". Hidden when startAmount isn't set (a 0/0 bar is meaningless).
function renderDebtProgress(cd,paid){
  const wrap=document.getElementById('debt-progress-wrap');
  const text=document.getElementById('debt-progress-text');
  const fill=document.getElementById('debt-progress-fill');
  if(!wrap||!text||!fill) return;
  const target=cd.startAmount||0;
  if(target<=0){ wrap.style.display='none'; return; }
  wrap.style.display='';
  const pct=Math.max(0,Math.min(100,Math.round((paid/target)*100)));
  const done=pct>=100;
  text.textContent=pct+'%';
  fill.style.width=pct+'%';
  fill.style.background=done?'linear-gradient(90deg,var(--green),var(--green2))':'linear-gradient(90deg,var(--purple),var(--purple2))';
}

// Payoff forecast for the current debt: a balance-burndown mini chart plus
// a plain-language "≈ N payments left at this pace" estimate. Purely
// derived from the existing entries (each carries the remaining `balance`
// after that payment) — no new inputs, no schema change. Shown only when
// there's enough signal to be meaningful: startAmount set, at least 2
// payments, a positive current balance, and a positive average paydown
// (i.e. the balance is actually trending down, not a debt that only grew).
// The pace estimate is by payment *count*, not calendar date, on purpose:
// entry.date is free-form text ("10.02.2026", "Березень", a label…), so a
// count-based "≈ N payments to go" is robust where a date projection would
// often be garbage. Mirrors the burndown/pace view common in loan-payoff
// trackers, built inline as SVG (no chart lib — see CLAUDE.md).
// The two rendered pieces below (chart + text) are this app's first
// Preact-rendered content — a deliberately small proof of concept before
// considering it anywhere else (see CLAUDE.md's "Preact adoption" note).
// Plain stateless functions returning h() trees, no JSX/hooks/classes —
// every call site uses render(h(...), targetEl), never a raw innerHTML=
// write into chartEl/textEl, since mixing the two in the same container
// would desync Preact's internal diff tracking from the real DOM on a
// later render.
function DebtBurndownChart({ W, H, areaPts, linePts, lastX, lastY, title }){
  return h('svg', { viewBox:`0 0 ${W} ${H}`, preserveAspectRatio:'none', role:'img', 'aria-label':title },
    h('defs', null,
      h('linearGradient', { id:'debtBurnFill', x1:'0', y1:'0', x2:'0', y2:'1' },
        h('stop', { offset:'0%', 'stop-color':'rgba(139,92,246,.34)' }),
        h('stop', { offset:'100%', 'stop-color':'rgba(139,92,246,0)' })
      )
    ),
    h('polygon', { points:areaPts, fill:'url(#debtBurnFill)' }),
    h('polyline', { points:linePts, fill:'none', stroke:'var(--purple2)', 'stroke-width':'2', 'stroke-linejoin':'round', 'stroke-linecap':'round', 'vector-effect':'non-scaling-stroke' }),
    h('circle', { cx:lastX.toFixed(1), cy:lastY.toFixed(1), r:'3.5', fill:'var(--purple2)' })
  );
}

// state: 'done' | 'no-pace' | 'pace'. The pace/avg i18n strings each carry
// a {n}/{amt} placeholder meant to become a bolded value — split around
// the placeholder and build a real <strong> element instead of
// interpolating an HTML string (the previous innerHTML approach), so
// there's no HTML-in-a-translation-string parsing involved at all.
/**
 * @param {{state: 'done' | 'no-pace' | 'pace', n?: number, avgStr?: string}} props
 */
function DebtForecastText({ state, n, avgStr }){
  if(state==='done') return h('span', { class:'debt-forecast-done' }, tr('debt_forecast_done'));
  if(state==='no-pace') return tr('debt_forecast_no_pace');
  const [paceBefore, paceAfter] = tr('debt_forecast_pace').split('{n}');
  const [avgBefore, avgAfter] = tr('debt_forecast_avg').split('{amt}');
  return h(Fragment, null,
    paceBefore, h('strong', null, n), paceAfter,
    h('br', null),
    avgBefore, h('strong', { class:'debt-amount-val' }, avgStr), avgAfter
  );
}

function renderDebtForecast(cd, currentBalance){
  const wrap=document.getElementById('debt-forecast');
  const chartEl=document.getElementById('debt-burndown');
  const textEl=document.getElementById('debt-forecast-text');
  if(!wrap||!chartEl||!textEl) return;
  const start=cd.startAmount||0;
  const entries=cd.entries||[];
  if(start<=0 || entries.length<2){ wrap.style.display='none'; return; }
  const cur=cd.currency||'у.о.';

  // Burndown series: startAmount, then the remaining balance after each
  // payment (chronological order — the array's own order, see renderDebt()).
  const series=[start, ...entries.map(e=>Number(e.balance)||0)];
  const maxV=Math.max(...series, 1);
  const minV=Math.min(...series, 0);
  const W=300, H=76, pad=3;
  const span=(maxV-minV)||1;
  const x=i=>pad + (W-2*pad)*(i/(series.length-1));
  const y=v=>pad + (H-2*pad)*(1-(v-minV)/span);
  const linePts=series.map((v,i)=>`${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');
  const areaPts=`${x(0).toFixed(1)},${(H-pad).toFixed(1)} ${linePts} ${x(series.length-1).toFixed(1)},${(H-pad).toFixed(1)}`;
  const lastX=x(series.length-1), lastY=y(series[series.length-1]);
  render(h(DebtBurndownChart, { W, H, areaPts, linePts, lastX, lastY, title: tr('debt_forecast_title') }), chartEl);

  // Average paydown per payment, counting only payments that actually
  // reduced the balance (a correction that raised it isn't "progress").
  let prev=start, totalDown=0, downCount=0;
  entries.forEach(e=>{
    const bal=Number(e.balance)||0;
    const d=prev-bal;
    if(d>0){ totalDown+=d; downCount++; }
    prev=bal;
  });
  const avgDown = downCount ? totalDown/downCount : 0;
  wrap.style.display='';

  if(currentBalance<=0){
    render(h(DebtForecastText, { state:'done' }), textEl);
    return;
  }
  if(avgDown<=0){
    // Balance never trended down (e.g. only-growing debt) — a pace estimate
    // would be meaningless/negative, so show the chart without a forecast.
    render(h(DebtForecastText, { state:'no-pace' }), textEl);
    return;
  }
  const paymentsLeft=Math.max(1, Math.ceil(currentBalance/avgDown));
  const avgStr=Math.round(avgDown).toLocaleString('uk-UA')+' '+cur;
  render(h(DebtForecastText, { state:'pace', n:paymentsLeft, avgStr }), textEl);
}

/** @returns {void} */
export function renderDebt(){
  renderDebtChips();
  const cd=getCurrentDebt();
  if(!cd){
    // No debts in this profile — clear out whatever the previous profile's
    // renderDebt() left on screen instead of leaving it stale.
    const ni=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-name')); if(ni) ni.value='';
    const noi=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-note')); if(noi) noi.value='';
    const ci=/** @type {HTMLSelectElement | null} */ (document.getElementById('debt-currency')); if(ci) ci.value='у.о.';
    const si=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-start')); if(si) si.value='';
    const dui=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-due-date')); if(dui) dui.value='';
    const dueChip=document.getElementById('debt-due-chip'); if(dueChip) dueChip.style.display='none';
    const progWrap=document.getElementById('debt-progress-wrap'); if(progWrap) progWrap.style.display='none';
    const S=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};
    S('debt-start-val','0'); S('debt-balance-val','0'); S('debt-paid-val','0'); S('debt-count-val','0');
    const lc=document.getElementById('debt-list-container');
    const cc=document.getElementById('debt-entry-count');
    if(cc) cc.textContent='';
    if(lc) lc.innerHTML=emptyStateHtml({
      icon:'bank',
      title:tr('debt_empty_no_calc_title'),
      desc:tr('debt_empty_no_calc_desc'),
      action:tr('debt_add_calc'),
      actionName:'add-new-debt'
    });
    return;
  }
  const cur=cd.currency||'у.о.';

  const ni=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-name')); if(ni) ni.value=cd.name||'';
  const noi=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-note')); if(noi) noi.value=cd.note||'';
  const ci=/** @type {HTMLSelectElement | null} */ (document.getElementById('debt-currency')); if(ci) ci.value=cur;
  const si=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-start')); if(si) si.value=String(cd.startAmount||0);
  const dui=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-due-date')); if(dui) dui.value=cd.dueDate||'';
  // Prefill today's date for the next payment if the field is empty
  const ddi=/** @type {HTMLInputElement | null} */ (document.getElementById('debt-date')); if(ddi&&!ddi.value) ddi.value=todayLabel();

  const currentBalance=cd.entries.length?cd.entries[cd.entries.length-1].balance:(cd.startAmount||0);
  const paid=(cd.startAmount||0)-currentBalance;
  const S=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};
  S('debt-start-val',(cd.startAmount||0).toLocaleString('uk-UA')+' '+cur);
  S('debt-balance-val',currentBalance.toLocaleString('uk-UA')+' '+cur);
  S('debt-paid-val',paid.toLocaleString('uk-UA')+' '+cur);
  S('debt-count-val',cd.entries.length);
  renderDebtDueChip(cd);
  renderDebtProgress(cd,paid);
  renderDebtForecast(cd,currentBalance);

  const lc=document.getElementById('debt-list-container');
  const cc=document.getElementById('debt-entry-count');
  if(!lc) return;
  if(cc) cc.textContent=cd.entries.length+' '+tr('finance_records_suffix');
  lc.innerHTML='';

  if(cd.entries.length===0){
    lc.innerHTML=emptyStateHtml({
      icon:'coin',
      title:tr('debt_empty_title'),
      desc:tr('debt_empty_desc'),
      action:tr('debt_add_payment'),
      actionName:'open-new-debt-entry-modal'
    });
    return;
  }

  let prevBalance=cd.startAmount||0;
  cd.entries.forEach(entry=>{
    const isCleanNumber=/^\d+(\.\d+)?$/.test(String(entry.amount).trim());
    const expected=isCleanNumber?prevBalance-parseFloat(entry.amount):null;
    const hasDiscrepancy=expected!==null&&Math.abs(expected-entry.balance)>0.01;
    const row=document.createElement('div');
    const editing=AppState.debtEntryEditId===entry.id;
    row.className='debt-row'+(hasDiscrepancy?' discrepancy':'');
    const fieldsHtml = editing ? `
      <div class="debt-field"><span class="debt-field-label">${tr('debt_amount')}</span><input type="text" value="${escapeHtml(entry.amount??'')}" data-action="update-debt-entry" data-id="${entry.id}" data-field="amount"></div>
      <div class="debt-field"><span class="debt-field-label">${tr('debt_stat_balance')}</span><input type="number" step="0.01" value="${entry.balance??''}" data-action="update-debt-entry" data-id="${entry.id}" data-field="balance"></div>
      <div class="debt-field"><span class="debt-field-label">${tr('finance_date')}</span><input type="text" value="${escapeHtml(entry.date??'')}" data-action="update-debt-entry" data-id="${entry.id}" data-field="date"></div>
      <button class="debt-row-edit debt-row-edit-active" data-action="toggle-debt-entry-edit" data-id="${entry.id}" aria-label="${tr('a11y_confirm')}">${window.Icon('check')}</button>
    ` : `
      <div class="debt-field"><span class="debt-field-label">${tr('debt_amount')}</span><div class="debt-field-view debt-amount-val">${escapeHtml(entry.amount??'')}</div></div>
      <div class="debt-field"><span class="debt-field-label">${tr('debt_stat_balance')}</span><div class="debt-field-view debt-amount-val">${(entry.balance??0).toLocaleString('uk-UA')}</div></div>
      <div class="debt-field"><span class="debt-field-label">${tr('finance_date')}</span><div class="debt-field-view">${entry.date?escapeHtml(entry.date):'—'}</div></div>
      <button class="debt-row-edit" data-action="toggle-debt-entry-edit" data-id="${entry.id}" aria-label="${tr('common_edit')}">${window.Icon('pencil')}</button>
    `;
    row.dataset.entryId=String(entry.id);
    row.innerHTML=`
      <div class="debt-row-inner">
        ${fieldsHtml}
        ${hasDiscrepancy?`<div class="debt-hint">${tr('debt_expected')} ${expected.toLocaleString('uk-UA')} ${cur} — ${tr('debt_discrepancy')} ${(entry.balance-expected).toLocaleString('uk-UA')} ${cur}</div>`:''}
      </div>
      <button class="debt-row-swipe-delete" data-action="delete-debt-entry" data-id="${entry.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
    `;
    setupDebtRowSwipe(row);
    // Newest entry first: cd.entries stays in chronological (push) order,
    // since the running-balance chaining above (prevBalance/expected) and
    // debtCurrentBalance()'s "last entry = current balance" assumption both
    // depend on that array order — only the *display* order flips, by
    // prepending each row instead of appending it (the loop still visits
    // entries oldest-to-newest, so the row processed last ends up on top).
    lc.prepend(row);
    prevBalance=entry.balance;
  });
}

const DEBT_ROW_SWIPE_REVEAL_PX=60;
const DEBT_ROW_SWIPE_OPEN_THRESHOLD=30;

function closeAllDebtRowSwipes(except){
  document.querySelectorAll('.debt-row.swipe-open').forEach(el=>{ if(el!==except) el.classList.remove('swipe-open'); });
}

// Touch-swipe-to-reveal-delete for debt payment-history rows — mirrors
// js/analytics-csv.js's setupTxSwipe() (see that function's comment for the
// full pointer-event drag rationale); duplicated rather than shared since
// the two target different outer/inner class names and this repo's
// established style is per-file self-contained render logic (see e.g. the
// tests/*.mjs stub-duplication convention in CLAUDE.md). Called fresh on
// every row every renderDebt() call, since renderDebt() does a full
// rebuild (lc.innerHTML='' then re-append), unlike renderFinance()'s
// targeted node-reuse diff — no risk of double-binding listeners on a
// reused node here.
function setupDebtRowSwipe(row){
  let startX=0,startY=0,dx=0,dragging=false,decided=false,horizontal=false;
  row.addEventListener('pointerdown',e=>{
    if(e.pointerType==='mouse') return; // mouse gets the CSS :hover reveal instead
    startX=e.clientX; startY=e.clientY; dx=0; dragging=true; decided=false; horizontal=false;
  });
  row.addEventListener('pointermove',e=>{
    if(!dragging) return;
    const ddx=e.clientX-startX, ddy=e.clientY-startY;
    if(!decided){
      if(Math.abs(ddx)<6 && Math.abs(ddy)<6) return;
      decided=true;
      horizontal=Math.abs(ddx)>Math.abs(ddy);
      if(horizontal){
        try{ row.setPointerCapture(e.pointerId); }catch(err){}
        row.classList.add('swipe-dragging');
      }
    }
    if(!horizontal) return;
    dx=Math.max(-DEBT_ROW_SWIPE_REVEAL_PX*1.3, Math.min(0,ddx));
    const inner=row.querySelector('.debt-row-inner');
    if(inner) inner.style.width=`calc(100% - ${-dx}px)`;
  });
  function endDrag(){
    if(!dragging) return;
    dragging=false;
    row.classList.remove('swipe-dragging');
    const inner=row.querySelector('.debt-row-inner');
    if(inner) inner.style.width='';
    if(horizontal){
      if(dx<-DEBT_ROW_SWIPE_OPEN_THRESHOLD){ closeAllDebtRowSwipes(row); row.classList.add('swipe-open'); }
      else row.classList.remove('swipe-open');
    }
  }
  row.addEventListener('pointerup',endDrag);
  row.addEventListener('pointercancel',endDrag);
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
/** @returns {void} */
export function __init_debt__(){
// Phase 8 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// converts this file's own 6 dynamic onclick/onchange sites (debt-entry
// edit/delete/fields) plus 8 static index.html ones (new-debt-entry FAB,
// info/history panel toggles, debt-info fields, add-payment, delete-debt)
// to data-action, same pattern as phases 3-7. Also folds in 5 window.*
// assignments that were exports of THIS file's own functions
// (updateDebtInfo/addDebtEntry/deleteCurrentDebt/updateDebtEntry/
// deleteDebtEntry) but physically lived in js/color-picker.js's
// __init_color_picker__ — a leftover of the original mechanical split
// phase 4 deliberately left alone (see that entry in CLAUDE.md); now that
// this file is the one being worked, those 5 lines move here and get the
// same data-action treatment instead of staying as dead weight in a
// different file's init function.
const CLICK_ACTIONS = {
  'add-new-debt': ()=>addNewDebt(),
  'open-new-debt-entry-modal': ()=>openNewDebtEntryModal(),
  'toggle-debt-info-panel': ()=>toggleDebtInfoPanel(),
  'toggle-debt-history-panel': ()=>toggleDebtHistoryPanel(),
  'toggle-debt-entry-edit': ds=>toggleDebtEntryEdit(Number(ds.id)),
  'delete-debt-entry': ds=>deleteDebtEntry(Number(ds.id)),
  'add-debt-entry': ()=>addDebtEntry(),
  'delete-current-debt': ()=>deleteCurrentDebt(),
};
document.addEventListener('click', e=>{
  const el=/** @type {HTMLElement | null} */ (/** @type {Element} */ (e.target).closest('[data-action]'));
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);

const FIELD_ACTIONS = {
  'auto-fill-debt-balance': ()=>autoFillDebtBalance(),
  'update-debt-info': ()=>updateDebtInfo(),
  'update-debt-entry': (ds,el)=>updateDebtEntry(Number(ds.id), ds.field, el.value),
};
function dispatchFieldAction(e){
  const el=/** @type {HTMLInputElement | null} */ (/** @type {Element} */ (e.target).closest('[data-action]'));
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el);
}
document.addEventListener('change', dispatchFieldAction);
document.addEventListener('input', dispatchFieldAction);

// Closes any swiped-open .debt-row (see setupDebtRowSwipe() above) the
// moment a pointer goes down anywhere outside it — same convention as
// js/analytics-csv.js's matching listener for .tx-item.
document.addEventListener('pointerdown', e=>{
  document.querySelectorAll('.debt-row.swipe-open').forEach(el=>{
    if(!el.contains(/** @type {Node} */ (e.target))) el.classList.remove('swipe-open');
  });
});

// Empty-state actions are data-action based now (CSP-safe), so no window.*
// exports are needed for addNewDebt/openNewDebtEntryModal.
}
