// @ts-check
// ── FINANCE ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { renderFinance } from './analytics-csv.js';
import { renderFinanceChart } from './calendar.js';
import { saveConfigLocal, scheduleSave } from './color-picker.js';
import { PALETTE, canEditActiveProfile, convertCurrency, currencySymbol, subKey, toBase, walletById, walletCurrency } from './core.js';
import { batchWriteTransactions, deleteTransactionDoc, lsKey, saveTransactionDoc } from './firebase-sync.js';
import { setCacheItem } from './privacy-cache.js';
import { uid } from './settings-managers.js';
import { TX_AMOUNT_MAX, TX_COMMENT_MAX, validateTransactionDraft } from './tx-validation.js';
import { csSync, enhanceSelect, escapeHtml, hexA, setupAccessibleClickableDivs, showToast, syncClickableA11yState, uiConfirm, uiPrompt } from './ui-widgets.js';
import { scanReceiptImage } from './receipt-ocr.js';

/** @returns {void} */
export function refreshWalletSelects(){
  ['fin-wallet','fin-wallet-target'].forEach((selId,i)=>{
    const sel=/** @type {HTMLSelectElement | null} */ (document.getElementById(selId)); if(!sel) return;
    const prev=sel.value;
    sel.innerHTML='';
    AppState.wallets.forEach(w=>{const o=document.createElement('option');o.value=w.id;o.textContent=`${w.name} (${w.currency||'UAH'})`;sel.appendChild(o);});
    if(prev&&AppState.wallets.some(w=>w.id===prev)) sel.value=prev;
    else if(selId==='fin-wallet-target'&&AppState.wallets[1]) sel.value=AppState.wallets[1].id;
  });
  updateAmountLabel();
  updateTransferHint();
}

/** @returns {void} */
export function updateAmountLabel(){
  const lbl=document.getElementById('fin-amount-label'); if(!lbl) return;
  const ws=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet'));
  const cur=ws?walletCurrency(ws.value):'UAH';
  lbl.textContent=`${tr('finance_amount_prefix')} (${currencySymbol(cur)})`;
  updateTransferHint();
}

/** @returns {void} */
export function updateTransferHint(){
  const hint=document.getElementById('transfer-rate-hint');
  if(!hint) return;
  if(AppState.currentFinanceType!=='transfer'){
    hint.style.display='none';
    hint.classList.remove('warning');
    hint.textContent='';
    return;
  }
  const ws=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet'))?.value;
  const wt=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet-target'))?.value;
  const amount=Number(/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount'))?.value)||0;
  const srcCur=walletCurrency(ws||'');
  const targetCur=walletCurrency(wt||'');
  const sampleAmount=amount>0?amount:1;
  const converted=convertCurrency(sampleAmount, srcCur, targetCur);
  if(!ws||!wt||!Number.isFinite(converted)){
    hint.style.display='none';
    hint.classList.remove('warning');
    hint.textContent='';
    return;
  }
  if(ws===wt){
    hint.style.display='flex';
    hint.classList.add('warning');
    hint.textContent=tr('finance_transfer_same_wallet_hint');
    return;
  }
  const sourceText=amount>0?`${sampleAmount.toFixed(2)} ${srcCur}`:`1 ${srcCur}`;
  const targetText=`${converted.toFixed(2)} ${targetCur}`;
  hint.style.display='flex';
  hint.classList.remove('warning');
  hint.innerHTML=`<span>≈</span><span>${tr('finance_transfer_hint')} <strong>${escapeHtml(sourceText)}</strong> → <strong>${escapeHtml(targetText)}</strong></span>`;
}

/** @param {string} type */
export function setFinanceType(type){
  AppState.currentFinanceType=type;
  const btnByType={income:'inc',expense:'exp',transfer:'trn'};
  Object.entries(btnByType).forEach(([btnType,suffix])=>{
    const btn=document.getElementById('btn-'+suffix);
    if(!btn) return;
    const active=btnType===type;
    btn.classList.toggle('active', active);
    btn.setAttribute('aria-pressed', active?'true':'false');
  });
  const wsl=document.getElementById('wallet-source-label');
  const tg=document.getElementById('wallet-target-group');
  const cg=document.getElementById('category-group');
  const sg=document.getElementById('subcategory-group');
  const rsg=document.getElementById('receipt-scan-group');
  refreshWalletSelects();
  // A transfer has no "receipt" to scan — a receipt implies a real
  // income/expense with a store/counterparty, not moving money between
  // your own wallets.
  if(rsg) rsg.style.display=(type==='transfer')?'none':'flex';
  if(type==='income')  {if(wsl)wsl.textContent=tr('finance_wallet');if(tg)tg.style.display='none';if(cg)cg.style.display='flex';fillCats('income');}
  if(type==='expense') {if(wsl)wsl.textContent=tr('finance_wallet_expense');if(tg)tg.style.display='none';if(cg)cg.style.display='flex';fillCats('expense');}
  if(type==='transfer'){if(wsl)wsl.textContent=tr('finance_wallet_transfer');if(tg)tg.style.display='flex';if(cg)cg.style.display='none';if(sg)sg.style.display='none';}
  updateTransferHint();
  renderFinTagChips();
}

function renderFinTagChips(){
  const group=document.getElementById('tags-group');
  const box=document.getElementById('fin-tags-chips');
  if(!group||!box) return;
  if(!AppState.tags.length){ group.style.display='none'; return; }
  group.style.display='flex';
  box.innerHTML=AppState.tags.map(t=>{
    const on=AppState.selectedTagIds.includes(t.id);
    const style=on?`border-color:${t.color};background:${hexA(t.color,.18)};color:${t.color}`:'';
    return `<div class="filter-chip${on?' active':''}" style="${style}" data-action="toggle-fin-tag" data-id="${t.id}">${escapeHtml(t.name)}</div>`;
  }).join('');
  setupAccessibleClickableDivs(box);
}

/** @param {string} id */
const toggleFinTag = function(id){
  const i=AppState.selectedTagIds.indexOf(id);
  if(i===-1) AppState.selectedTagIds.push(id); else AppState.selectedTagIds.splice(i,1);
  renderFinTagChips();
};

/** @param {string} type */
export function fillCats(type){
  const sel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-category'));if(!sel)return;
  const prev=sel.value;
  sel.innerHTML='';
  (AppState.categories[type]||[]).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o);});
  if(prev&&(AppState.categories[type]||[]).includes(prev)) sel.value=prev;
  fillSubcats();
}

/** @returns {void} */
export function fillSubcats(){
  const sel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-subcategory'));
  const group=document.getElementById('subcategory-group');
  if(!sel||!group) return;
  if(AppState.currentFinanceType==='transfer'){ group.style.display='none'; return; }
  const catSel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-category'));
  const cat=catSel?catSel.value:'';
  const subs=AppState.subcategories[subKey(AppState.currentFinanceType,cat)]||[];
  const prev=sel.value;
  sel.innerHTML='<option value="">—</option>'+subs.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join('');
  if(prev&&subs.includes(prev)) sel.value=prev;
  group.style.display = subs.length ? 'flex' : 'none';
}

/** @returns {string} */
export function newTransactionId(){
  try{ if(crypto&&crypto.randomUUID) return crypto.randomUUID(); }catch(e){}
  return uid('tx');
}

/** @param {*} a @param {*} b */
function sameTxId(a,b){ return String(a)===String(b); }

function txToday(){
  return new Date().toISOString().split('T')[0];
}

const setTxDateToday = function(){
  const input=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-date'));
  if(!input) return;
  input.value=txToday();
  // enhanceDateInput() (js/ui-widgets.js) only refreshes the visible
  // .dp-val label on a real 'change'/'cs-sync' event — setting .value
  // directly leaves the picker showing the old date while the hidden
  // input already holds today's, so the form can submit a date the user
  // never saw selected.
  input.dispatchEvent(new Event('change',{bubbles:true}));
};

/** @returns {void} */
export function updateCommentCounter(){
  const input=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment'));
  const counter=document.getElementById('fin-comment-counter');
  if(!input||!counter) return;
  const used=input.value.length;
  counter.textContent=`${used}/${TX_COMMENT_MAX}`;
  counter.style.color=used>TX_COMMENT_MAX*0.9?'var(--orange)':'var(--muted)';
}

function readTransactionForm(){
  const ws=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet'))?.value||(AppState.wallets[0]&&AppState.wallets[0].id)||'';
  const wt=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet-target'))?.value||(AppState.wallets[1]&&AppState.wallets[1].id)||'';
  const amount=Number(/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount'))?.value);
  const date=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-date'))?.value||'';
  const cat=AppState.currentFinanceType==='transfer'?'Внутрішній переказ':(/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-category'))?.value||'Інше');
  const sub=AppState.currentFinanceType==='transfer'?undefined:(/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-subcategory'))?.value||undefined);
  const comment=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment'))?.value.trim()||'';
  return {amount,date,ws,wt,cat,sub,comment};
}

/** @returns {Promise<void>} */
export async function addTransaction(){
  if(!canEditActiveProfile()){ showToast(tr('shared_profile_readonly'),'xmark'); return; }
  const ai=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount'));
  const draft=readTransactionForm();
  const errKey=validateTransactionDraft(draft, AppState.currentFinanceType==='transfer');
  if(errKey){showToast(tr(errKey),'xmark');return;}
  const {amount,date,ws,wt,cat,sub,comment}=draft;
  const srcCur=walletCurrency(ws);
  let targetAmount=null, targetCurrency=null;
  if(AppState.currentFinanceType==='transfer'){
    targetCurrency=walletCurrency(wt);
    targetAmount=convertCurrency(amount, srcCur, targetCurrency);
    if(!Number.isFinite(targetAmount)||targetAmount<=0||targetAmount>=TX_AMOUNT_MAX){showToast(tr('finance_err_amount_large'),'xmark');return;}
  }
  if(AppState.editingTxId!=null){
    const t=AppState.transactions.find(x=>sameTxId(x.id,AppState.editingTxId));
    if(t) Object.assign(t,{type:AppState.currentFinanceType,amount,currency:srcCur,category:cat,subcategory:sub,tags:AppState.selectedTagIds.slice(),wallet:ws,targetWallet:AppState.currentFinanceType==='transfer'?wt:null,targetAmount,targetCurrency,date,comment});
    cancelEditTransaction();
    const txKey=lsKey('tx'); if(txKey) setCacheItem(txKey,JSON.stringify(AppState.transactions));
    // Writes straight to this transaction's own subcollection doc rather
    // than scheduleSave()'s whole-finance-doc rewrite — see
    // js/firebase-sync.js's TRANSACTIONS SUBCOLLECTION section.
    if(t) saveTransactionDoc(t).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
    renderFinance(); renderFinanceChart();
    const m1=document.getElementById('tx-form-modal'); if(m1) m1.style.display='none';
    showToast(tr('toast_tx_updated'),'check');
    return;
  }
  const newTx={id:newTransactionId(),createdAt:Date.now(),type:AppState.currentFinanceType,amount,currency:srcCur,category:cat,subcategory:sub,tags:AppState.selectedTagIds.slice(),wallet:ws,targetWallet:AppState.currentFinanceType==='transfer'?wt:null,targetAmount,targetCurrency,date,comment};
  AppState.transactions.unshift(newTx);
  const txKey=lsKey('tx'); if(txKey) setCacheItem(txKey,JSON.stringify(AppState.transactions));
  saveTransactionDoc(newTx).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
  if(ai)ai.value='';
  const ci=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment'));if(ci)ci.value='';
  updateCommentCounter();
  AppState.selectedTagIds=[]; renderFinTagChips();
  renderFinance(); renderFinanceChart();
  const m2=document.getElementById('tx-form-modal'); if(m2) m2.style.display='none';

  let toastMsg=AppState.currentFinanceType==='transfer'?tr('toast_transfer_done'):tr('toast_tx_added');
  let toastIcon=AppState.currentFinanceType==='transfer'?'swap':'check';
  if(AppState.currentFinanceType==='expense' && AppState.budgets[cat]>0){
    const now=new Date();
    const mPrefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
    if(date.startsWith(mPrefix)){
      const limit=AppState.budgets[cat];
      const spent=AppState.transactions.reduce((s,t)=>(t.type==='expense'&&t.category===cat&&t.date&&t.date.startsWith(mPrefix))?s+toBase(t.amount,t.currency||'UAH'):s,0);
      if(spent>=limit){ toastMsg=`Бюджет «${cat}» перевищено: ${spent.toLocaleString('uk-UA')}/${limit.toLocaleString('uk-UA')} грн`; toastIcon='warning'; }
      else if(spent>=limit*0.9){ toastMsg=`Бюджет «${cat}»: ${Math.round(spent/limit*100)}% витрачено`; toastIcon='warning'; }
    }
  }
  showToast(toastMsg, toastIcon);
}

/**
 * @param {string | number} id
 * @returns {Promise<void>}
 */
export async function deleteTransaction(id){
  if(!canEditActiveProfile()){ showToast(tr('shared_profile_readonly'),'xmark'); return; }
  if(!(await uiConfirm(tr('finance_delete_confirm'),{title:tr('finance_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.transactions=AppState.transactions.filter(t=>!sameTxId(t.id,id));
  const txKey=lsKey('tx'); if(txKey) setCacheItem(txKey,JSON.stringify(AppState.transactions));
  deleteTransactionDoc(id).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
  renderFinance(); renderFinanceChart();
}

/** @param {string | number} id */
export const editTransaction = function(id){
  const t=AppState.transactions.find(x=>sameTxId(x.id,id)); if(!t) return;
  AppState.editingTxId=id;
  setFinanceType(t.type);

  const wsel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet'));
  if(wsel){ wsel.value=t.wallet; wsel.dispatchEvent(new Event('change',{bubbles:true})); }
  if(t.type==='transfer'){
    const wtsel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-wallet-target'));
    if(wtsel){ wtsel.value=t.targetWallet; wtsel.dispatchEvent(new Event('change',{bubbles:true})); }
  } else {
    const catsel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-category'));
    if(catsel){ catsel.value=t.category; catsel.dispatchEvent(new Event('change',{bubbles:true})); }
    const subsel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-subcategory'));
    if(subsel){ subsel.value=t.subcategory||''; subsel.dispatchEvent(new Event('change',{bubbles:true})); }
  }
  const ai=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount')); if(ai) ai.value=String(t.amount);
  updateTransferHint();
  const dsel=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-date'));
  if(dsel){ dsel.value=t.date||''; dsel.dispatchEvent(new Event('change',{bubbles:true})); }
  const ci=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment')); if(ci) ci.value=t.comment||'';
  updateCommentCounter();
  AppState.selectedTagIds=(t.tags||[]).slice(); renderFinTagChips();

  const titleText=document.getElementById('fin-form-title-text'); if(titleText) titleText.textContent=tr('finance_edit_title');
  const submitBtn=document.getElementById('fin-submit-btn'); if(submitBtn) submitBtn.textContent=tr('finance_save_changes');
  const cancelBtn=document.getElementById('fin-cancel-edit-btn'); if(cancelBtn) cancelBtn.style.display='inline-block';
  const m=document.getElementById('tx-form-modal'); if(m) m.style.display='flex';
};

const cancelEditTransaction = function(){
  AppState.editingTxId=null;
  const ai=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount')); if(ai) ai.value='';
  const ci=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment')); if(ci) ci.value='';
  setTxDateToday();
  updateCommentCounter();
  AppState.selectedTagIds=[]; renderFinTagChips();
  const titleText=document.getElementById('fin-form-title-text'); if(titleText) titleText.textContent=tr('finance_new_tx');
  const submitBtn=document.getElementById('fin-submit-btn'); if(submitBtn) submitBtn.textContent=tr('finance_add_btn');
  const cancelBtn=document.getElementById('fin-cancel-edit-btn'); if(cancelBtn) cancelBtn.style.display='none';
};

const openNewTxModal = function(){
  cancelEditTransaction();
  const m=document.getElementById('tx-form-modal'); if(m) m.style.display='flex';
};

const closeTxModal = function(){
  cancelEditTransaction();
  const m=document.getElementById('tx-form-modal'); if(m) m.style.display='none';
};

/** @param {string | number} [amount] */
const setTxAmount = function(amount){
  const ai=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount'));
  if(!ai) return;
  ai.value=String(amount||'');
  ai.focus();
  updateTransferHint();
};

function renderTxSearchControls(){
  const btn=document.getElementById('tx-search-clear');
  if(btn) btn.style.display=AppState.txSearch?'flex':'none';
}

/** @param {string} value */
export function setTxSearch(value){
  AppState.txSearch=String(value||'').trim().toLowerCase();
  renderTxSearchControls();
  renderFinance();
}

const clearTxSearch = function(){
  const input=/** @type {HTMLInputElement | null} */ (document.getElementById('tx-search-input'));
  if(input) input.value='';
  setTxSearch('');
};

/** @param {string} f */
export function setTxFilter(f){
  AppState.txFilter=f;
  document.querySelectorAll('.filter-chip').forEach(c=>{
    c.classList.toggle('active',/** @type {HTMLElement} */ (c).dataset.filter===f);
  });
  syncClickableA11yState(document.getElementById('tab-finance'));
  renderFinance();
}

/**
 * @param {string} id
 * @returns {string}
 */
export function walletBadge(id){
  const w=walletById(id);
  const name=w?w.name:'—';
  const color=w?(w.color||'#8b5cf6'):'#7b709a';
  const icon=w?(w.icon||'card'):'card';
  return `<span class="wallet-tag" style="background:${hexA(color,.12)};color:${color};border:1px solid ${hexA(color,.28)}">${window.Icon(icon)}<span class="wallet-tag-name">${escapeHtml(name)}</span></span>`;
}

/**
 * @param {string} id
 * @returns {string}
 */
export function tagBadge(id){
  const t=AppState.tags.find(x=>x.id===id);
  if(!t) return '';
  return `<span class="wallet-tag" style="background:${hexA(t.color,.12)};color:${t.color};border:1px solid ${hexA(t.color,.28)}">${window.Icon('tag')}<span class="wallet-tag-name">${escapeHtml(t.name)}</span></span>`;
}

const openTagsManager = function(){
  renderTagsList();
  const modal=document.getElementById('tags-modal'); if(modal) modal.style.display='flex';
};

function renderTagsList(){
  const box=document.getElementById('tags-list'); if(!box) return;
  box.innerHTML='';
  if(!AppState.tags.length){ box.innerHTML=`<div class="mgr-empty">${tr('tags_empty')}</div>`; return; }
  AppState.tags.forEach(t=>{
    const row=document.createElement('div');
    row.className='mgr-row';
    row.innerHTML=`
      <button type="button" class="mgr-color" style="background:${escapeHtml(t.color||'#8b5cf6')}" data-action="open-color-picker" data-kind="tag" data-id="${t.id}"></button>
      <input type="text" class="mgr-name-inline" value="${escapeHtml(t.name)}" placeholder="${tr('common_name')}" data-action="update-tag" data-id="${t.id}" data-field="name">
      <button class="mgr-del" data-action="delete-tag" data-id="${t.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>`;
    box.appendChild(row);
  });
}

/**
 * @param {string} id
 * @param {string} field
 * @param {*} value
 */
export const updateTag = function(id,field,value){
  const t=AppState.tags.find(x=>x.id===id); if(!t) return;
  if(field==='name') t.name=String(value).trim()||tr('tags_default_name');
  else /** @type {any} */ (t)[field]=value;
  saveConfigLocal(); scheduleSave();
  renderFinTagChips(); renderFinance();
};

const addTag = async function(){
  const name=await uiPrompt(tr('tags_add_prompt'),'',tr('tags_add_title'));
  if(name===null) return;
  const clean=name.trim(); if(!clean) return;
  const color=PALETTE[AppState.tags.length%PALETTE.length];
  AppState.tags.push({id:uid('tag'), name:clean, color});
  saveConfigLocal(); scheduleSave();
  renderTagsList(); renderFinTagChips();
};

/** @param {string} id */
const deleteTag = async function(id){
  if(!(await uiConfirm(tr('tags_delete_confirm'),{title:tr('tags_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.tags=AppState.tags.filter(t=>t.id!==id);
  AppState.selectedTagIds=AppState.selectedTagIds.filter(tid=>tid!==id);
  /** @type {any[]} */
  const affected=[];
  AppState.transactions.forEach(t=>{ if(Array.isArray(t.tags)&&t.tags.includes(id)){ t.tags=t.tags.filter((/** @type {string} */ tid)=>tid!==id); affected.push(t); } });
  saveConfigLocal();
  const tk=lsKey('tx'); if(tk) setCacheItem(tk,JSON.stringify(AppState.transactions));
  // tags[] itself is a finance-doc field (needs scheduleSave()); the
  // individual transactions that referenced this tag are their own
  // subcollection docs and get updated directly instead.
  scheduleSave();
  if(affected.length) batchWriteTransactions(affected).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
  renderTagsList(); renderFinTagChips(); renderFinance();
};

const openRulesManager = function(){
  renderAutoRulesList();
  const modal=document.getElementById('rules-modal'); if(modal) modal.style.display='flex';
};

/** @param {string} id */
const toggleRuleEdit = function(id){
  AppState.expandedRuleId = AppState.expandedRuleId===id ? null : id;
  renderAutoRulesList();
};

// Compact-manager-row pattern (icon badge + two-line summary + pencil
// toggle that reveals the full field set, same shape as
// renderShiftTypesList()/renderCategoriesList()) — replaces the old
// always-expanded .debt-row stack of labeled fields, see CLAUDE.md's
// "Unify manager design" note.
function renderAutoRulesList(){
  const box=document.getElementById('rules-list'); if(!box) return;
  box.innerHTML='';
  if(!AppState.autoRules.length){ box.innerHTML=`<div class="mgr-empty">${tr('rules_empty')}</div>`; return; }
  AppState.autoRules.forEach(r=>{
    const catList=AppState.categories[r.type]||[];
    const open=AppState.expandedRuleId===r.id;
    const typeLabel=r.type==='income'?tr('cat_income'):tr('cat_expense');
    const summary=r.keyword ? `"${escapeHtml(r.keyword)}" → ${escapeHtml(r.category||'')}` : tr('rules_keyword_placeholder');
    const row=document.createElement('div');
    row.className='mgr-row';
    row.style.cssText='flex-direction:column;align-items:stretch;gap:10px';
    row.innerHTML=`
      <div class="cat-row">
        <div class="icon-badge icon-badge-sm" style="background:var(--purple)">${window.Icon('sparkle')}</div>
        <div class="cat-row-body" style="cursor:default">
          <span class="cat-row-name">${summary}</span>
          <span class="cat-row-sub">${typeLabel}</span>
        </div>
        <button type="button" class="mgr-edit${open?' active':''}" data-action="toggle-rule-edit" data-id="${r.id}" aria-label="${tr('common_edit')}">${window.Icon(open?'xmark':'pencil')}</button>
        <button class="mgr-del" data-action="delete-auto-rule" data-id="${r.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
      </div>
      ${open?`
      <div style="display:flex;flex-direction:column;gap:8px;padding-top:6px;border-top:1px dashed var(--border)">
        <div class="mgr-field"><span class="mgr-field-label">${tr('recurring_type')}</span>
          <select data-action="update-auto-rule" data-id="${r.id}" data-field="type">
            <option value="expense" ${r.type==='expense'?'selected':''}>${tr('cat_expense')}</option>
            <option value="income" ${r.type==='income'?'selected':''}>${tr('cat_income')}</option>
          </select>
        </div>
        <div class="mgr-field"><span class="mgr-field-label">${tr('rules_keyword')}</span>
          <input type="text" class="mgr-name" value="${escapeHtml(r.keyword||'')}" placeholder="${tr('rules_keyword_placeholder')}" data-action="update-auto-rule" data-id="${r.id}" data-field="keyword">
        </div>
        <div class="mgr-field"><span class="mgr-field-label">${tr('finance_category')}</span>
          <select data-action="update-auto-rule" data-id="${r.id}" data-field="category">
            ${catList.map(c=>`<option value="${escapeHtml(c)}" ${r.category===c?'selected':''}>${escapeHtml(c)}</option>`).join('')}
          </select>
        </div>
      </div>`:''}`;
    box.appendChild(row);
    row.querySelectorAll('select').forEach(enhanceSelect);
  });
}

/**
 * @param {string} id
 * @param {string} field
 * @param {string} value
 */
const updateAutoRule = function(id,field,value){
  const r=AppState.autoRules.find(x=>x.id===id); if(!r) return;
  if(field==='type'){ r.type=value; r.category=(AppState.categories[value]||[])[0]||''; }
  else /** @type {any} */ (r)[field]=value;
  saveConfigLocal(); scheduleSave();
  renderAutoRulesList();
};

const addAutoRule = function(){
  const type='expense';
  const category=(AppState.categories.expense||[])[0]||'';
  AppState.autoRules.push({id:uid('rule'), type, keyword:'', category});
  saveConfigLocal(); scheduleSave();
  renderAutoRulesList();
};

/** @param {string} id */
const deleteAutoRule = async function(id){
  if(!(await uiConfirm(tr('rules_delete_confirm'),{title:tr('rules_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.autoRules=AppState.autoRules.filter(r=>r.id!==id);
  saveConfigLocal(); scheduleSave();
  renderAutoRulesList();
};

/**
 * @param {string} type
 * @param {string} comment
 * @returns {*}
 */
export function findMatchingRule(type, comment){
  if(!comment) return null;
  const lc=comment.toLowerCase();
  return AppState.autoRules.find(r=>r.type===type && r.keyword && lc.includes(r.keyword.toLowerCase())) || null;
}

/** @returns {void} */
export function applyAutoRuleToForm(){
  if(AppState.currentFinanceType==='transfer') return;
  const ci=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment'));
  const rule=findMatchingRule(AppState.currentFinanceType, ci?ci.value:'');
  if(!rule) return;
  const catSel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-category'));
  if(!catSel || catSel.value===rule.category) return;
  if(!(AppState.categories[AppState.currentFinanceType]||[]).includes(rule.category)) return;
  catSel.value=rule.category;
  catSel.dispatchEvent(new Event('change',{bubbles:true}));
  csSync(catSel);
  showToast(`${tr('rules_auto_applied')} ${rule.category}`,'sparkle');
}

// ── ON-DEVICE AI CATEGORY SUGGESTION ──────────────────────────────
// Chrome's built-in Prompt API (self.LanguageModel, stable from Chrome
// 138) runs a small model entirely on-device: no network call, no API key,
// no per-request cost, and the transaction comment never leaves the
// browser. Feature-detected and a silent no-op everywhere it's
// unsupported — every browser this app is actually tested against,
// including this repo's own Playwright/Chromium sandbox, which has no
// on-device model installed — so this can never block or break the form,
// only enhance it where available. Runs only when findMatchingRule() above
// found nothing: a user-authored keyword rule is deterministic and always
// takes priority over a probabilistic AI guess.
/** @type {Promise<any> | null} */
let aiSessionPromise=null;
function getAISession(){
  if(!aiSessionPromise){
    aiSessionPromise=(async()=>{
      if(typeof self==='undefined' || !(/** @type {any} */ (self)).LanguageModel) return null;
      try{
        const availability=await (/** @type {any} */ (self)).LanguageModel.availability();
        if(availability==='unavailable') return null;
        return await (/** @type {any} */ (self)).LanguageModel.create({
          initialPrompts:[{role:'system', content:'You categorize personal-finance transactions for a budgeting app. Reply with only the exact category name from the list given to you, nothing else — no punctuation, no explanation.'}],
        });
      }catch(e){ return null; }
    })();
  }
  return aiSessionPromise;
}

/** @type {ReturnType<typeof setTimeout> | null} */
let aiSuggestTimer=null;
/** @returns {void} */
export function maybeSuggestCategoryWithAI(){
  clearTimeout(aiSuggestTimer ?? undefined);
  if(AppState.currentFinanceType==='transfer') return;
  const ci=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment'));
  const text=ci?ci.value.trim():'';
  // Short comments ("кава", "хліб") are exactly what the deterministic
  // keyword rules above already handle well; the model adds real value on
  // longer, less structured notes, and skipping short ones avoids firing a
  // session-create + prompt round-trip on every couple of keystrokes.
  if(text.length<8) return;
  if(findMatchingRule(AppState.currentFinanceType, text)) return;
  const categories=(AppState.categories[AppState.currentFinanceType]||[]).slice();
  if(categories.length<2) return;
  aiSuggestTimer=setTimeout(async()=>{
    // Re-checked at every stage below: typing more, switching income/
    // expense, or picking a category by hand while the (possibly slow)
    // session setup / model call is still in flight should never let a
    // stale suggestion land on top of what the user's doing right now.
    const stillFresh=()=>{
      const c=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-comment'));
      return AppState.currentFinanceType!=='transfer' && c && c.value.trim()===text;
    };
    if(!stillFresh()) return;
    const session=await getAISession();
    if(!session || !stillFresh()) return;
    let answer;
    try{
      answer=await session.prompt(`Categories: ${categories.join(', ')}\nTransaction note: "${text}"\nWhich single category best matches? Reply with only the exact category name from the list above.`);
    }catch(e){ return; }
    if(!stillFresh()) return;
    const picked=categories.find(c=>c.trim().toLowerCase()===String(answer||'').trim().toLowerCase());
    const catSel=/** @type {HTMLSelectElement | null} */ (document.getElementById('fin-category'));
    if(!picked || !catSel || catSel.value===picked) return;
    catSel.value=picked;
    catSel.dispatchEvent(new Event('change',{bubbles:true}));
    csSync(catSel);
    showToast(`${tr('ai_category_suggested')} ${picked}`,'sparkle');
  }, 700);
}

// ── RECEIPT SCAN (OCR) ─────────────────────────────────────────────
// Photographs/picks a receipt image and runs it through js/receipt-ocr.js
// (on-device Tesseract.js, no network) to prefill amount + date. Never
// blocks the form — a failed/empty scan just leaves the fields as they
// were, with a toast explaining nothing was found, so the user can always
// fall back to typing the transaction in by hand.
const triggerReceiptScan = function(){
  const input=document.getElementById('fin-receipt-input');
  if(input) input.click();
};

let receiptScanInFlight=false;
/** @param {Event} e */
const handleReceiptFile = async function(e){
  const target=/** @type {HTMLInputElement} */ (e.target);
  const file=target.files && target.files[0];
  target.value=''; // allow re-picking the same photo (e.g. after a failed scan)
  if(!file || receiptScanInFlight) return;
  receiptScanInFlight=true;
  const btn=/** @type {HTMLButtonElement | null} */ (document.getElementById('fin-scan-receipt-btn'));
  const btnLabel=btn?btn.querySelector('span:last-child'):null;
  const originalLabel=btnLabel?btnLabel.textContent:'';
  if(btn) btn.disabled=true;
  // A real phone photo can take well past showToast()'s fixed 2.8s auto-hide
  // to finish recognizing (see js/receipt-ocr.js's downscale/timeout note) —
  // relying on the toast alone as "is it still working?" feedback made a
  // scan that was genuinely still running read as if nothing was happening
  // at all (reported directly by the account owner). The button's own label
  // stays swapped for the whole duration instead, a persistent indicator
  // the transient toast can't provide.
  if(btnLabel) btnLabel.textContent=tr('receipt_scan_processing');
  showToast(tr('receipt_scan_processing'),'camera');
  try{
    const {amount,date}=await scanReceiptImage(file);
    let found=false;
    if(amount!=null && Number.isFinite(amount) && amount>0){
      const amountInput=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-amount'));
      if(amountInput){ amountInput.value=String(amount); updateTransferHint(); found=true; }
    }
    if(date){
      const dateInput=/** @type {HTMLInputElement | null} */ (document.getElementById('fin-date'));
      if(dateInput){
        dateInput.value=date;
        // enhanceDateInput() (js/ui-widgets.js) only refreshes the visible
        // .dp-val label on a real 'change' event, same gotcha setTxDateToday()
        // above already works around.
        dateInput.dispatchEvent(new Event('change',{bubbles:true}));
        found=true;
      }
    }
    showToast(found?tr('receipt_scan_done'):tr('receipt_scan_not_found'), found?'check':'xmark');
  }catch(err){
    console.error(err);
    const timedOut=err instanceof Error && err.message==='receipt-ocr-timeout';
    showToast(timedOut?tr('receipt_scan_timeout'):tr('receipt_scan_fail'),'xmark');
  }finally{
    receiptScanInFlight=false;
    if(btn) btn.disabled=false;
    if(btnLabel) btnLabel.textContent=originalLabel;
  }
};
// Deliberately its own listener rather than a FIELD_ACTIONS entry below —
// FIELD_ACTIONS is dispatched from both 'change' and 'input' listeners,
// and a file input fires both on selection, which would run OCR twice.
document.addEventListener('change', e=>{
  if(e.target && /** @type {Element} */ (e.target).id==='fin-receipt-input') handleReceiptFile(e);
});

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
/** @returns {void} */
export function __init_finance__(){
// Phase 7 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// this file's own 7 dynamic onclick/onchange sites (tag filter chips, tag
// manager rows, auto-rule rows) plus 6 static index.html ones (new-tx FAB,
// tx-form cancel, open-tags-manager, add-tag, open-rules-manager,
// add-auto-rule) converted to data-action, same pattern as phases 3-6.
// Color swatches and transaction actions are data-action based now. The old
// `cancelEditTransaction` window export had zero external call sites and stays
// dropped.
// setFinanceType/addTransaction/setTxFilter's window.* used to live in
// js/color-picker.js's __init_color_picker__ (same leftover-from-the-split
// situation phase 8 found for debt.js and phase 9 found for calendar.js) -
// moved here and converted as part of phase 9, see CLAUDE.md.
/** @type {Record<string, (ds: DOMStringMap) => void>} */
const CLICK_ACTIONS = {
  'toggle-fin-tag': ds=>toggleFinTag(ds.id||''),
  'open-new-tx-modal': ()=>openNewTxModal(),
  'close-tx-modal': ()=>closeTxModal(),
  'open-tags-manager': ()=>openTagsManager(),
  'delete-tag': ds=>deleteTag(ds.id||''),
  'add-tag': ()=>addTag(),
  'open-rules-manager': ()=>openRulesManager(),
  'toggle-rule-edit': ds=>toggleRuleEdit(ds.id||''),
  'delete-auto-rule': ds=>deleteAutoRule(ds.id||''),
  'add-auto-rule': ()=>addAutoRule(),
  'set-finance-type': ds=>setFinanceType(ds.type||''),
  'set-tx-amount': ds=>setTxAmount(ds.amount),
  'set-tx-date-today': ()=>setTxDateToday(),
  'add-transaction': ()=>addTransaction(),
  'set-tx-filter': ds=>setTxFilter(ds.filter||''),
  'clear-tx-search': ()=>clearTxSearch(),
  'trigger-receipt-scan': ()=>triggerReceiptScan(),
};
document.addEventListener('click', e=>{
  const el=/** @type {HTMLElement | null} */ (/** @type {Element} */ (e.target).closest('[data-action]'));
  const action=el&&el.dataset.action;
  if(action && CLICK_ACTIONS[action]) CLICK_ACTIONS[action](el.dataset);
}, true);

/** @type {Record<string, (ds: DOMStringMap, el: HTMLInputElement) => void>} */
const FIELD_ACTIONS = {
  'update-tag': (ds,el)=>updateTag(ds.id||'', ds.field||'', el.value),
  'update-auto-rule': (ds,el)=>updateAutoRule(ds.id||'', ds.field||'', el.value),
  'set-tx-search': (ds,el)=>setTxSearch(el.value),
  'update-transfer-hint': ()=>updateTransferHint(),
  'update-comment-counter': ()=>updateCommentCounter(),
};
/** @param {Event} e */
function dispatchFinanceFieldAction(e){
  const el=/** @type {HTMLInputElement | null} */ (/** @type {Element} */ (e.target).closest('[data-action]'));
  const action=el&&el.dataset.action;
  if(action && FIELD_ACTIONS[action]) FIELD_ACTIONS[action](el.dataset, el);
}
document.addEventListener('change', dispatchFinanceFieldAction);
document.addEventListener('input', e=>{
  dispatchFinanceFieldAction(e);
});

// deleteTransaction/openNewTxModal are consumed through ES imports and
// data-action dispatch now; no CSP-sensitive window.* exports are needed here.
}
