// ── FINANCE ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { renderFinance } from './analytics-csv.js';
import { renderFinanceChart } from './calendar.js';
import { saveConfigLocal, scheduleSave } from './color-picker.js';
import { PALETTE, convertCurrency, currencySymbol, subKey, toBase, walletById, walletCurrency } from './core.js';
import { batchWriteTransactions, deleteTransactionDoc, lsKey, saveTransactionDoc } from './firebase-sync.js';
import { setCacheItem } from './privacy-cache.js';
import { uid } from './settings-managers.js';
import { csSync, enhanceSelect, escapeHtml, hexA, setupAccessibleClickableDivs, showToast, syncClickableA11yState, uiConfirm, uiPrompt } from './ui-widgets.js';

export function refreshWalletSelects(){
  ['fin-wallet','fin-wallet-target'].forEach((selId,i)=>{
    const sel=document.getElementById(selId); if(!sel) return;
    const prev=sel.value;
    sel.innerHTML='';
    AppState.wallets.forEach(w=>{const o=document.createElement('option');o.value=w.id;o.textContent=`${w.name} (${w.currency||'UAH'})`;sel.appendChild(o);});
    if(prev&&AppState.wallets.some(w=>w.id===prev)) sel.value=prev;
    else if(selId==='fin-wallet-target'&&AppState.wallets[1]) sel.value=AppState.wallets[1].id;
  });
  updateAmountLabel();
}

export function updateAmountLabel(){
  const lbl=document.getElementById('fin-amount-label'); if(!lbl) return;
  const ws=document.getElementById('fin-wallet');
  const cur=ws?walletCurrency(ws.value):'UAH';
  lbl.textContent=`${tr('finance_amount_prefix')} (${currencySymbol(cur)})`;
}

export function setFinanceType(type){
  AppState.currentFinanceType=type;
  ['inc','exp','trn'].forEach(x=>document.getElementById('btn-'+x)?.classList.remove('active'));
  document.getElementById('btn-'+{income:'inc',expense:'exp',transfer:'trn'}[type])?.classList.add('active');
  const wsl=document.getElementById('wallet-source-label');
  const tg=document.getElementById('wallet-target-group');
  const cg=document.getElementById('category-group');
  const sg=document.getElementById('subcategory-group');
  refreshWalletSelects();
  if(type==='income')  {if(wsl)wsl.textContent=tr('finance_wallet');if(tg)tg.style.display='none';if(cg)cg.style.display='flex';fillCats('income');}
  if(type==='expense') {if(wsl)wsl.textContent=tr('finance_wallet_expense');if(tg)tg.style.display='none';if(cg)cg.style.display='flex';fillCats('expense');}
  if(type==='transfer'){if(wsl)wsl.textContent=tr('finance_wallet_transfer');if(tg)tg.style.display='flex';if(cg)cg.style.display='none';if(sg)sg.style.display='none';}
  renderFinTagChips();
}

function renderFinTagChips(){
  const group=document.getElementById('tags-group');
  const box=document.getElementById('fin-tags-chips');
  if(!group||!box) return;
  if(!AppState.tags.length){ group.style.display='none'; return; }
  group.style.display='flex';
  box.innerHTML=AppState.tags.map(t=>{
    const on=AppState.selectedTagIds.includes(t.id);
    const style=on?`border-color:${t.color};background:${hexA(t.color,.18)};color:${t.color}`:'';
    return `<div class="filter-chip${on?' active':''}" style="${style}" data-action="toggle-fin-tag" data-id="${t.id}">${escapeHtml(t.name)}</div>`;
  }).join('');
  setupAccessibleClickableDivs(box);
}

const toggleFinTag = function(id){
  const i=AppState.selectedTagIds.indexOf(id);
  if(i===-1) AppState.selectedTagIds.push(id); else AppState.selectedTagIds.splice(i,1);
  renderFinTagChips();
};

export function fillCats(type){
  const sel=document.getElementById('fin-category');if(!sel)return;
  const prev=sel.value;
  sel.innerHTML='';
  (AppState.categories[type]||[]).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o);});
  if(prev&&(AppState.categories[type]||[]).includes(prev)) sel.value=prev;
  fillSubcats();
}

export function fillSubcats(){
  const sel=document.getElementById('fin-subcategory');
  const group=document.getElementById('subcategory-group');
  if(!sel||!group) return;
  if(AppState.currentFinanceType==='transfer'){ group.style.display='none'; return; }
  const catSel=document.getElementById('fin-category');
  const cat=catSel?catSel.value:'';
  const subs=AppState.subcategories[subKey(AppState.currentFinanceType,cat)]||[];
  const prev=sel.value;
  sel.innerHTML='<option value="">—</option>'+subs.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join('');
  if(prev&&subs.includes(prev)) sel.value=prev;
  group.style.display = subs.length ? 'flex' : 'none';
}

function newTransactionId(){
  try{ if(crypto&&crypto.randomUUID) return crypto.randomUUID(); }catch(e){}
  return uid('tx');
}

function sameTxId(a,b){ return String(a)===String(b); }

const TX_AMOUNT_MAX=1000000000;
const TX_COMMENT_MAX=500;
const TX_DATE_RE=/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/;

function readTransactionForm(){
  const ws=document.getElementById('fin-wallet')?.value||(AppState.wallets[0]&&AppState.wallets[0].id)||'';
  const wt=document.getElementById('fin-wallet-target')?.value||(AppState.wallets[1]&&AppState.wallets[1].id)||'';
  const amount=Number(document.getElementById('fin-amount')?.value);
  const date=document.getElementById('fin-date')?.value||'';
  const cat=AppState.currentFinanceType==='transfer'?'Внутрішній переказ':(document.getElementById('fin-category')?.value||'Інше');
  const sub=AppState.currentFinanceType==='transfer'?null:(document.getElementById('fin-subcategory')?.value||null);
  const comment=document.getElementById('fin-comment')?.value.trim()||'';
  return {amount,date,ws,wt,cat,sub,comment};
}

function validateTransactionDraft(draft){
  if(!Number.isFinite(draft.amount)||draft.amount<=0) return 'finance_err_amount';
  if(draft.amount>=TX_AMOUNT_MAX) return 'finance_err_amount_large';
  if(!draft.date) return 'finance_err_date';
  if(!TX_DATE_RE.test(draft.date)) return 'finance_err_date_format';
  if(!draft.ws) return 'finance_err_wallet';
  if(draft.comment.length>TX_COMMENT_MAX) return 'finance_err_comment_long';
  if(String(draft.cat||'').length>120 || String(draft.sub||'').length>120) return 'finance_err_field_long';
  if(AppState.currentFinanceType==='transfer'){
    if(!draft.wt) return 'finance_err_wallet';
    if(draft.ws===draft.wt) return 'finance_err_same_wallet';
  }
  return '';
}

export async function addTransaction(){
  const ai=document.getElementById('fin-amount');
  const draft=readTransactionForm();
  const errKey=validateTransactionDraft(draft);
  if(errKey){showToast(tr(errKey),'xmark');return;}
  const {amount,date,ws,wt,cat,sub,comment}=draft;
  const srcCur=walletCurrency(ws);
  let targetAmount=null, targetCurrency=null;
  if(AppState.currentFinanceType==='transfer'){
    targetCurrency=walletCurrency(wt);
    targetAmount=convertCurrency(amount, srcCur, targetCurrency);
    if(!Number.isFinite(targetAmount)||targetAmount<=0||targetAmount>=TX_AMOUNT_MAX){showToast(tr('finance_err_amount_large'),'xmark');return;}
  }
  if(AppState.editingTxId!=null){
    const t=AppState.transactions.find(x=>sameTxId(x.id,AppState.editingTxId));
    if(t) Object.assign(t,{type:AppState.currentFinanceType,amount,currency:srcCur,category:cat,subcategory:sub,tags:AppState.selectedTagIds.slice(),wallet:ws,targetWallet:AppState.currentFinanceType==='transfer'?wt:null,targetAmount,targetCurrency,date,comment});
    cancelEditTransaction();
    const txKey=lsKey('tx'); if(txKey) setCacheItem(txKey,JSON.stringify(AppState.transactions));
    // Writes straight to this transaction's own subcollection doc rather
    // than scheduleSave()'s whole-finance-doc rewrite — see
    // js/firebase-sync.js's TRANSACTIONS SUBCOLLECTION section.
    if(t) saveTransactionDoc(t).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
    renderFinance(); renderFinanceChart();
    const m1=document.getElementById('tx-form-modal'); if(m1) m1.style.display='none';
    showToast(tr('toast_tx_updated'),'check');
    return;
  }
  const newTx={id:newTransactionId(),createdAt:Date.now(),type:AppState.currentFinanceType,amount,currency:srcCur,category:cat,subcategory:sub,tags:AppState.selectedTagIds.slice(),wallet:ws,targetWallet:AppState.currentFinanceType==='transfer'?wt:null,targetAmount,targetCurrency,date,comment};
  AppState.transactions.unshift(newTx);
  const txKey=lsKey('tx'); if(txKey) setCacheItem(txKey,JSON.stringify(AppState.transactions));
  saveTransactionDoc(newTx).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
  if(ai)ai.value='';
  const ci=document.getElementById('fin-comment');if(ci)ci.value='';
  AppState.selectedTagIds=[]; renderFinTagChips();
  renderFinance(); renderFinanceChart();
  const m2=document.getElementById('tx-form-modal'); if(m2) m2.style.display='none';

  let toastMsg=AppState.currentFinanceType==='transfer'?tr('toast_transfer_done'):tr('toast_tx_added');
  let toastIcon=AppState.currentFinanceType==='transfer'?'swap':'check';
  if(AppState.currentFinanceType==='expense' && AppState.budgets[cat]>0){
    const now=new Date();
    const mPrefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
    if(date.startsWith(mPrefix)){
      const limit=AppState.budgets[cat];
      const spent=AppState.transactions.reduce((s,t)=>(t.type==='expense'&&t.category===cat&&t.date&&t.date.startsWith(mPrefix))?s+toBase(t.amount,t.currency||'UAH'):s,0);
      if(spent>=limit){ toastMsg=`Бюджет «${cat}» перевищено: ${spent.toLocaleString('uk-UA')}/${limit.toLocaleString('uk-UA')} грн`; toastIcon='warning'; }
      else if(spent>=limit*0.9){ toastMsg=`Бюджет «${cat}»: ${Math.round(spent/limit*100)}% витрачено`; toastIcon='warning'; }
    }
  }
  showToast(toastMsg, toastIcon);
}

export async function deleteTransaction(id){
  if(!(await uiConfirm(tr('finance_delete_confirm'),{title:tr('finance_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.transactions=AppState.transactions.filter(t=>!sameTxId(t.id,id));
  const txKey=lsKey('tx'); if(txKey) setCacheItem(txKey,JSON.stringify(AppState.transactions));
  deleteTransactionDoc(id).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
  renderFinance(); renderFinanceChart();
}

export const editTransaction = function(id){
  const t=AppState.transactions.find(x=>sameTxId(x.id,id)); if(!t) return;
  AppState.editingTxId=id;
  setFinanceType(t.type);

  const wsel=document.getElementById('fin-wallet');
  if(wsel){ wsel.value=t.wallet; wsel.dispatchEvent(new Event('change',{bubbles:true})); }
  if(t.type==='transfer'){
    const wtsel=document.getElementById('fin-wallet-target');
    if(wtsel){ wtsel.value=t.targetWallet; wtsel.dispatchEvent(new Event('change',{bubbles:true})); }
  } else {
    const catsel=document.getElementById('fin-category');
    if(catsel){ catsel.value=t.category; catsel.dispatchEvent(new Event('change',{bubbles:true})); }
    const subsel=document.getElementById('fin-subcategory');
    if(subsel){ subsel.value=t.subcategory||''; subsel.dispatchEvent(new Event('change',{bubbles:true})); }
  }
  const ai=document.getElementById('fin-amount'); if(ai) ai.value=t.amount;
  const dsel=document.getElementById('fin-date');
  if(dsel){ dsel.value=t.date||''; dsel.dispatchEvent(new Event('change',{bubbles:true})); }
  const ci=document.getElementById('fin-comment'); if(ci) ci.value=t.comment||'';
  AppState.selectedTagIds=(t.tags||[]).slice(); renderFinTagChips();

  const titleText=document.getElementById('fin-form-title-text'); if(titleText) titleText.textContent=tr('finance_edit_title');
  const submitBtn=document.getElementById('fin-submit-btn'); if(submitBtn) submitBtn.textContent=tr('finance_save_changes');
  const cancelBtn=document.getElementById('fin-cancel-edit-btn'); if(cancelBtn) cancelBtn.style.display='inline-block';
  const m=document.getElementById('tx-form-modal'); if(m) m.style.display='flex';
};

const cancelEditTransaction = function(){
  AppState.editingTxId=null;
  const ai=document.getElementById('fin-amount'); if(ai) ai.value='';
  const ci=document.getElementById('fin-comment'); if(ci) ci.value='';
  AppState.selectedTagIds=[]; renderFinTagChips();
  const titleText=document.getElementById('fin-form-title-text'); if(titleText) titleText.textContent=tr('finance_new_tx');
  const submitBtn=document.getElementById('fin-submit-btn'); if(submitBtn) submitBtn.textContent=tr('finance_add_btn');
  const cancelBtn=document.getElementById('fin-cancel-edit-btn'); if(cancelBtn) cancelBtn.style.display='none';
};

const openNewTxModal = function(){
  cancelEditTransaction();
  const m=document.getElementById('tx-form-modal'); if(m) m.style.display='flex';
};

const closeTxModal = function(){
  cancelEditTransaction();
  const m=document.getElementById('tx-form-modal'); if(m) m.style.display='none';
};

export function setTxSearch(value){
  AppState.txSearch=String(value||'').trim().toLowerCase();
  renderFinance();
}

export function setTxFilter(f){
  AppState.txFilter=f;
  document.querySelectorAll('.filter-chip').forEach(c=>{
    c.classList.toggle('active',c.dataset.filter===f);
  });
  syncClickableA11yState(document.getElementById('tab-finance'));
  renderFinance();
}

export function walletBadge(id){
  const w=walletById(id);
  const name=w?w.name:'—';
  const color=w?(w.color||'#8b5cf6'):'#7b709a';
  const icon=w?(w.icon||'card'):'card';
  return `<span class="wallet-tag" style="background:${hexA(color,.12)};color:${color};border:1px solid ${hexA(color,.28)}">${window.Icon(icon)}<span class="wallet-tag-name">${escapeHtml(name)}</span></span>`;
}

export function tagBadge(id){
  const t=AppState.tags.find(x=>x.id===id);
  if(!t) return '';
  return `<span class="wallet-tag" style="background:${hexA(t.color,.12)};color:${t.color};border:1px solid ${hexA(t.color,.28)}">${window.Icon('tag')}<span class="wallet-tag-name">${escapeHtml(t.name)}</span></span>`;
}

const openTagsManager = function(){
  renderTagsList();
  document.getElementById('tags-modal').style.display='flex';
};

function renderTagsList(){
  const box=document.getElementById('tags-list'); if(!box) return;
  box.innerHTML='';
  if(!AppState.tags.length){ box.innerHTML=`<div class="mgr-empty">${tr('tags_empty')}</div>`; return; }
  AppState.tags.forEach(t=>{
    const row=document.createElement('div');
    row.className='mgr-row';
    row.innerHTML=`
      <button type="button" class="mgr-color" style="background:${escapeHtml(t.color||'#8b5cf6')}" data-action="open-color-picker" data-kind="tag" data-id="${t.id}"></button>
      <input type="text" class="mgr-name-inline" value="${escapeHtml(t.name)}" placeholder="${tr('common_name')}" data-action="update-tag" data-id="${t.id}" data-field="name">
      <button class="mgr-del" data-action="delete-tag" data-id="${t.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>`;
    box.appendChild(row);
  });
}

export const updateTag = function(id,field,value){
  const t=AppState.tags.find(x=>x.id===id); if(!t) return;
  if(field==='name') t.name=String(value).trim()||tr('tags_default_name');
  else t[field]=value;
  saveConfigLocal(); scheduleSave();
  renderFinTagChips(); renderFinance();
};

const addTag = async function(){
  const name=await uiPrompt(tr('tags_add_prompt'),'',tr('tags_add_title'));
  if(name===null) return;
  const clean=name.trim(); if(!clean) return;
  const color=PALETTE[AppState.tags.length%PALETTE.length];
  AppState.tags.push({id:uid('tag'), name:clean, color});
  saveConfigLocal(); scheduleSave();
  renderTagsList(); renderFinTagChips();
};

const deleteTag = async function(id){
  if(!(await uiConfirm(tr('tags_delete_confirm'),{title:tr('tags_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.tags=AppState.tags.filter(t=>t.id!==id);
  AppState.selectedTagIds=AppState.selectedTagIds.filter(tid=>tid!==id);
  const affected=[];
  AppState.transactions.forEach(t=>{ if(Array.isArray(t.tags)&&t.tags.includes(id)){ t.tags=t.tags.filter(tid=>tid!==id); affected.push(t); } });
  saveConfigLocal();
  const tk=lsKey('tx'); if(tk) setCacheItem(tk,JSON.stringify(AppState.transactions));
  // tags[] itself is a finance-doc field (needs scheduleSave()); the
  // individual transactions that referenced this tag are their own
  // subcollection docs and get updated directly instead.
  scheduleSave();
  if(affected.length) batchWriteTransactions(affected).catch(e=>{ console.error(e); showToast(tr('sync_autosave_error'),'xmark'); });
  renderTagsList(); renderFinTagChips(); renderFinance();
};

const openRulesManager = function(){
  renderAutoRulesList();
  document.getElementById('rules-modal').style.display='flex';
};

const toggleRuleEdit = function(id){
  AppState.expandedRuleId = AppState.expandedRuleId===id ? null : id;
  renderAutoRulesList();
};

// Compact-manager-row pattern (icon badge + two-line summary + pencil
// toggle that reveals the full field set, same shape as
// renderShiftTypesList()/renderCategoriesList()) — replaces the old
// always-expanded .debt-row stack of labeled fields, see CLAUDE.md's
// "Unify manager design" note.
function renderAutoRulesList(){
  const box=document.getElementById('rules-list'); if(!box) return;
  box.innerHTML='';
  if(!AppState.autoRules.length){ box.innerHTML=`<div class="mgr-empty">${tr('rules_empty')}</div>`; return; }
  AppState.autoRules.forEach(r=>{
    const catList=AppState.categories[r.type]||[];
    const open=AppState.expandedRuleId===r.id;
    const typeLabel=r.type==='income'?tr('cat_income'):tr('cat_expense');
    const summary=r.keyword ? `"${escapeHtml(r.keyword)}" → ${escapeHtml(r.category||'')}` : tr('rules_keyword_placeholder');
    const row=document.createElement('div');
    row.className='mgr-row';
    row.style.cssText='flex-direction:column;align-items:stretch;gap:10px';
    row.innerHTML=`
      <div class="cat-row">
        <div class="icon-badge icon-badge-sm" style="background:var(--purple)">${window.Icon('sparkle')}</div>
        <div class="cat-row-body" style="cursor:default">
          <span class="cat-row-name">${summary}</span>
          <span class="cat-row-sub">${typeLabel}</span>
        </div>
        <button type="button" class="mgr-edit${open?' active':''}" data-action="toggle-rule-edit" data-id="${r.id}" aria-label="${tr('common_edit')}">${window.Icon(open?'xmark':'pencil')}</button>
        <button class="mgr-del" data-action="delete-auto-rule" data-id="${r.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
      </div>
      ${open?`
      <div style="display:flex;flex-direction:column;gap:8px;padding-top:6px;border-top:1px dashed var(--border)">
        <div class="mgr-field"><span class="mgr-field-label">${tr('recurring_type')}</span>
          <select data-action="update-auto-rule" data-id="${r.id}" data-field="type">
            <option value="expense" ${r.type==='expense'?'selected':''}>${tr('cat_expense')}</option>
            <option value="income" ${r.type==='income'?'selected':''}>${tr('cat_income')}</option>
          </select>
        </div>
        <div class="mgr-field"><span class="mgr-field-label">${tr('rules_keyword')}</span>
          <input type="text" class="mgr-name" value="${escapeHtml(r.keyword||'')}" placeholder="${tr('rules_keyword_placeholder')}" data-action="update-auto-rule" data-id="${r.id}" data-field="keyword">
        </div>
        <div class="mgr-field"><span class="mgr-field-label">${tr('finance_category')}</span>
          <select data-action="update-auto-rule" data-id="${r.id}" data-field="category">
            ${catList.map(c=>`<option value="${escapeHtml(c)}" ${r.category===c?'selected':''}>${escapeHtml(c)}</option>`).join('')}
          </select>
        </div>
      </div>`:''}`;
    box.appendChild(row);
    row.querySelectorAll('select').forEach(enhanceSelect);
  });
}

const updateAutoRule = function(id,field,value){
  const r=AppState.autoRules.find(x=>x.id===id); if(!r) return;
  if(field==='type'){ r.type=value; r.category=(AppState.categories[value]||[])[0]||''; }
  else r[field]=value;
  saveConfigLocal(); scheduleSave();
  renderAutoRulesList();
};

const addAutoRule = function(){
  const type='expense';
  const category=(AppState.categories.expense||[])[0]||'';
  AppState.autoRules.push({id:uid('rule'), type, keyword:'', category});
  saveConfigLocal(); scheduleSave();
  renderAutoRulesList();
};

const deleteAutoRule = async function(id){
  if(!(await uiConfirm(tr('rules_delete_confirm'),{title:tr('rules_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.autoRules=AppState.autoRules.filter(r=>r.id!==id);
  saveConfigLocal(); scheduleSave();
  renderAutoRulesList();
};

function findMatchingRule(type, comment){
  if(!comment) return null;
  const lc=comment.toLowerCase();
  return AppState.autoRules.find(r=>r.type===type && r.keyword && lc.includes(r.keyword.toLowerCase())) || null;
}

export function applyAutoRuleToForm(){
  if(AppState.currentFinanceType==='transfer') return;
  const ci=document.getElementById('fin-comment');
  const rule=findMatchingRule(AppState.currentFinanceType, ci?ci.value:'');
  if(!rule) return;
  const catSel=document.getElementById('fin-category');
  if(!catSel || catSel.value===rule.category) return;
  if(!(AppState.categories[AppState.currentFinanceType]||[]).includes(rule.category)) return;
  catSel.value=rule.category;
  catSel.dispatchEvent(new Event('change',{bubbles:true}));
  csSync(catSel);
  showToast(`${tr('rules_auto_applied')} ${rule.category}`,'sparkle');
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_finance__(){
// Phase 7 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// this file's own 7 dynamic onclick/onchange sites (tag filter chips, tag
// manager rows, auto-rule rows) plus 6 static index.html ones (new-tx FAB,
// tx-form cancel, open-tags-manager, add-tag, open-rules-manager,
// add-auto-rule) converted to data-action, same pattern as phases 3-6.
// `openColorPicker(...)` in renderTagsList() stays inline onclick — owned
// by color-picker.js, a separate target. `cancelEditTransaction` had zero
// external call sites (window-exposed but never actually referenced from
// index.html or any onclick) — dropped entirely rather than converted.
// setFinanceType/addTransaction/setTxFilter's window.* used to live in
// js/color-picker.js's __init_color_picker__ (same leftover-from-the-split
// situation phase 8 found for debt.js and phase 9 found for calendar.js) -
// moved here and converted as part of phase 9, see CLAUDE.md.
const CLICK_ACTIONS = {
  'toggle-fin-tag': ds=>toggleFinTag(ds.id),
  'open-new-tx-modal': ()=>openNewTxModal(),
  'close-tx-modal': ()=>closeTxModal(),
  'open-tags-manager': ()=>openTagsManager(),
  'delete-tag': ds=>deleteTag(ds.id),
  'add-tag': ()=>addTag(),
  'open-rules-manager': ()=>openRulesManager(),
  'toggle-rule-edit': ds=>toggleRuleEdit(ds.id),
  'delete-auto-rule': ds=>deleteAutoRule(ds.id),
  'add-auto-rule': ()=>addAutoRule(),
  'set-finance-type': ds=>setFinanceType(ds.type),
  'add-transaction': ()=>addTransaction(),
  'set-tx-filter': ds=>setTxFilter(ds.filter),
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);

const FIELD_ACTIONS = {
  'update-tag': (ds,el)=>updateTag(ds.id, ds.field, el.value),
  'update-auto-rule': (ds,el)=>updateAutoRule(ds.id, ds.field, el.value),
  'set-tx-search': (ds,el)=>setTxSearch(el.value),
};
function dispatchFinanceFieldAction(e){
  const el=e.target.closest('[data-action]');
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el);
}
document.addEventListener('change', dispatchFinanceFieldAction);
document.addEventListener('input', e=>{
  const el=e.target.closest('[data-action="set-tx-search"]');
  if(el) setTxSearch(el.value);
});

// Still window-exposed: js/analytics-csv.js's transaction-row template
// calls both by a literal onclick/string reference (.tx-swipe-delete's
// onclick="event.stopPropagation();deleteTransaction(...)" and the
// onboarding-checklist/start-guide's onclick="openNewTxModal()"), a
// separate, still-untouched target. editTransaction no longer needs this -
// its one remaining caller (the .tx-item click listener in
// analytics-csv.js) is a real addEventListener callback, not an onclick
// string, so the real `import { editTransaction }` there is enough.
window.deleteTransaction = deleteTransaction;
window.openNewTxModal = openNewTxModal;
}
