// ── FIREBASE-SYNC ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { DCOL, db, doc, getDoc, setDoc } from './core.js';

// ── FIREBASE ──────────────────────────────────────────────────
// All cloud data lives under users/{uid}/max_tracker/{doc} so accounts
// never see or overwrite each other's shifts/finances/debts. Firestore
// security rules (see firestore.rules) must enforce this server-side —
// this path scoping alone is only a client-side convention.
// The default profile keeps the original unsuffixed doc names/ls keys
// (zero migration for existing users); any other profile's docs/keys get
// a "@<profileId>" suffix. profiles_meta itself is account-wide, never
// suffixed. See switchProfile()/loadActiveProfileId() for activeProfileId.
export function userDoc(name){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  const docName = (name!=='profiles_meta' && AppState.activeProfileId && AppState.activeProfileId!=='default') ? `${name}@${AppState.activeProfileId}` : name;
  return doc(db,'users',AppState.currentUser.uid,DCOL,docName);
}
export function lsKey(name){
  if(!AppState.currentUser) return null;
  return (AppState.activeProfileId && AppState.activeProfileId!=='default') ? `mx_${name}_${AppState.currentUser.uid}_${AppState.activeProfileId}` : `mx_${name}_${AppState.currentUser.uid}`;
}
export function activeProfileLsKey(){
  return AppState.currentUser ? `mx_activeProfile_${AppState.currentUser.uid}` : null;
}
export function loadActiveProfileId(){
  try{
    const k=activeProfileLsKey(); const v=k&&localStorage.getItem(k);
    AppState.activeProfileId = v || 'default';
  }catch(e){ AppState.activeProfileId='default'; }
}
// Account-wide list of switchable data-profiles (name + id only — each
// profile's own nickname/avatar lives inside its own finance doc via the
// existing profile.nickname/profile.avatar, see PROFILE section below).
export async function loadProfilesMeta(){
  const snap=await getDoc(userDoc('profiles_meta'));
  if(snap.exists() && Array.isArray(snap.data().list) && snap.data().list.length){
    AppState.profilesMeta=snap.data();
  }else{
    AppState.profilesMeta={list:[{id:'default', name:tr('profiles_default_name'), createdAt:Date.now()}], updatedAt:Date.now()};
    await setDoc(userDoc('profiles_meta'), AppState.profilesMeta, {merge:false});
  }
  // If the locally-remembered active profile was deleted on another device,
  // fall back to the first available profile rather than loading nothing.
  if(!AppState.profilesMeta.list.some(p=>p.id===AppState.activeProfileId)){
    AppState.activeProfileId=AppState.profilesMeta.list[0].id;
    try{ const k=activeProfileLsKey(); if(k) localStorage.setItem(k, AppState.activeProfileId); }catch(e){}
  }
}
export async function saveProfilesMeta(){
  AppState.profilesMeta.updatedAt=Date.now();
  await setDoc(userDoc('profiles_meta'), AppState.profilesMeta, {merge:false});
}
