// ── FIREBASE-SYNC ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { DCOL, collection, db, deleteDoc, doc, getDoc, getDocs, setDoc, writeBatch } from './core.js';

// ── FIREBASE ──────────────────────────────────────────────────
// All cloud data lives under users/{uid}/max_tracker/{doc} so accounts
// never see or overwrite each other's shifts/finances/debts. Firestore
// security rules (see firestore.rules) must enforce this server-side —
// this path scoping alone is only a client-side convention.
// The default profile keeps the original unsuffixed doc names/ls keys
// (zero migration for existing users); any other profile's docs/keys get
// a "@<profileId>" suffix. profiles_meta itself is account-wide, never
// suffixed. See switchProfile()/loadActiveProfileId() for activeProfileId.
export function userDoc(name){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  const docName = (name!=='profiles_meta' && AppState.activeProfileId && AppState.activeProfileId!=='default') ? `${name}@${AppState.activeProfileId}` : name;
  return doc(db,'users',AppState.currentUser.uid,DCOL,docName);
}
export function lsKey(name){
  if(!AppState.currentUser) return null;
  return (AppState.activeProfileId && AppState.activeProfileId!=='default') ? `mx_${name}_${AppState.currentUser.uid}_${AppState.activeProfileId}` : `mx_${name}_${AppState.currentUser.uid}`;
}
export function activeProfileLsKey(){
  return AppState.currentUser ? `mx_activeProfile_${AppState.currentUser.uid}` : null;
}
export function loadActiveProfileId(){
  try{
    const k=activeProfileLsKey(); const v=k&&localStorage.getItem(k);
    AppState.activeProfileId = v || 'default';
  }catch(e){ AppState.activeProfileId='default'; }
}
// Account-wide list of switchable data-profiles (name + id only — each
// profile's own nickname/avatar lives inside its own finance doc via the
// existing profile.nickname/profile.avatar, see PROFILE section below).
export async function loadProfilesMeta(){
  const snap=await getDoc(userDoc('profiles_meta'));
  if(snap.exists() && Array.isArray(snap.data().list) && snap.data().list.length){
    AppState.profilesMeta=snap.data();
  }else{
    AppState.profilesMeta={list:[{id:'default', name:tr('profiles_default_name'), createdAt:Date.now()}], updatedAt:Date.now()};
    await setDoc(userDoc('profiles_meta'), AppState.profilesMeta, {merge:false});
  }
  // If the locally-remembered active profile was deleted on another device,
  // fall back to the first available profile rather than loading nothing.
  if(!AppState.profilesMeta.list.some(p=>p.id===AppState.activeProfileId)){
    AppState.activeProfileId=AppState.profilesMeta.list[0].id;
    try{ const k=activeProfileLsKey(); if(k) localStorage.setItem(k, AppState.activeProfileId); }catch(e){}
  }
}
export async function saveProfilesMeta(){
  AppState.profilesMeta.updatedAt=Date.now();
  await setDoc(userDoc('profiles_meta'), AppState.profilesMeta, {merge:false});
}

// ── TRANSACTIONS SUBCOLLECTION ─────────────────────────────────
// users/{uid}/max_tracker/{financeDocName}/transactions/{txId} — see
// MIGRATION_PLAN_transactions.md and CLAUDE.md's Firebase data model
// section for why this replaced the old finance.data array: every
// fbSaveNow() used to rewrite the *entire* transaction history on every
// single add/edit/delete, which is both the 1 MiB doc-size risk and the
// coarse per-document optimistic-concurrency conflict the plan describes.
// Pre-launch (no real users yet, see CLAUDE.md's Operating conventions)
// made a direct cutover practical instead of the originally-planned
// cautious dual-write/dual-read rollout — there's no live user base whose
// in-flight saves a phased migration would need to protect.
export function txCollection(){
  return collection(userDoc('finance'), 'transactions');
}
export function txDocRef(id){
  return doc(txCollection(), String(id));
}
export async function saveTransactionDoc(t){
  await setDoc(txDocRef(t.id), t, {merge:false});
}
export async function deleteTransactionDoc(id){
  await deleteDoc(txDocRef(id));
}
export async function loadTransactionsFromSubcollection(){
  const snap=await getDocs(txCollection());
  const out=[];
  snap.forEach(d=>out.push(d.data()));
  return out;
}
// Firestore write batches cap at 500 ops; chunked well under that so this
// stays correct even for a very long transaction history.
const BATCH_CHUNK=450;
export async function batchWriteTransactions(txs){
  for(let i=0;i<txs.length;i+=BATCH_CHUNK){
    const batch=writeBatch(db);
    txs.slice(i,i+BATCH_CHUNK).forEach(t=>batch.set(txDocRef(t.id), t));
    await batch.commit();
  }
}
export async function batchDeleteTransactionsByIds(ids){
  for(let i=0;i<ids.length;i+=BATCH_CHUNK){
    const batch=writeBatch(db);
    ids.slice(i,i+BATCH_CHUNK).forEach(id=>batch.delete(txDocRef(id)));
    await batch.commit();
  }
}
// Deletes every doc in the transactions subcollection — Firestore never
// cascade-deletes a subcollection when its parent doc is deleted, so
// account deletion (js/auth.js's deleteAccountUser()) has to do this
// explicitly or it would leave an orphaned subcollection behind.
export async function deleteAllTransactionDocs(){
  const snap=await getDocs(txCollection());
  const ids=[]; snap.forEach(d=>ids.push(d.id));
  if(ids.length) await batchDeleteTransactionsByIds(ids);
}
