// @ts-check
// ── FIREBASE-SYNC ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { DCOL, arrayRemove, arrayUnion, collection, db, deleteDoc, doc, getDoc, getDocs, setDoc, updateDoc, writeBatch } from './core.js';

// ── FIREBASE ──────────────────────────────────────────────────
// All cloud data lives under users/{uid}/max_tracker/{doc} so accounts
// never see or overwrite each other's shifts/finances/debts. Firestore
// security rules (see firestore.rules) must enforce this server-side —
// this path scoping alone is only a client-side convention.
// The default profile keeps the original unsuffixed doc names/ls keys
// (zero migration for existing users); any other profile's docs/keys get
// a "@<profileId>" suffix. profiles_meta itself is account-wide, never
// suffixed. See switchProfile()/loadActiveProfileId() for activeProfileId.
// activeProfileOwnerUid (see state.js) redirects this at whichever
// account actually owns the active profile's data — set only while
// viewing a *shared* profile (see the SHARED PROFILES section below).
/** @param {string} name */
export function userDoc(name){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  if(name==='profiles_meta') return doc(db,'users',AppState.currentUser.uid,DCOL,'profiles_meta');
  const ownerUid = AppState.activeProfileOwnerUid || AppState.currentUser.uid;
  const docName = (AppState.activeProfileId && AppState.activeProfileId!=='default') ? `${name}@${AppState.activeProfileId}` : name;
  return doc(db,'users',ownerUid,DCOL,docName);
}
/**
 * @param {string} name
 * @returns {string | null}
 */
export function lsKey(name){
  if(!AppState.currentUser) return null;
  // Shared-profile data is never cached locally — it isn't this account's
  // own uid-namespaced storage, and the profile can gain/lose members from
  // other devices at any time, so always loading fresh from Firestore is
  // simpler and safer than reasoning about cache invalidation across
  // accounts. Every existing lsKey() call site already handles a null key
  // (falls back to skipping the cache read/write), so this needs no
  // caller changes.
  if(AppState.activeProfileOwnerUid) return null;
  return (AppState.activeProfileId && AppState.activeProfileId!=='default') ? `mx_${name}_${AppState.currentUser.uid}_${AppState.activeProfileId}` : `mx_${name}_${AppState.currentUser.uid}`;
}
/** @returns {string | null} */
export function activeProfileLsKey(){
  return AppState.currentUser ? `mx_activeProfile_${AppState.currentUser.uid}` : null;
}
// Stored as "profileId" for one of this account's own profiles, or
// "ownerUid|profileId" for a shared profile someone else owns.
/** @returns {void} */
export function loadActiveProfileId(){
  try{
    const k=activeProfileLsKey(); const v=k&&localStorage.getItem(k);
    if(v && v.includes('|')){
      const [ownerUid,profileId]=v.split('|');
      AppState.activeProfileOwnerUid=ownerUid; AppState.activeProfileId=profileId;
    }else{
      AppState.activeProfileOwnerUid=null; AppState.activeProfileId=v || 'default';
    }
  }catch(e){ AppState.activeProfileOwnerUid=null; AppState.activeProfileId='default'; }
}
/** @returns {void} */
export function saveActiveProfileId(){
  try{
    const k=activeProfileLsKey();
    if(k) localStorage.setItem(k, AppState.activeProfileOwnerUid ? `${AppState.activeProfileOwnerUid}|${AppState.activeProfileId}` : AppState.activeProfileId);
  }catch(e){}
}
// Account-wide list of switchable data-profiles (name + id only — each
// profile's own nickname/avatar lives inside its own finance doc via the
// existing profile.nickname/profile.avatar, see PROFILE section below).
// A shared-profile reference (kind:'shared') additionally carries the
// owning account's uid — see the SHARED PROFILES section below.
/** @returns {Promise<void>} */
export async function loadProfilesMeta(){
  const snap=await getDoc(userDoc('profiles_meta'));
  if(snap.exists() && Array.isArray(snap.data().list) && snap.data().list.length){
    AppState.profilesMeta=/** @type {typeof AppState.profilesMeta} */ (snap.data());
  }else{
    AppState.profilesMeta={list:[{id:'default', name:tr('profiles_default_name'), createdAt:Date.now()}], updatedAt:Date.now()};
    await setDoc(userDoc('profiles_meta'), AppState.profilesMeta, {merge:false});
  }
  // If the locally-remembered active profile was deleted (or, for a shared
  // profile, this account was removed from it) on another device, fall
  // back to the first available profile rather than loading nothing.
  const stillExists = AppState.activeProfileOwnerUid
    ? AppState.profilesMeta.list.some(p=>p.id===AppState.activeProfileId && p.kind==='shared' && p.ownerUid===AppState.activeProfileOwnerUid)
    : AppState.profilesMeta.list.some(p=>p.id===AppState.activeProfileId && p.kind!=='shared');
  if(!stillExists){
    const first=AppState.profilesMeta.list[0];
    AppState.activeProfileId=first.id;
    AppState.activeProfileOwnerUid=first.kind==='shared'?first.ownerUid:null;
    saveActiveProfileId();
  }
}
/** @returns {Promise<void>} */
export async function saveProfilesMeta(){
  AppState.profilesMeta.updatedAt=Date.now();
  await setDoc(userDoc('profiles_meta'), AppState.profilesMeta, {merge:false});
}

// ── SHARED PROFILES ─────────────────────────────────────
// Lets a second Firebase Auth account read/write one of this account's
// existing profiles (shifts/finance/debt, including the transactions
// subcollection) — for a couple sharing one household's finances, not a
// general multi-tenant model. Deliberately reuses the *existing*
// users/{uid}/max_tracker/{doc}@{profileId} tree instead of a parallel
// data model: the owner's side of a shared profile is stored and behaves
// exactly like a normal profile of theirs (userDoc()/txCollection() above
// already redirect to it via activeProfileOwnerUid — nothing about the
// read/write/render paths needed to change for the owner's own account).
// See firestore.rules' matching "SHARED PROFILES helpers" comment for the
// full security design and CLAUDE.md's "Shared profiles" section for the
// rationale writeup.
//
// Joining is invite-code based, never open self-join: profile_invites/{code}
// (top-level, not nested — a joining user has no relationship to the
// owner's account yet, so has to be able to read this before anything
// else) holds {ownerUid, profileId, profileName, createdBy, createdAt,
// expiresAt, usedBy}. Redeeming one is a genuine two-step, rules-enforced
// sequence, not a single write: first mark the invite used (only possible
// while usedBy is still null and it hasn't expired), then — only that
// then unlocks it — join users/{ownerUid}/max_tracker/shared_members@
// {profileId} by presenting the now-redeemed code. See firestore.rules
// for exactly what each step's rule checks; tests/firestore-rules.mjs
// exercises the full lifecycle against a real emulator, not just each
// rule branch in isolation.
const INVITE_CODE_ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I - unambiguous to read aloud or type
function generateInviteCode(){
  let s='';
  for(let i=0;i<8;i++) s+=INVITE_CODE_ALPHABET[Math.floor(Math.random()*INVITE_CODE_ALPHABET.length)];
  return s;
}
const INVITE_TTL_MS=24*60*60*1000;

// Turns the current profile into a shared one (idempotent — calling it
// again on an already-shared profile just issues a fresh invite code)
// and returns a code to hand to whoever should join. Can only be called
// while viewing one of *this account's own* profiles, never someone
// else's shared profile.
/** @returns {Promise<string>} the invite code */
export async function shareCurrentProfile(){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  if(AppState.activeProfileOwnerUid) throw new Error('cannot share a profile you do not own');
  const membersRef=userDoc('shared_members');
  const snap=await getDoc(membersRef);
  if(!snap.exists()){
    await setDoc(membersRef, {members:[AppState.currentUser.uid], updatedAt:Date.now()}, {merge:false});
  }
  const profile=AppState.profilesMeta.list.find(p=>p.id===AppState.activeProfileId);
  const code=generateInviteCode();
  await setDoc(doc(db,'profile_invites',code), {
    ownerUid: AppState.currentUser.uid,
    createdBy: AppState.currentUser.uid,
    profileId: AppState.activeProfileId,
    profileName: (profile&&profile.name)||'',
    createdAt: Date.now(),
    expiresAt: Date.now()+INVITE_TTL_MS,
    usedBy: null,
  }, {merge:false});
  return code;
}

// Redeems an invite code: the two-write sequence described above, then
// adds a {kind:'shared', ownerUid} reference to this account's own
// profilesMeta so it shows up in the profile switcher alongside local
// profiles. Returns {ok:false, reason} for every rejected case (unknown/
// already-used/expired code, or trying to redeem your own invite) rather
// than throwing, since these are all reachable via a plain typo — an
// exception would make the calling UI's error handling clunkier for what
// is, for the user, just "that code didn't work."
/**
 * @typedef {Object} RedeemInviteResult
 * @property {boolean} ok
 * @property {('not-found'|'own-profile'|'used'|'expired'|'failed')} [reason]
 * @property {string} [profileId]
 * @property {string} [profileName]
 */
/**
 * @param {string} rawCode
 * @returns {Promise<RedeemInviteResult>}
 */
export async function redeemSharedInvite(rawCode){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  const code=String(rawCode||'').trim().toUpperCase();
  if(!code) return {ok:false, reason:'not-found'};
  const inviteRef=doc(db,'profile_invites',code);
  const snap=await getDoc(inviteRef);
  if(!snap.exists()) return {ok:false, reason:'not-found'};
  const invite=snap.data();
  if(invite.ownerUid===AppState.currentUser.uid) return {ok:false, reason:'own-profile'};
  if(invite.usedBy) return {ok:false, reason:'used'};
  if(!invite.expiresAt || invite.expiresAt<Date.now()) return {ok:false, reason:'expired'};
  try{
    await updateDoc(inviteRef, {usedBy: AppState.currentUser.uid});
    await updateDoc(doc(db,'users',invite.ownerUid,DCOL,`shared_members@${invite.profileId}`), {
      members: arrayUnion(AppState.currentUser.uid),
      updatedAt: Date.now(),
      lastJoinInviteCode: code,
    });
  }catch(e){
    console.error(e);
    return {ok:false, reason:'failed'};
  }
  if(!AppState.profilesMeta.list.some(p=>p.kind==='shared' && p.id===invite.profileId && p.ownerUid===invite.ownerUid)){
    AppState.profilesMeta.list.push({id:invite.profileId, name:invite.profileName||code, kind:'shared', ownerUid:invite.ownerUid, createdAt:Date.now()});
    await saveProfilesMeta();
  }
  return {ok:true, profileId:invite.profileId, profileName:invite.profileName};
}

// Removes this account from a shared profile it's a member of (never the
// owner — the owner leaving their own profile isn't "leaving", it's a
// different, unsupported operation for this v1: deleting/unsharing the
// profile entirely). Safe to call while that profile is the active one —
// the caller (see js/color-picker.js's leaveSharedProfileUI()) switches
// back to the account's own default profile afterward, same as
// deleteProfile() already requires switching off a profile before it can
// be removed.
/**
 * @param {string} ownerUid
 * @param {string} profileId
 * @returns {Promise<void>}
 */
export async function leaveSharedProfile(ownerUid, profileId){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  await updateDoc(doc(db,'users',ownerUid,DCOL,`shared_members@${profileId}`), {
    members: arrayRemove(AppState.currentUser.uid),
    updatedAt: Date.now(),
  });
  AppState.profilesMeta.list=AppState.profilesMeta.list.filter(p=>!(p.kind==='shared' && p.id===profileId && p.ownerUid===ownerUid));
  await saveProfilesMeta();
}

// ── GRANULAR PERMISSIONS (a later session) ──────────────────────
// Every member defaults to 'editor' (the original, only-ever behavior) —
// 'viewer' is an explicit downgrade the owner applies afterward. See
// firestore.rules' matching isEditorMember()/memberRole() for the actual
// security enforcement; everything here is a thin client convenience layer
// that mirrors what the rules already decide, never a second source of
// truth for it.

// Reads the current account's own role on the active profile and sets
// AppState.activeProfileRole. Called from switchProfile() right after
// activeProfileOwnerUid/activeProfileId are updated — a no-op (always
// 'editor') for any of the account's own profiles, since ownerUid is only
// ever set while viewing someone else's shared profile.
/** @returns {Promise<void>} */
export async function loadActiveProfileRole(){
  if(!AppState.activeProfileOwnerUid){ AppState.activeProfileRole='editor'; return; }
  try{
    const snap=await getDoc(userDoc('shared_members'));
    const roles=(snap.exists() && snap.data().roles) || {};
    AppState.activeProfileRole = roles[AppState.currentUser.uid]==='viewer' ? 'viewer' : 'editor';
  }catch(e){
    console.error(e);
    // Fail open to 'editor' on a transient read error rather than silently
    // locking someone out of a profile they actually have edit access to —
    // firestore.rules is the real enforcement either way, so this can only
    // ever make the client *offer* an action the server then correctly
    // allows or rejects, never bypass real enforcement.
    AppState.activeProfileRole='editor';
  }
}

// For the OWNER managing one of their own shared profiles: returns
// {members:[uid,...], roles:{uid:role}} or null if the profile was never
// shared (shared_members doc doesn't exist yet). Only ever called for a
// profile the current account owns — reading someone else's shared_members
// by profileId alone (no ownerUid) isn't meaningful, since userDoc()
// resolves relative to the current account.
/**
 * @param {string} profileId
 * @returns {Promise<{members: string[], roles: Record<string, string>} | null>}
 */
export async function listSharedMembers(profileId){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  const name = profileId && profileId!=='default' ? `shared_members@${profileId}` : 'shared_members';
  const snap=await getDoc(doc(db,'users',AppState.currentUser.uid,DCOL,name));
  if(!snap.exists()) return null;
  const data=snap.data();
  return {members:data.members||[], roles:data.roles||{}};
}

// Owner-only: sets one member's role on one of the owner's own shared
// profiles. Writes the whole roles map in one call (read-modify-write)
// rather than a dotted-path field update — simpler to reason about and
// avoids a Firestore merge-semantics edge case for a map this small.
/**
 * @param {string} profileId
 * @param {string} memberUid
 * @param {string} role
 * @returns {Promise<void>}
 */
export async function setMemberRole(profileId, memberUid, role){
  if(!AppState.currentUser) throw new Error('not-authenticated');
  if(AppState.activeProfileOwnerUid) throw new Error('only the profile owner can change member roles');
  const name = profileId && profileId!=='default' ? `shared_members@${profileId}` : 'shared_members';
  const ref=doc(db,'users',AppState.currentUser.uid,DCOL,name);
  const snap=await getDoc(ref);
  const data=snap.exists() ? snap.data() : {members:[AppState.currentUser.uid]};
  const roles={...(data.roles||{}), [memberUid]: role};
  await updateDoc(ref, {roles, updatedAt:Date.now()});
}

// ── TRANSACTIONS SUBCOLLECTION ─────────────────────────────────
// users/{uid}/max_tracker/{financeDocName}/transactions/{txId} — see
// MIGRATION_PLAN_transactions.md and CLAUDE.md's Firebase data model
// section for why this replaced the old finance.data array: every
// fbSaveNow() used to rewrite the *entire* transaction history on every
// single add/edit/delete, which is both the 1 MiB doc-size risk and the
// coarse per-document optimistic-concurrency conflict the plan describes.
// Pre-launch (no real users yet, see CLAUDE.md's Operating conventions)
// made a direct cutover practical instead of the originally-planned
// cautious dual-write/dual-read rollout — there's no live user base whose
// in-flight saves a phased migration would need to protect.
export function txCollection(){
  return collection(userDoc('finance'), 'transactions');
}
/** @param {string | number} id */
export function txDocRef(id){
  return doc(txCollection(), String(id));
}
/**
 * @param {{id: string | number}} t
 * @returns {Promise<void>}
 */
export async function saveTransactionDoc(t){
  await setDoc(txDocRef(t.id), t, {merge:false});
}
/**
 * @param {string | number} id
 * @returns {Promise<void>}
 */
export async function deleteTransactionDoc(id){
  await deleteDoc(txDocRef(id));
}
/** @returns {Promise<any[]>} */
export async function loadTransactionsFromSubcollection(){
  const snap=await getDocs(txCollection());
  const out=[];
  snap.forEach(d=>out.push(d.data()));
  return out;
}
// Firestore write batches cap at 500 ops; chunked well under that so this
// stays correct even for a very long transaction history.
const BATCH_CHUNK=450;
/**
 * @param {Array<{id: string | number}>} txs
 * @returns {Promise<void>}
 */
export async function batchWriteTransactions(txs){
  for(let i=0;i<txs.length;i+=BATCH_CHUNK){
    const batch=writeBatch(db);
    txs.slice(i,i+BATCH_CHUNK).forEach(t=>batch.set(txDocRef(t.id), t));
    await batch.commit();
  }
}
/**
 * @param {Array<string | number>} ids
 * @returns {Promise<void>}
 */
export async function batchDeleteTransactionsByIds(ids){
  for(let i=0;i<ids.length;i+=BATCH_CHUNK){
    const batch=writeBatch(db);
    ids.slice(i,i+BATCH_CHUNK).forEach(id=>batch.delete(txDocRef(id)));
    await batch.commit();
  }
}
// Deletes every doc in the transactions subcollection — Firestore never
// cascade-deletes a subcollection when its parent doc is deleted, so
// account deletion (js/auth.js's deleteAccountUser()) has to do this
// explicitly or it would leave an orphaned subcollection behind.
/** @returns {Promise<void>} */
export async function deleteAllTransactionDocs(){
  const snap=await getDocs(txCollection());
  const ids=[]; snap.forEach(d=>ids.push(d.id));
  if(ids.length) await batchDeleteTransactionsByIds(ids);
}
