// ── GOALS-PROFILE ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { computeWalletBalances } from './analytics-csv.js';
import { renderLinkPhoneUI } from './auth.js';
import { saveConfigLocal, scheduleSave } from './color-picker.js';
import { currencySymbol, walletById } from './core.js';
import { uid } from './settings-managers.js';
import { enhanceSelect, escapeHtml, setupAccessibleClickableDivs, showToast, uiConfirm } from './ui-widgets.js';

const openGoalsManager = function(){
  AppState.expandedGoalId=null; AppState.showNewGoalForm=false;
  renderGoalsManagerList();
  document.getElementById('goals-modal').style.display='flex';
};

const toggleGoalEdit = function(id){
  AppState.expandedGoalId = AppState.expandedGoalId===id ? null : id;
  renderGoalsManagerList();
};

const toggleNewGoalForm = function(){
  AppState.showNewGoalForm=!AppState.showNewGoalForm;
  renderNewGoalForm();
};

function renderNewGoalForm(){
  const box=document.getElementById('goals-new-form'); if(!box) return;
  box.style.display=AppState.showNewGoalForm?'flex':'none';
  if(!AppState.showNewGoalForm) return;
  const sel=document.getElementById('goal-new-wallet');
  if(sel){ sel.innerHTML=AppState.wallets.map(w=>`<option value="${w.id}">${escapeHtml(w.name)}</option>`).join(''); enhanceSelect(sel); }
  const amt=document.getElementById('goal-new-amount'); if(amt) amt.value='';
  const dt=document.getElementById('goal-new-date'); if(dt) dt.value='';
}

function renderGoalsManagerList(){
  const box=document.getElementById('goals-list-mgr'); if(!box) return;
  box.innerHTML='';
  if(!AppState.goals.length){ box.innerHTML=`<div class="mgr-empty">${tr('goals_empty')}</div>`; }
  else{
    const wb=computeWalletBalances();
    AppState.goals.forEach(g=>{
      const w=walletById(g.walletId);
      const open=AppState.expandedGoalId===g.id;
      const saved=w?Math.max(0, wb[g.walletId]||0):0;
      const target=g.targetAmount||0;
      const done=target>0 && saved>=target;
      const summary=w
        ? `${saved.toLocaleString('uk-UA')} / ${target.toLocaleString('uk-UA')} ${currencySymbol(w.currency||'UAH')}${done?' · '+tr('goals_reached'):''}`
        : tr('goals_need_wallet');
      const row=document.createElement('div');
      row.className='mgr-row';
      row.style.cssText='flex-direction:column;align-items:stretch;gap:10px';
      row.innerHTML=`
        <div class="cat-row">
          <span class="icon-badge icon-badge-sm" style="background:${w?w.color:'var(--muted)'}">${w?window.Icon(w.icon||'card'):''}</span>
          <div class="cat-row-body" style="cursor:default">
            <span class="cat-row-name">${w?escapeHtml(w.name):''}${g.targetDate?` · ${escapeHtml(g.targetDate)}`:''}</span>
            <span class="cat-row-sub">${summary}</span>
          </div>
          <button type="button" class="mgr-edit${open?' active':''}" data-action="toggle-goal-edit" data-id="${g.id}" aria-label="${tr('common_edit')}">${window.Icon(open?'xmark':'pencil')}</button>
          <button class="mgr-del" data-action="delete-goal" data-id="${g.id}" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
        </div>
        ${open?`
        <div style="display:flex;flex-direction:column;gap:8px;padding-top:6px;border-top:1px dashed var(--border)">
          <div class="fg">
            <label>${tr('finance_wallet')}</label>
            <select data-action="update-goal" data-id="${g.id}" data-field="walletId">
              ${AppState.wallets.map(w2=>`<option value="${w2.id}" ${g.walletId===w2.id?'selected':''}>${escapeHtml(w2.name)}</option>`).join('')}
            </select>
          </div>
          <div class="fg">
            <label>${tr('goals_target')}</label>
            <input type="number" min="0.01" step="0.01" value="${g.targetAmount||''}" data-action="update-goal" data-id="${g.id}" data-field="targetAmount">
          </div>
          <div class="fg">
            <label>${tr('goals_target_date')}</label>
            <input type="text" placeholder="напр. Грудень 2026" value="${escapeHtml(g.targetDate||'')}" data-action="update-goal" data-id="${g.id}" data-field="targetDate">
          </div>
        </div>`:''}
      `;
      box.appendChild(row);
      if(open) row.querySelectorAll('select').forEach(enhanceSelect);
    });
  }
  renderNewGoalForm();
}

const updateGoal = function(id,field,value){
  const g=AppState.goals.find(x=>x.id===id); if(!g) return;
  if(field==='targetAmount') g.targetAmount=parseFloat(value)||0;
  else g[field]=value;
  saveConfigLocal(); scheduleSave();
  renderGoalsManagerList();
  renderGoals();
};

const confirmAddGoal = function(){
  if(!AppState.wallets.length){ showToast(tr('goals_need_wallet'),'xmark'); return; }
  const walletSel=document.getElementById('goal-new-wallet');
  const walletId=walletSel&&walletSel.value?walletSel.value:AppState.wallets[0].id;
  const targetAmount=parseFloat(document.getElementById('goal-new-amount').value)||0;
  const targetDate=document.getElementById('goal-new-date').value||'';
  AppState.goals.push({id:uid('goal'), walletId, targetAmount, targetDate});
  saveConfigLocal(); scheduleSave();
  AppState.showNewGoalForm=false;
  renderGoalsManagerList();
  renderGoals();
  showToast(tr('goals_added'),'plus');
};

const deleteGoal = async function(id){
  if(!(await uiConfirm(tr('goals_delete_confirm'),{title:tr('goals_delete_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.goals=AppState.goals.filter(g=>g.id!==id);
  saveConfigLocal(); scheduleSave();
  renderGoalsManagerList();
  renderGoals();
};

export function renderGoals(){
  const section=document.getElementById('goals-section');
  const box=document.getElementById('goals-list');
  if(!section||!box) return;
  if(!AppState.widgets.goals || !AppState.goals.length){ section.style.display='none'; return; }
  section.style.display='block';
  const wb=computeWalletBalances();
  box.innerHTML='';
  AppState.goals.forEach(g=>{
    const w=walletById(g.walletId);
    if(!w) return;
    const saved=Math.max(0, wb[g.walletId]||0);
    const target=g.targetAmount||0;
    const pct=target>0?Math.min(100,Math.round(saved/target*100)):0;
    const done=target>0 && saved>=target;
    const color=done?'var(--green2)':'var(--purple2)';
    const row=document.createElement('div');
    row.style.marginBottom='14px';
    row.innerHTML=`
      <div style="display:flex;justify-content:space-between;align-items:center;font-size:12px;font-weight:700;margin-bottom:4px;gap:8px">
        <span style="display:flex;align-items:center;gap:8px;color:var(--text-strong);min-width:0"><span class="icon-badge icon-badge-sm" style="background:${w.color}">${window.Icon(w.icon||'card')}</span><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHtml(w.name)}${g.targetDate?` · ${escapeHtml(g.targetDate)}`:''}</span></span>
        <span style="color:${color};white-space:nowrap">${saved.toLocaleString('uk-UA')} / ${target.toLocaleString('uk-UA')} ${currencySymbol(w.currency||'UAH')}</span>
      </div>
      <div class="salary-bar-wrap"><div class="salary-bar-fill" style="width:${pct}%;background:${color}"></div></div>
      ${done?`<div style="font-size:11px;color:var(--green2);font-weight:700;margin-top:3px">${tr('goals_reached')}</div>`:''}
    `;
    box.appendChild(row);
  });
}

export const BUILTIN_AVATARS=[
  {id:'fox', icon:'sparkle', gradient:'linear-gradient(135deg,#f97316,#fbbf24)'},
  {id:'panda', icon:'moon', gradient:'linear-gradient(135deg,#64748b,#cbd5e1)'},
  {id:'robot', icon:'bolt', gradient:'linear-gradient(135deg,#0ea5e9,#67e8f9)'},
  {id:'rocket', icon:'target', gradient:'linear-gradient(135deg,#8b5cf6,#ec4899)'},
  {id:'gem', icon:'star', gradient:'linear-gradient(135deg,#06b6d4,#3b82f6)'},
  {id:'lion', icon:'flag', gradient:'linear-gradient(135deg,#f59e0b,#ef4444)'},
];

const selectBuiltinAvatar = function(id){
  AppState.profile.avatar='builtin:'+id;
  saveConfigLocal(); scheduleSave();
  renderProfileUI();
  showToast(tr('toast_avatar_updated'),'check');
};

function renderAvatarPicker(){
  const box=document.getElementById('profile-avatar-picker'); if(!box) return;
  box.innerHTML=BUILTIN_AVATARS.map(a=>`<div class="avatar-opt${AppState.profile.avatar==='builtin:'+a.id?' sel':''}" style="background:${a.gradient}" data-action="select-builtin-avatar" data-id="${a.id}">${window.Icon(a.icon)}</div>`).join('');
  setupAccessibleClickableDivs(box);
}

const handleAvatarUpload = function(event){
  const file=event.target.files && event.target.files[0];
  event.target.value='';
  if(!file) return;
  if(!file.type.startsWith('image/')){ showToast(tr('toast_avatar_bad_file'),'xmark'); return; }
  const reader=new FileReader();
  reader.onload=e=>{
    const img=new Image();
    img.onload=()=>{
      const size=160;
      const canvas=document.createElement('canvas');
      canvas.width=size; canvas.height=size;
      const ctx=canvas.getContext('2d');
      const s=Math.min(img.width,img.height);
      const sx=(img.width-s)/2, sy=(img.height-s)/2;
      ctx.drawImage(img, sx, sy, s, s, 0, 0, size, size);
      AppState.profile.avatar=canvas.toDataURL('image/jpeg',0.82);
      saveConfigLocal(); scheduleSave();
      renderProfileUI();
      showToast(tr('toast_avatar_updated'),'check');
    };
    img.onerror=()=>showToast(tr('toast_avatar_bad_file'),'xmark');
    img.src=e.target.result;
  };
  reader.readAsDataURL(file);
};

const updateNickname = function(value){
  AppState.profile.nickname=String(value||'').trim();
  saveConfigLocal(); scheduleSave();
  renderProfileUI();
};

const onNicknameInput = function(value){
  const btn=document.getElementById('profile-save-btn');
  if(btn) btn.style.display = (String(value||'').trim()!==(AppState.profile.nickname||'')) ? 'inline-flex' : 'none';
};

const saveNickname = function(){
  const ni=document.getElementById('profile-nickname-input');
  updateNickname(ni?ni.value:'');
  const btn=document.getElementById('profile-save-btn');
  if(btn) btn.style.display='none';
  if(ni) ni.readOnly=true;
  showToast(tr('toast_nickname_saved'),'check');
};

const enableNicknameEdit = function(){
  const ni=document.getElementById('profile-nickname-input');
  if(!ni) return;
  ni.readOnly=false;
  ni.focus();
  ni.select();
};

const onNicknameBlur = function(){
  setTimeout(()=>{
    const ni=document.getElementById('profile-nickname-input');
    const btn=document.getElementById('profile-save-btn');
    if(ni && (!btn || btn.style.display==='none')) ni.readOnly=true;
  },150);
};

function fillAvatarEl(el){
  if(!el) return;
  el.style.color='';
  if(AppState.profile.avatar && AppState.profile.avatar.startsWith('builtin:')){
    const a=BUILTIN_AVATARS.find(x=>'builtin:'+x.id===AppState.profile.avatar);
    if(a){ el.style.background=a.gradient; el.style.color='#fff'; el.innerHTML=window.Icon(a.icon); return; }
  }
  el.style.background='';
  if(AppState.profile.avatar){
    el.innerHTML='';
    const img=document.createElement('img');
    img.src=AppState.profile.avatar; // set as a property, not interpolated into HTML — profile.avatar is normally trusted (builtin id or canvas data URL) but Firestore has no field validation, so a directly-written doc could put arbitrary text here
    img.alt='';
    el.appendChild(img);
  }
  else{
    const letter=(AppState.profile.nickname||(AppState.currentUser&&AppState.currentUser.email)||'?').trim().charAt(0).toUpperCase()||'?';
    el.textContent=letter;
  }
}

export function renderProfileUI(){
  fillAvatarEl(document.getElementById('profile-avatar-preview'));
  fillAvatarEl(document.getElementById('topbar-avatar'));
  renderAvatarPicker();
  const ni=document.getElementById('profile-nickname-input');
  if(ni && document.activeElement!==ni){ ni.value=AppState.profile.nickname||''; ni.readOnly=true; }
  const who=document.getElementById('profile-signed-as');
  if(who){
    if(!AppState.currentUser){ who.textContent=''; }
    else{
      const isGoogle=(AppState.currentUser.providerData||[]).some(p=>p.providerId==='google.com');
      who.textContent=`${tr('settings_signed_in_as')} ${AppState.currentUser.email||''} (${isGoogle?'Google':'Email'})`;
    }
  }
  renderLinkPhoneUI();
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_goals_profile__(){
// Phase 6 of the window.*/inline-onclick removal audit item (see CLAUDE.md):
// all 13 of this file's window.* exports existed only for onclick/onchange/
// oninput/onblur attributes (its own goal-row/avatar-picker templates plus
// static ones in index.html). Converted to a data-action attribute
// dispatched through delegated listeners, same CLICK_ACTIONS/FIELD_ACTIONS
// pattern as phases 3-5. `blur` doesn't bubble (unlike input/change/click),
// so the nickname-input's onblur uses a separate `data-blur-action`
// attribute matched by a `focusout` listener (focusout is blur's bubbling
// equivalent) instead of reusing `data-action`.
const CLICK_ACTIONS = {
  'open-goals-manager': ()=>openGoalsManager(),
  'toggle-goal-edit': ds=>toggleGoalEdit(ds.id),
  'delete-goal': ds=>deleteGoal(ds.id),
  'toggle-new-goal-form': ()=>toggleNewGoalForm(),
  'confirm-add-goal': ()=>confirmAddGoal(),
  'select-builtin-avatar': ds=>selectBuiltinAvatar(ds.id),
  'save-nickname': ()=>saveNickname(),
  'enable-nickname-edit': ()=>enableNicknameEdit(),
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);

const FIELD_ACTIONS = {
  'update-goal': (ds,el)=>updateGoal(ds.id, ds.field, el.value),
  'handle-avatar-upload': (ds,el,e)=>handleAvatarUpload(e),
  'on-nickname-input': (ds,el)=>onNicknameInput(el.value),
};
function dispatchFieldAction(e){
  const el=e.target.closest('[data-action]');
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el, e);
}
document.addEventListener('change', dispatchFieldAction);
document.addEventListener('input', dispatchFieldAction);

document.addEventListener('focusout', e=>{
  const el=e.target.closest('[data-blur-action]');
  if(el && el.dataset.blurAction==='on-nickname-blur') onNicknameBlur();
});
}
