// ── NOTIFICATIONS ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { scheduleSave } from './color-picker.js';
import { VAPID_KEY, currencySymbol, db, deleteDoc, deleteToken, doc, fbApp, getMessaging, getToken, isMessagingSupported, onMessage, setDoc, toBase, walletCurrency } from './core.js';
import { csSync, showToast } from './ui-widgets.js';

export function loadNotifSettings(){
  try{ const n=localStorage.getItem('mxNotif'); if(n) AppState.notifSettings={...AppState.notifSettings, ...JSON.parse(n)}; }catch(e){}
}

export function saveNotifSettings(){
  // Captured on every save (not just once) so it tracks whichever device
  // most recently touched notification settings — the Cloud Function has
  // no other way to know the user's local time for the daily reminder.
  try{ AppState.notifSettings.timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'; }catch(e){}
  try{ localStorage.setItem('mxNotif', JSON.stringify(AppState.notifSettings)); }catch(e){}
  // Also synced to the finance doc (see setDoc payload) — the scheduled
  // Cloud Function push sweep reads it from there, since it obviously
  // can't see this device's localStorage.
  scheduleSave();
}

async function ensureNotifPermission(){
  if(!('Notification' in window)){ showToast(tr('toast_reminders_unsupported'),'xmark'); return false; }
  let perm=Notification.permission;
  if(perm==='default') perm=await Notification.requestPermission();
  if(perm!=='granted'){ showToast(tr('toast_reminders_denied'),'xmark'); return false; }
  return true;
}

function showLocalNotification(title, body){
  // badge (the small Android status-bar/notification-shade glyph) must be an
  // alpha-transparency-only image — Android renders it using just the alpha
  // channel as a white silhouette, ignoring color. icon-192.png is a fully
  // opaque color image with no alpha channel at all, so using it as `badge`
  // made Android render the *entire* icon as one solid white blob (reported
  // by the account owner via screenshot). badge-96.png is a real white
  // bell-on-transparent glyph made specifically for this; `icon` (the large
  // image) is unaffected and still uses the real full-color app icon.
  const show=reg=>{ if(reg) reg.showNotification(title,{body, icon:'icon-192.png', badge:'badge-96.png'}); else new Notification(title,{body, icon:'icon-192.png'}); };
  if(navigator.serviceWorker && navigator.serviceWorker.getRegistration) navigator.serviceWorker.getRegistration().then(show);
  else show(null);
}

export function pushEnabledKey(){ return AppState.currentUser ? `mx_pushEnabled_${AppState.currentUser.uid}` : null; }

export async function getMessagingInstance(){
  if(AppState.messagingInstance) return AppState.messagingInstance;
  if(!(await isMessagingSupported())) return null;
  AppState.messagingInstance=getMessaging(fbApp);
  onMessage(AppState.messagingInstance, payload=>{
    const n=payload.notification||{};
    showLocalNotification(n.title||'Rytm', n.body||'');
  });
  return AppState.messagingInstance;
}

const togglePushNotifications = async function(){
  const k=pushEnabledKey();
  if(k && localStorage.getItem(k)==='1') await disablePushNotifications();
  else await enablePushNotifications();
};

async function enablePushNotifications(){
  if(VAPID_KEY==='PASTE_YOUR_VAPID_KEY_HERE'){ showToast(tr('toast_push_no_vapid'),'xmark'); renderNotifUI(); return; }
  const messaging=await getMessagingInstance();
  if(!messaging){ showToast(tr('toast_push_unsupported'),'xmark'); renderNotifUI(); return; }
  if(!(await ensureNotifPermission())){ renderNotifUI(); return; }
  try{
    const reg=await navigator.serviceWorker.register('sw.js');
    const token=await getToken(messaging,{vapidKey:VAPID_KEY, serviceWorkerRegistration:reg});
    if(!token) throw new Error('no-token');
    await setDoc(doc(db,'push_tokens',AppState.currentUser.uid), {token, updatedAt:Date.now()}, {merge:true});
    const k=pushEnabledKey(); if(k) localStorage.setItem(k,'1');
    showToast(tr('toast_push_on'),'check');
  }catch(err){
    console.error('enable push failed',err);
    showToast(tr('toast_push_fail'),'xmark');
  }
  renderNotifUI();
}

async function disablePushNotifications(){
  try{
    const messaging=await getMessagingInstance();
    if(messaging){
      // deleteToken() (unlike getToken()) takes no options argument — it
      // only checks messaging.swRegistration, and if that's not already
      // set (e.g. a fresh page load that never called getToken() this
      // session), it auto-registers a separate firebase-messaging-sw.js
      // at the root scope. That file doesn't exist in this repo — push
      // handling was merged into sw.js itself, see CLAUDE.md's Layout
      // section — so the lookup 404s and deleteToken() throws. Setting
      // this property directly (the same one getToken() sets internally
      // when passed an explicit serviceWorkerRegistration) heads that off.
      if(!messaging.swRegistration) messaging.swRegistration=await navigator.serviceWorker.register('sw.js');
      await deleteToken(messaging);
    }
  }catch(err){ console.warn('deleteToken failed', err); }
  try{ await deleteDoc(doc(db,'push_tokens',AppState.currentUser.uid)); }catch(err){ console.warn('deleting push token doc failed', err); }
  const k=pushEnabledKey(); if(k) localStorage.removeItem(k);
  showToast(tr('toast_push_off'),'xmark');
  renderNotifUI();
}

const toggleReminders = async function(){
  if(AppState.notifSettings.enabled){
    AppState.notifSettings.enabled=false;
    saveNotifSettings(); renderNotifUI();
    showToast(tr('toast_reminders_off'),'xmark');
    return;
  }
  if(!(await ensureNotifPermission())){ renderNotifUI(); return; }
  AppState.notifSettings.enabled=true;
  saveNotifSettings(); renderNotifUI();
  showToast(tr('toast_reminders_on'),'check');
  maybeShowDailyReminder();
};

const toggleBudgetAlerts = async function(){
  if(AppState.notifSettings.budgetAlerts){
    AppState.notifSettings.budgetAlerts=false;
    saveNotifSettings(); renderNotifUI();
    return;
  }
  if(!(await ensureNotifPermission())){ renderNotifUI(); return; }
  AppState.notifSettings.budgetAlerts=true;
  saveNotifSettings(); renderNotifUI();
  checkBudgetAlerts();
};

const toggleRecurringAlerts = async function(){
  if(AppState.notifSettings.recurringAlerts){
    AppState.notifSettings.recurringAlerts=false;
    saveNotifSettings(); renderNotifUI();
    return;
  }
  if(!(await ensureNotifPermission())){ renderNotifUI(); return; }
  AppState.notifSettings.recurringAlerts=true;
  saveNotifSettings(); renderNotifUI();
  checkRecurringAlerts();
};

const toggleDebtAlerts = async function(){
  if(AppState.notifSettings.debtAlerts){
    AppState.notifSettings.debtAlerts=false;
    saveNotifSettings(); renderNotifUI();
    return;
  }
  if(!(await ensureNotifPermission())){ renderNotifUI(); return; }
  AppState.notifSettings.debtAlerts=true;
  saveNotifSettings(); renderNotifUI();
  checkDebtAlerts();
};

export function populateNotifTimeSelects(){
  const h=document.getElementById('notif-time-hour');
  const m=document.getElementById('notif-time-minute');
  if(h && !h.options.length){
    for(let i=0;i<24;i++){ const o=document.createElement('option'); o.value=o.textContent=String(i).padStart(2,'0'); h.appendChild(o); }
  }
  if(m && !m.options.length){
    for(let i=0;i<60;i+=5){ const o=document.createElement('option'); o.value=o.textContent=String(i).padStart(2,'0'); m.appendChild(o); }
  }
}

const updateNotifTimeFromSelects = function(){
  const h=document.getElementById('notif-time-hour')?.value||'21';
  const m=document.getElementById('notif-time-minute')?.value||'00';
  AppState.notifSettings.time=`${h}:${m}`;
  saveNotifSettings();
};

export function renderNotifUI(){
  const cb=document.getElementById('notif-toggle-checkbox');
  if(cb) cb.checked=!!AppState.notifSettings.enabled;
  const [hh,mm]=(AppState.notifSettings.time||'21:00').split(':');
  const h=document.getElementById('notif-time-hour');
  const m=document.getElementById('notif-time-minute');
  if(h && h.value!==hh){ h.value=hh; csSync(h); }
  if(m && m.value!==mm){ m.value=mm; csSync(m); }
  const bcb=document.getElementById('notif-budget-checkbox');
  if(bcb) bcb.checked=!!AppState.notifSettings.budgetAlerts;
  const rcb=document.getElementById('notif-recurring-checkbox');
  if(rcb) rcb.checked=!!AppState.notifSettings.recurringAlerts;
  const dcb=document.getElementById('notif-debt-checkbox');
  if(dcb) dcb.checked=!!AppState.notifSettings.debtAlerts;
  const pcb=document.getElementById('notif-push-checkbox');
  const pk=pushEnabledKey();
  if(pcb) pcb.checked=!!(pk && localStorage.getItem(pk)==='1');
}

function todayStr(){
  const d=new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

export function runNotificationChecks(){
  maybeShowDailyReminder();
  checkBudgetAlerts();
  checkRecurringAlerts();
  checkDebtAlerts();
}

function maybeShowDailyReminder(){
  if(!AppState.notifSettings.enabled) return;
  if(!('Notification' in window) || Notification.permission!=='granted') return;
  const today=todayStr();
  if(localStorage.getItem('mxReminderShown')===today) return;
  const now=new Date();
  const [h,m]=(AppState.notifSettings.time||'21:00').split(':').map(Number);
  if(now.getHours()<h || (now.getHours()===h && now.getMinutes()<(m||0))) return;
  if(AppState.transactions.some(tx=>tx.date===today)) return;
  showLocalNotification('Rytm', tr('reminder_body'));
  localStorage.setItem('mxReminderShown', today);
}

function checkBudgetAlerts(){
  if(!AppState.notifSettings.budgetAlerts) return;
  if(!('Notification' in window) || Notification.permission!=='granted') return;
  const now=new Date();
  const prefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
  Object.entries(AppState.budgets).forEach(([cat,limit])=>{
    if(!(limit>0) || !(AppState.categories.expense||[]).includes(cat)) return;
    const spent=AppState.transactions.reduce((s,t)=>(t.type==='expense'&&t.category===cat&&t.date&&t.date.startsWith(prefix))?s+toBase(t.amount,t.currency||'UAH'):s,0);
    if(spent<=limit) return;
    const shownKey=`mxBudgetAlert_${prefix}_${cat}`;
    if(localStorage.getItem(shownKey)) return;
    showLocalNotification(tr('notif_budget_title'), tr('notif_budget_body').replace('{category}',cat));
    localStorage.setItem(shownKey,'1');
  });
}

function checkRecurringAlerts(){
  if(!AppState.notifSettings.recurringAlerts) return;
  if(!('Notification' in window) || Notification.permission!=='granted') return;
  const tomorrow=new Date(); tomorrow.setDate(tomorrow.getDate()+1);
  const tomorrowStr=`${tomorrow.getFullYear()}-${String(tomorrow.getMonth()+1).padStart(2,'0')}-${String(tomorrow.getDate()).padStart(2,'0')}`;
  AppState.recurring.forEach(r=>{
    if(r.active===false || r.nextDate!==tomorrowStr || !r.amount) return;
    const shownKey=`mxRecurAlert_${r.id}_${tomorrowStr}`;
    if(localStorage.getItem(shownKey)) return;
    const amountStr=r.amount.toLocaleString('uk-UA')+' '+currencySymbol(walletCurrency(r.wallet));
    showLocalNotification(tr('notif_recurring_title'), tr('notif_recurring_body').replace('{category}',r.category||tr('cat_other')).replace('{amount}',amountStr));
    localStorage.setItem(shownKey,'1');
  });
}

// One day ahead of a debt's dueDate — same "fires exactly one calendar day
// before" convention checkRecurringAlerts() already uses, not a
// configurable lead time (see CLAUDE.md for why this field didn't exist
// until now: debts previously had no structured date field, only a
// freeform text label per payment entry).
function checkDebtAlerts(){
  if(!AppState.notifSettings.debtAlerts) return;
  if(!('Notification' in window) || Notification.permission!=='granted') return;
  const tomorrow=new Date(); tomorrow.setDate(tomorrow.getDate()+1);
  const tomorrowStr=`${tomorrow.getFullYear()}-${String(tomorrow.getMonth()+1).padStart(2,'0')}-${String(tomorrow.getDate()).padStart(2,'0')}`;
  AppState.debts.forEach(d=>{
    if(d.dueDate!==tomorrowStr) return;
    const shownKey=`mxDebtAlert_${d.id}_${tomorrowStr}`;
    if(localStorage.getItem(shownKey)) return;
    showLocalNotification(tr('notif_debt_title'), tr('notif_debt_body').replace('{name}',d.name||tr('debt_default_name')));
    localStorage.setItem(shownKey,'1');
  });
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_notifications__(){
// Phase 13 of the window.*/inline-onclick removal audit item (see
// CLAUDE.md): this file's 5 static onchange="" sites in index.html
// (push/reminders/budget/recurring toggles, hour+minute time selects)
// converted to a data-action dispatch, same pattern earlier phases used.
const FIELD_ACTIONS = {
  'toggle-push-notifications': ()=>togglePushNotifications(),
  'toggle-reminders': ()=>toggleReminders(),
  'toggle-budget-alerts': ()=>toggleBudgetAlerts(),
  'toggle-recurring-alerts': ()=>toggleRecurringAlerts(),
  'toggle-debt-alerts': ()=>toggleDebtAlerts(),
  'update-notif-time': ()=>updateNotifTimeFromSelects(),
};
document.addEventListener('change', e=>{
  const el=e.target.closest('[data-action]');
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el);
});
}
