// ── SHOPPING ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';
import { saveShoppingLocal, scheduleSave } from './color-picker.js';
import { uid } from './settings-managers.js';
import { emptyStateHtml, escapeHtml, uiConfirm } from './ui-widgets.js';

const addShoppingItem = function(){
  const ni=document.getElementById('shopping-name-input');
  const qi=document.getElementById('shopping-qty-input');
  const name=(ni&&ni.value||'').trim();
  if(!name) return;
  const qty=parseInt(qi&&qi.value,10)||1;
  AppState.shoppingList.push({id:uid('item'), name, qty, done:false, createdAt:Date.now()});
  if(ni) ni.value='';
  if(qi) qi.value='';
  saveShoppingLocal(); scheduleSave();
  renderShoppingList();
  if(ni) ni.focus();
};

const toggleShoppingItem = function(id, done){
  const it=AppState.shoppingList.find(x=>x.id===id); if(!it) return;
  it.done=!!done;
  saveShoppingLocal(); scheduleSave();
  renderShoppingList();
};

const deleteShoppingItem = function(id){
  AppState.shoppingList=AppState.shoppingList.filter(x=>x.id!==id);
  saveShoppingLocal(); scheduleSave();
  renderShoppingList();
};

const clearBoughtShopping = async function(){
  if(!AppState.shoppingList.some(x=>x.done)) return;
  if(!(await uiConfirm(tr('shopping_clear_confirm'),{title:tr('shopping_clear_title'),okText:tr('common_delete'),danger:true}))) return;
  AppState.shoppingList=AppState.shoppingList.filter(x=>!x.done);
  saveShoppingLocal(); scheduleSave();
  renderShoppingList();
};

export function renderShoppingList(){
  const box=document.getElementById('shopping-list-container'); if(!box) return;
  const remaining=AppState.shoppingList.filter(x=>!x.done).length;
  const bought=AppState.shoppingList.length-remaining;
  const S=(id,v)=>{const el=document.getElementById(id); if(el) el.textContent=v;};
  S('shopping-remaining-val', remaining);
  S('shopping-bought-val', bought);
  const clearBtn=document.getElementById('shopping-clear-btn');
  if(clearBtn) clearBtn.style.display = bought>0 ? '' : 'none';
  box.innerHTML='';
  if(!AppState.shoppingList.length){
    box.innerHTML=emptyStateHtml({
      icon:'cart',
      title:tr('shopping_empty_title'),
      desc:tr('shopping_empty_desc'),
      action:tr('shopping_add_btn'),
      onClick:'document.getElementById("shopping-name-input")?.focus()'
    });
    return;
  }
  // Unbought items first, bought ones (dimmed/struck-through) trail behind.
  const sorted=[...AppState.shoppingList].sort((a,b)=>(a.done===b.done)?0:(a.done?1:-1));
  sorted.forEach(it=>{
    const row=document.createElement('div');
    row.className='mgr-row';
    row.innerHTML=`
      <input type="checkbox" class="rchk" ${it.done?'checked':''} onchange="toggleShoppingItem('${it.id}', this.checked)">
      <div class="mgr-name-inline" style="${it.done?'text-decoration:line-through;opacity:.55':''}">${escapeHtml(it.name)}</div>
      ${it.qty>1?`<span style="font-size:12px;font-weight:700;color:var(--muted);flex:0 0 auto">×${it.qty}</span>`:''}
      <button class="mgr-del" onclick="deleteShoppingItem('${it.id}')" aria-label="${tr('common_delete')}">${window.Icon('trash')}</button>
    `;
    box.appendChild(row);
  });
}

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_shopping__(){
window.addShoppingItem = addShoppingItem;
window.toggleShoppingItem = toggleShoppingItem;
window.deleteShoppingItem = deleteShoppingItem;
window.clearBoughtShopping = clearBoughtShopping;
}
