// ── UI-WIDGETS ──────────────────────────────────────
// Split from the original single-file index.html module script — see
// CLAUDE.md for the module layout. Import wiring below was generated by
// AST-based free-variable analysis (eslint-scope), not manual tracing.
import { AppState } from './state.js';

const HTML_ESCAPES={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};

export function escapeHtml(str){
  return String(str==null?'':str).replace(/[&<>"']/g, c=>HTML_ESCAPES[c]);
}

export function emptyStateHtml({icon='inbox', title='', desc='', action='', onClick=''}){
  return `<div class="empty-state">
    <div class="empty-state-icon">${window.Icon(icon)}</div>
    <div class="empty-state-title">${escapeHtml(title)}</div>
    ${desc?`<div class="empty-state-desc">${escapeHtml(desc)}</div>`:''}
    ${action?`<button type="button" class="btn btn-primary" onclick="${escapeHtml(onClick)}">${escapeHtml(action)}</button>`:''}
  </div>`;
}

export const filterSettings = function(q){
  const needle=String(q||'').trim().toLowerCase();
  const sections=[...document.querySelectorAll('#tab-settings .settings-section')];
  let visible=0;
  sections.forEach(section=>{
    const groupHit=AppState.activeSettingsGroup==='all' || section.dataset.settingsGroup===AppState.activeSettingsGroup;
    const text=section.textContent.toLowerCase();
    const hit=groupHit && (!needle || text.includes(needle));
    section.classList.toggle('settings-section-hidden', !hit);
    if(hit) visible++;
  });
  const empty=document.getElementById('settings-no-results');
  if(empty) empty.style.display = sections.length && visible===0 ? 'block' : 'none';
};

const setSettingsGroup = function(group){
  AppState.activeSettingsGroup=group||'all';
  document.querySelectorAll('.settings-group-chip').forEach(chip=>{
    chip.classList.toggle('active', chip.dataset.group===AppState.activeSettingsGroup);
  });
  filterSettings(document.getElementById('settings-search-input')?.value||'');
};

const FINANCE_SECTIONS_COLLAPSED_BY_DEFAULT=['analytics-section','fx-widget-section','fx-converter-section'];

export function setupCollapsibleFinanceSections(){
  ['analytics-section','budgets-section','goals-section','finance-chart-section','fx-widget-section','fx-converter-section'].forEach(id=>{
    const section=document.getElementById(id);
    const title=section&&section.querySelector('.chart-title');
    if(!section||!title||section.dataset.collapsibleReady) return;
    section.dataset.collapsibleReady='1';
    section.classList.add('collapsible');
    if(FINANCE_SECTIONS_COLLAPSED_BY_DEFAULT.includes(id)) section.classList.add('collapsed');
    title.setAttribute('tabindex','0');
    title.setAttribute('role','button');
    title.addEventListener('click',()=>section.classList.toggle('collapsed'));
    title.addEventListener('keydown',e=>{
      if(e.key==='Enter'||e.key===' '){ e.preventDefault(); section.classList.toggle('collapsed'); }
    });
  });
}

export function setupAccessibleClickableDivs(root){
  // Matches both div[onclick] (older, not-yet-converted rows) and
  // div[data-action] (rows already converted to the delegated
  // data-action dispatch by the window.*/onclick-removal audit item —
  // see CLAUDE.md) so a row doesn't lose keyboard accessibility the
  // moment its onclick="" attribute gets replaced.
  (root||document).querySelectorAll('div[onclick]:not([tabindex]), div[data-action]:not([tabindex])').forEach(el=>{
    if(el.classList.contains('modal-overlay')) return;
    // Wrapper divs whose only onclick is "don't let this bubble to the
    // backdrop" aren't a real action — skip them, or every modal/dialog
    // card would become a pointless, empty tab stop before its real controls.
    if(el.hasAttribute('onclick') && el.getAttribute('onclick').trim()==='event.stopPropagation()') return;
    el.tabIndex=0;
    el.setAttribute('role','button');
    el.addEventListener('keydown',e=>{
      if(e.key==='Enter'||e.key===' '){ e.preventDefault(); el.click(); }
    });
  });
}

export function setupAccessibleSettingsRows(){ setupAccessibleClickableDivs(); }

export function hexA(hex, a){
  let h=String(hex||'#8b5cf6').replace('#','');
  if(h.length===3) h=h.split('').map(c=>c+c).join('');
  const n=parseInt(h,16);
  const r=(n>>16)&255, g=(n>>8)&255, b=n&255;
  return `rgba(${r},${g},${b},${a})`;
}

function hapticFeedback(kind){
  if(!('vibrate' in navigator)) return;
  try{
    if(kind==='success') navigator.vibrate(10);
    else if(kind==='error') navigator.vibrate([12,40,12]);
  }catch(e){}
}

export function showToast(msg, icon){
  const t=document.getElementById('toast');
  t.innerHTML='';
  if(icon){
    // window.Icon() output is trusted (built only from the static ICON_PATHS
    // table), unlike msg below which can contain user-entered text (category
    // names, nicknames, etc.) and must never be inserted as raw HTML.
    const iconTmp=document.createElement('div');
    iconTmp.innerHTML=window.Icon(icon);
    if(iconTmp.firstChild) t.appendChild(iconTmp.firstChild);
  }
  const span=document.createElement('span');
  span.textContent=msg;
  t.appendChild(span);
  t.classList.add('show');
  setTimeout(()=>t.classList.remove('show'),2800);
  if(icon==='check') hapticFeedback('success');
  else if(icon==='xmark') hapticFeedback('error');
}

function positionFixedPanel(trigger, panel, matchTriggerWidth, opts){
  opts=opts||{};
  const r=trigger.getBoundingClientRect();
  const vw=window.innerWidth, vh=window.innerHeight;
  const margin=8;
  if(matchTriggerWidth) panel.style.width=r.width+'px';
  const panelWidth=matchTriggerWidth?r.width:(panel.offsetWidth||280);
  let left=r.left;
  if(left+panelWidth>vw-margin) left=Math.max(margin, vw-margin-panelWidth);

  const spaceBelow=vh-r.bottom-margin;
  const spaceAbove=r.top-margin;
  let top;
  if(opts.dynamicHeight){
    const preferredMax=260;
    let maxH;
    if(spaceBelow>=140 || spaceBelow>=spaceAbove){
      top=r.bottom+6;
      maxH=Math.max(100, Math.min(preferredMax, vh-top-margin));
    }else{
      maxH=Math.max(100, Math.min(preferredMax, spaceAbove-6));
      top=Math.max(margin, r.top-6-maxH);
    }
    panel.style.maxHeight=maxH+'px';
    const scroll=panel.querySelector('.cs-panel-scroll');
    if(scroll) scroll.style.maxHeight=Math.max(60, maxH-12)+'px';
  }else{
    const estH=panel.offsetHeight||360;
    top=r.bottom+6;
    if(top+estH>vh-margin && spaceAbove>spaceBelow) top=Math.max(margin, r.top-6-estH);
  }
  panel.style.left=left+'px';
  panel.style.top=top+'px';
}

export function enhanceSelect(sel){
  if(!sel || sel.dataset.enhanced) return;
  sel.dataset.enhanced='1';
  const small = sel.classList.contains('tool-select') || !!sel.closest('.cal-nav');
  const wrap=document.createElement('div');
  wrap.className='cs'+(small?' cs-sm':'');
  sel.parentNode.insertBefore(wrap, sel);
  wrap.appendChild(sel);
  const trigger=document.createElement('button');
  trigger.type='button'; trigger.className='cs-trigger';
  trigger.innerHTML='<span class="cs-val"></span>'+window.Icon('chevron');
  const car=trigger.querySelector('svg'); if(car) car.classList.add('cs-caret');
  const panel=document.createElement('div'); panel.className='cs-panel';
  const panelScroll=document.createElement('div'); panelScroll.className='cs-panel-scroll';
  panel.appendChild(panelScroll);
  wrap.appendChild(trigger); wrap.appendChild(panel);
  const close=()=>wrap.classList.remove('open');
  function build(){
    panelScroll.innerHTML='';
    Array.from(sel.options).forEach(opt=>{
      const o=document.createElement('div');
      o.className='cs-opt'+(opt.selected?' sel':'');
      o.textContent=opt.textContent;
      o.addEventListener('click',e=>{ e.stopPropagation(); sel.value=opt.value; sel.dispatchEvent(new Event('change',{bubbles:true})); close(); });
      panelScroll.appendChild(o);
    });
    const cur=sel.options[sel.selectedIndex];
    trigger.querySelector('.cs-val').textContent=cur?cur.textContent:'';
  }
  trigger.addEventListener('click',e=>{
    e.stopPropagation();
    const willOpen=!wrap.classList.contains('open');
    document.querySelectorAll('.cs.open').forEach(c=>c.classList.remove('open'));
    if(willOpen){ positionFixedPanel(trigger, panel, true, {dynamicHeight:true}); wrap.classList.add('open'); }
  });
  sel.addEventListener('change', build);
  sel.addEventListener('cs-sync', build); // for programmatic .value changes
  new MutationObserver(build).observe(sel,{childList:true});
  build();
}

export function csSync(sel){ if(sel) sel.dispatchEvent(new Event('cs-sync')); }

function dpParse(v){
  if(!v) return null;
  const [y,m,d]=v.split('-').map(Number);
  if(!y) return null;
  return new Date(y,m-1,d);
}

function dpFmt(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }

function dpLabel(v){
  const d=dpParse(v); if(!d) return tr('finance_pick_date');
  return `${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}.${d.getFullYear()}`;
}

export function enhanceDateInput(inp){
  if(!inp || inp.dataset.enhanced) return;
  inp.dataset.enhanced='1';
  const wrap=document.createElement('div'); wrap.className='dp';
  inp.parentNode.insertBefore(wrap, inp);
  wrap.appendChild(inp);
  const trigger=document.createElement('button');
  trigger.type='button'; trigger.className='cs-trigger dp-trigger';
  trigger.innerHTML='<span class="dp-val"></span>'+window.Icon('calendar');
  const panel=document.createElement('div'); panel.className='dp-panel';
  wrap.appendChild(trigger); wrap.appendChild(panel);
  let viewDate=dpParse(inp.value)||new Date();
  const close=()=>wrap.classList.remove('open');
  function refreshLabel(){ trigger.querySelector('.dp-val').textContent=dpLabel(inp.value); }
  function render(){
    const y=viewDate.getFullYear(), m=viewDate.getMonth();
    const selected=dpParse(inp.value), today=new Date();
    const first=(new Date(y,m,1).getDay()+6)%7;
    const total=new Date(y,m+1,0).getDate();
    const prevTotal=new Date(y,m,0).getDate();
    let html=`<div class="dp-nav"><button type="button" class="dp-nav-btn" data-act="prev" aria-label="${tr('a11y_prev_month')}">${window.Icon('chevron')}</button><div class="dp-month-label">${AppState.MONTHS[m]} ${y}</div><button type="button" class="dp-nav-btn" data-act="next" aria-label="${tr('a11y_next_month')}">${window.Icon('chevron')}</button></div>`;
    html+=`<div class="dp-weekdays">${AppState.WEEKDAYS.map(w=>`<span>${w}</span>`).join('')}</div><div class="dp-grid">`;
    for(let i=0;i<first;i++) html+=`<span class="dp-day dp-out">${prevTotal-first+i+1}</span>`;
    for(let d=1;d<=total;d++){
      const isSel=selected&&selected.getFullYear()===y&&selected.getMonth()===m&&selected.getDate()===d;
      const isToday=today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===d;
      html+=`<span class="dp-day${isSel?' dp-sel':''}${!isSel&&isToday?' dp-today-mark':''}" data-d="${d}">${d}</span>`;
    }
    const rest=(7-((first+total)%7))%7;
    for(let i=1;i<=rest;i++) html+=`<span class="dp-day dp-out">${i}</span>`;
    html+='</div><button type="button" class="dp-today-btn" data-act="today">Сьогодні</button>';
    panel.innerHTML=html;
    panel.querySelector('[data-act=prev]').addEventListener('click',e=>{e.stopPropagation(); viewDate=new Date(y,m-1,1); render();});
    panel.querySelector('[data-act=next]').addEventListener('click',e=>{e.stopPropagation(); viewDate=new Date(y,m+1,1); render();});
    panel.querySelector('[data-act=today]').addEventListener('click',e=>{
      e.stopPropagation(); const t=new Date(); inp.value=dpFmt(t);
      inp.dispatchEvent(new Event('change',{bubbles:true})); viewDate=t; refreshLabel(); close();
    });
    panel.querySelectorAll('.dp-day:not(.dp-out)').forEach(el=>{
      el.addEventListener('click',e=>{
        e.stopPropagation();
        inp.value=dpFmt(new Date(y,m,parseInt(el.getAttribute('data-d'))));
        inp.dispatchEvent(new Event('change',{bubbles:true}));
        refreshLabel(); close();
      });
    });
  }
  trigger.addEventListener('click',e=>{
    e.stopPropagation();
    const willOpen=!wrap.classList.contains('open');
    document.querySelectorAll('.cs.open,.dp.open').forEach(c=>c.classList.remove('open'));
    if(willOpen){ viewDate=dpParse(inp.value)||new Date(); render(); positionFixedPanel(trigger, panel, false); wrap.classList.add('open'); }
  });
  inp.addEventListener('change', refreshLabel);
  inp.addEventListener('cs-sync', refreshLabel);
  refreshLabel();
}

export function enhanceAllSelects(){
  if(AppState.selectsEnhanced) return; AppState.selectsEnhanced=true;
  document.querySelectorAll('.app select').forEach(enhanceSelect);
  document.querySelectorAll('.app input[type=date]').forEach(enhanceDateInput);
  const closeAllPanels=()=>document.querySelectorAll('.cs.open,.dp.open').forEach(c=>c.classList.remove('open'));
  document.addEventListener('click',closeAllPanels);
  // Fixed-position panels don't move with their trigger, so close them on
  // any scroll (capture:true catches scrolling inside .modal-card-body
  // too, since 'scroll' doesn't bubble) or viewport resize. Scrolling
  // *inside* the panel itself (.cs-panel-scroll) must NOT close it —
  // otherwise the very act of touch-scrolling the option list closes
  // the panel before the user can see the rest of it.
  document.addEventListener('scroll',e=>{
    if(e.target.closest && e.target.closest('.cs-panel,.dp-panel')) return;
    closeAllPanels();
  },true);
  window.addEventListener('resize',closeAllPanels);
}

function __closeDlg(val){
  const ov=document.getElementById('ui-dialog');
  if(ov) ov.style.display='none';
  const r=AppState.__dlgResolve; AppState.__dlgResolve=null;
  if(r) r(val);
}

function uiDialog({title,message,input,defaultValue,okText,cancelText,danger}){
  return new Promise(resolve=>{
    AppState.__dlgResolve=resolve;
    document.getElementById('ui-dlg-title').textContent=title||'';
    const msg=document.getElementById('ui-dlg-msg');
    msg.textContent=message||''; msg.style.display=message?'block':'none';
    const inp=document.getElementById('ui-dlg-input');
    const ok=document.getElementById('ui-dlg-ok');
    const cancel=document.getElementById('ui-dlg-cancel');
    ok.textContent=okText||'OK';
    ok.classList.toggle('danger',!!danger);
    cancel.textContent=cancelText||tr('common_cancel');
    cancel.style.display=(cancelText===null)?'none':'';
    if(input){
      inp.style.display='block'; inp.value=defaultValue||'';
      setTimeout(()=>{inp.focus(); inp.select();},50);
    }else{
      inp.style.display='none';
    }
    document.getElementById('ui-dialog').style.display='flex';
  });
}

export const uiConfirm = function(message,opts){ opts=opts||{}; return uiDialog({title:opts.title||tr('common_confirm_title'),message,okText:opts.okText||tr('common_yes'),cancelText:opts.cancelText||tr('common_cancel'),danger:opts.danger}).then(v=>v!==null && v!==false); };

export const uiAlert = function(message,title){ return uiDialog({title:title||'',message,okText:tr('common_got_it'),cancelText:null}); };

export const uiPrompt = function(message,defaultValue,title){ return uiDialog({title:title||'',message,input:true,defaultValue,okText:tr('common_done')}); };

// Top-level statements that DO something immediately (as opposed to a
// plain declaration) - deferred into this function and called from
// app.js only after every module in the import graph has finished
// evaluating, so nothing here can hit a temporal-dead-zone reference to
// another chunk's not-yet-initialized export (this is exactly the class
// of bug that broke 'auth' being read before core.js's declaration of it
// had run, when this was still ordinary top-level code in this file).
export function __init_ui_widgets__(){
// Phase 12 of the window.*/inline-onclick removal audit item (see
// CLAUDE.md): this file's own remaining onclick/oninput sites — the
// settings search input and the 5 .settings-group-chip buttons, all in
// index.html — replaced with a data-action dispatch, same
// CLICK_ACTIONS/FIELD_ACTIONS-on-the-capture-phase pattern earlier phases
// used (settings-managers.js, etc.). uiConfirm/uiAlert/uiPrompt were
// already dead as window.* (every call site is a real `import`, never a
// literal onclick="uiConfirm(...)") so those exports were dropped outright.
const CLICK_ACTIONS = {
  'set-settings-group': ds=>setSettingsGroup(ds.group),
};
const FIELD_ACTIONS = {
  'filter-settings': (ds,el)=>filterSettings(el.value),
};
document.addEventListener('click', e=>{
  const el=e.target.closest('[data-action]');
  if(el && CLICK_ACTIONS[el.dataset.action]) CLICK_ACTIONS[el.dataset.action](el.dataset);
}, true);
document.addEventListener('input', e=>{
  const el=e.target.closest('[data-action]');
  if(el && FIELD_ACTIONS[el.dataset.action]) FIELD_ACTIONS[el.dataset.action](el.dataset, el);
});
(function bindDlg(){
  const ok=document.getElementById('ui-dlg-ok');
  const cancel=document.getElementById('ui-dlg-cancel');
  const inp=document.getElementById('ui-dlg-input');
  const ov=document.getElementById('ui-dialog');
  if(ok) ok.addEventListener('click',()=>{ const useInput=inp.style.display!=='none'; __closeDlg(useInput?inp.value:true); });
  if(cancel) cancel.addEventListener('click',()=>__closeDlg(null));
  if(ov) ov.addEventListener('click',e=>{ if(e.target===ov) __closeDlg(null); });
  if(inp) inp.addEventListener('keydown',e=>{ if(e.key==='Enter'){e.preventDefault(); __closeDlg(inp.value);} if(e.key==='Escape'){__closeDlg(null);} });
})();
}
