// Flat ESLint config (ESLint 9). Scoped to the js/*.js module graph the
// same way tsconfig.json is -- js/vendor/** (Preact/Tesseract) is excluded,
// never meant to be linted. This is a correctness/hygiene net (unused vars,
// undeclared globals, duplicate object keys), not a style formatter -- no
// Prettier here, this repo's existing hand-authored formatting stays as-is.
export default [
  {
    ignores: ["js/vendor/**", "dist/**", "node_modules/**"],
  },
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Standard browser/DOM globals this codebase actually uses.
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        Notification: "readonly",
        navigator: "readonly",
        URLSearchParams: "readonly",
        URL: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        Intl: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        history: "readonly",
        location: "readonly",
        alert: "readonly",
        confirm: "readonly",
        matchMedia: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        createImageBitmap: "readonly",
        OffscreenCanvas: "readonly",
        Worker: "readonly",
        WebAssembly: "readonly",
        WebAssembly2: "readonly",
        PublicKeyCredential: "readonly",
        getComputedStyle: "readonly",
        Blob: "readonly",
        crypto: "readonly",
        TextEncoder: "readonly",
        btoa: "readonly",
        atob: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        self: "readonly",
        globalThis: "readonly",
        importScripts: "readonly",
        firebase: "readonly",
        // Bare classic-globals.js functions (see types/globals.d.ts --
        // real window.* properties called bare, not ES module exports).
        tr: "readonly",
        Icon: "readonly",
        setIcon: "readonly",
        translateStaticDOM: "readonly",
        setLang: "readonly",
        setTheme: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none" }],
      "no-undef": "error",
      "no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-dupe-class-members": "error",
      "no-fallthrough": "warn",
      "no-const-assign": "error",
      "no-case-declarations": "warn",
      "no-unsafe-negation": "error",
      "no-self-assign": "error",
      "no-unreachable": "error",
    },
  },
];
